from __future__ import annotations

import unittest
from pathlib import Path

from rapidtriage.core.visible_capabilities import CAPABILITY_GROUPS, build_visible_capability_response, validate_visible_capability_contract


REPO_ROOT = Path(__file__).resolve().parents[1]


class RapidTriageWebStaticTests(unittest.TestCase):
    def test_web_artifact_workbench_exposes_ntfs_replay_review_cards(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("ntfsArtifactPreviewText", app_js)
        self.assertIn("renderNtfsReplayPreviewArtifactCard", app_js)
        self.assertIn("usn_replay_inventory_profile", app_js)
        self.assertIn("bounded_mft_replay_preview", app_js)
        self.assertIn("mft_bounded_path_cache_profile", app_js)
        self.assertIn("MFT cache quality", app_js)
        self.assertIn("MFT partial path warnings", app_js)
        self.assertIn("usn_path_reliability_profile", app_js)
        self.assertIn("Path reliability", app_js)
        self.assertIn("Reliability wording", app_js)
        self.assertIn("rename_pair_preview", app_js)
        self.assertIn("delete_lifecycle_preview", app_js)
        self.assertIn("bounded_state_replay_preview", app_js)
        self.assertIn("usn_state_replay_validation_profile", app_js)
        self.assertIn("State replay validation", app_js)
        self.assertIn("State validation wording", app_js)
        self.assertIn("Delete lifecycle", app_js)
        self.assertIn("State transitions", app_js)
        self.assertIn("Bounded state replay", app_js)
        self.assertIn("STATE paired OLD", app_js)
        self.assertIn("USN replay preview", app_js)
        self.assertIn("renderNtfsSourceLocatorLinks", app_js)
        self.assertIn("Source locators", app_js)
        self.assertIn("source-hex-range", app_js)
        self.assertIn("include_hashes=true", app_js)
        self.assertIn("errorMessageFromDetail", app_js)
        self.assertIn("renderSourceResolutionDiagnostics", app_js)
        self.assertIn("source_path_resolution", app_js)
        self.assertIn("Source path resolution diagnostics", app_js)
        self.assertIn("Court-grade rename/delete replay still requires full-journal ordering", app_js)

    def test_web_workbench_exposes_run_validation_diff_inventory_panel(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("data-testid=\"run-validation-diff-panel\"", app_js)
        self.assertIn("loadRunValidationPackageSummary", app_js)
        self.assertIn("renderRunValidationPackageSummary", app_js)
        self.assertIn("diff_inventory", app_js)
        self.assertIn("usn_state_replay_diff_attached", app_js)
        self.assertIn("usn_state_replay_diff_pass_count", app_js)
        self.assertIn("usn_state_replay_status", app_js)
        self.assertIn("Run validation diff inventory", app_js)
        self.assertIn("run-validation-diff-panel", styles)
        self.assertIn("validation-diff-card", styles)
        self.assertIn("validation-diff-list", styles)
        self.assertIn("compact-dl", styles)

    def test_web_workbench_exposes_mac_first_evidence_detail_rows(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("MAC_FIRST_EVIDENCE_STORAGE_KEY", app_js)
        self.assertIn("bindMacFirstEvidenceControls", app_js)
        self.assertIn("data-testid=\"mac-first-evidence-form\"", app_js)
        self.assertIn("Apply Mac evidence", app_js)
        self.assertIn("clearMacFirstEvidence", app_js)
        self.assertIn("params.set(\"mac_first_evidence\"", app_js)
        self.assertIn("renderMacFirstEvidenceRows", app_js)
        self.assertIn("macFirstEvidenceSummaryText", app_js)
        self.assertIn("data-testid=\"mac-first-evidence-rows\"", app_js)
        self.assertIn("Attached Mac evidence", app_js)
        self.assertIn("evidence_manifest_hash", app_js)
        self.assertIn("ready_for_trusted_diff", app_js)
        self.assertIn("trusted diff", app_js)
        self.assertIn("mac-first-evidence-rows", styles)
        self.assertIn("mac-first-evidence-list", styles)
        self.assertIn("mac-first-evidence-form", styles)
        self.assertIn("mac-first-evidence-controls", styles)

    def test_search_results_expose_review_facets_for_fast_triage(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("renderSearchFacets", app_js)
        self.assertIn("review facets", app_js)
        self.assertIn("search-facet-chip[data-filter]", app_js)
        self.assertIn("aria-label=\"Filter results by", app_js)
        self.assertIn("search-facet-panel", styles)
        self.assertIn("search-facet-chip", styles)

    def test_workbench_review_queue_and_schema_visibility_contracts(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        state_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_state.js").read_text(encoding="utf-8")
        index_html = (REPO_ROOT / "rapidtriage" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('/assets/app_workbench_config.js', index_html)
        self.assertIn('/assets/app_state.js', index_html)
        self.assertLess(index_html.index('/assets/app_workbench_config.js'), index_html.index('/assets/app.js'))
        self.assertLess(index_html.index('/assets/app_workbench_config.js'), index_html.index('/assets/app_state.js'))
        self.assertLess(index_html.index('/assets/app_state.js'), index_html.index('/assets/app.js'))
        self.assertIn("function persistWorkbenchSession", state_js)
        self.assertIn("activeStageId,", state_js)
        self.assertIn("activeStageSubactionId,", state_js)
        self.assertIn("activeStageId = payload.activeStageId || \"\";", state_js)
        self.assertIn("activeStageSubactionId = payload.activeStageSubactionId || \"\";", state_js)
        self.assertIn("let activeStageId = \"\";", app_js)
        self.assertIn("let activeStageSubactionId = \"\";", app_js)
        self.assertIn("function stageIdForTab", app_js)
        self.assertIn("function stageCountTitle", app_js)
        self.assertIn("function renderStageCountBadge", app_js)
        self.assertIn("function artifactRowGroupCount", app_js)
        self.assertIn("function clientFilteredRows", app_js)
        self.assertIn("function updateClientFilterSummary", app_js)
        self.assertIn("현재 화면 필터 결과", app_js)
        self.assertIn("data-client-filter-summary", app_js)
        self.assertIn("client-filter-empty", app_js)
        self.assertIn("발견 항목", app_js)
        self.assertIn("숫자 = 발견 항목 수", app_js)
        self.assertIn("stage-nav-capability-summary", app_js)
        self.assertIn("전체 기능 요약", app_js)
        self.assertIn("작업 입구", app_js)
        self.assertIn("세부 이동", app_js)
        self.assertIn("기능 지도", app_js)
        self.assertIn("const totalSubactions = stages.reduce", app_js)
        self.assertIn("const totalCapabilities = capabilityGroups.reduce", app_js)
        self.assertIn(".stage-nav-capability-summary", styles)
        self.assertIn(".stage-nav-capability-note", styles)
        self.assertIn("<small>건</small>", app_js)
        self.assertIn("class=\"${escapeHtml(className)}\"", app_js)
        self.assertIn("stage-count-badge", app_js)
        self.assertIn("className: \"stage-subaction-count\"", app_js)
        self.assertIn("title=\"${escapeHtml(title)}\"", app_js)
        self.assertIn("aria-label=\"${escapeHtml(title)}\"", app_js)
        self.assertIn("function caseStageFlow(run, tab, currentStageId = \"\")", app_js)
        self.assertIn("const stages = caseStageFlow(run, tab, activeStageId);", app_js)
        self.assertIn("data-stage-id=\"${escapeHtml(stage.id)}\"", app_js)
        self.assertIn("data-stage-subaction", app_js)
        self.assertIn("data-source-category-filter", app_js)
        self.assertIn("stage-nav-subactions-drawer", app_js)
        self.assertIn("세부 항목", app_js)
        self.assertIn("class=\"stage-subaction", app_js)
        self.assertIn("const stageId = button.dataset.stageId || activeStageId || \"source\";", app_js)
        self.assertIn("const stageSubactionId = button.dataset.stageSubaction || \"\";", app_js)
        self.assertIn("const sourceCategoryFilter = button.dataset.sourceCategoryFilter || \"\";", app_js)
        self.assertIn("const filter = button.dataset.artifactFilter || \"\";", app_js)
        self.assertIn("activeArtifactFilter = targetTab === \"artifacts\" ? sourceCategoryFilter : \"\";", app_js)
        self.assertIn("activeStageId = stageId;", app_js)
        self.assertIn("activeStageSubactionId = stageSubactionId;", app_js)
        self.assertIn("async function switchTab(tab, options = {})", app_js)
        self.assertIn("function renderVirtualizationNotice", state_js)
        self.assertIn("function getSearchDraft", state_js)
        self.assertIn("data-testid=\"artifact-tree-lane-find\"", app_js)
        self.assertIn("data-testid=\"artifact-tree-lane-deliver\"", app_js)
        self.assertIn("tab: \"summary\", label: \"Overview\"", config_js)
        self.assertIn("tab: \"indicators\", label: \"Indicators\"", config_js)
        self.assertIn("data-testid=\"forensic-view-mode-bar\"", app_js)
        self.assertIn("aria-current=\"${mode.tab === tab ? \"page\" : \"false\"}\"", app_js)
        self.assertIn("aria-live=\"polite\"", app_js)
        self.assertIn("viewer.setAttribute(\"aria-busy\", \"true\")", app_js)
        self.assertIn("viewer.setAttribute(\"aria-busy\", \"false\")", app_js)
        self.assertIn("data-artifact-filter", app_js)
        self.assertIn("applyArtifactTreeFilter", app_js)
        self.assertIn("data-testid=\"review-bulk-queue\"", app_js)
        self.assertIn("review-bulk-toolbar", app_js)
        self.assertIn("Find related", app_js)
        self.assertIn("Prepare report", app_js)
        self.assertIn("renderSqliteSchemaPanel", app_js)
        self.assertIn("data-testid=\"sqlite-schema-panel\"", app_js)
        self.assertIn("Schema visibility", app_js)
        self.assertIn("renderSqliteSidecarState", app_js)
        self.assertIn("data-testid=\"sqlite-sidecar-state\"", app_js)
        self.assertIn("requires_wal_review", app_js)
        self.assertIn("sqlite-sidecar-warning", app_js)
        self.assertIn("sqlite-wal-preview", app_js)
        self.assertIn("source-sqlite-wal-preview", app_js)
        self.assertIn("data-sqlite-wal-preview-path", app_js)
        self.assertIn("renderSqliteWalPreviewInline", app_js)
        self.assertIn("data-testid=\"sqlite-wal-preview-panel\"", app_js)
        self.assertIn("estimated_frame_count", app_js)
        self.assertIn("renderEmailParseDiagnostics", app_js)
        self.assertIn("data-testid=\"email-parse-diagnostics\"", app_js)
        self.assertIn("Do not conclude the mailbox is complete", app_js)
        self.assertIn("renderDocsIndexSidecarSearch", app_js)
        self.assertIn("data-testid=\"docs-index-sidecar-search\"", app_js)
        self.assertIn("docs-index-search", app_js)
        self.assertIn("/docs-index-search?", app_js)
        self.assertIn("stores_full_text=false", app_js)
        self.assertIn("data-focus-file-search-keywords", app_js)
        self.assertIn("source_viewer_action_profile: result.source_viewer_action_profile", app_js)
        self.assertIn("input.form?.requestSubmit()", app_js)
        self.assertIn("Copy citation", app_js)
        self.assertIn("review_note_citation.text", app_js)
        self.assertIn("artifact-tree-lane", styles)
        self.assertIn("review-bulk-toolbar", styles)
        self.assertIn("sqlite-schema-panel", styles)
        self.assertIn("sqlite-column-chip", styles)
        self.assertIn("sqlite-sidecar-card", styles)
        self.assertIn("sqlite-sidecar-chip", styles)
        self.assertIn("email-diagnostics-card", styles)
        self.assertIn("docs-index-sidecar-search", styles)

    def test_forensic_operator_layout_exposes_available_features_without_stage_coupling(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("FEATURE_PLACEMENT_CONTRACT", config_js)
        self.assertIn("forensic-feature-placement-contract-v1", config_js)
        self.assertIn("one-primary-home-per-feature-family", config_js)
        self.assertIn("primary-review-pane", config_js)
        self.assertIn("right-intelligence-panel", config_js)
        self.assertIn("global filters detached from result tables", config_js)
        self.assertIn("data-placement-contract=\"${escapeHtml(FEATURE_PLACEMENT_CONTRACT.profile_version)}\"", app_js)
        self.assertIn("redundant-tab-row", app_js)
        for label in ("증거/이미지", "검색/단서", "자료 검토", "행위 흔적", "타임라인", "리뷰/보고"):
            self.assertIn(label, app_js)
        for subnav_label in ("이미지/E01", "추출 폴더", "해시/제한", "키워드/본문", "URL/계정", "IOC/위험", "문서/PDF", "메일/첨부", "사진/OCR", "영상/오디오", "KakaoTalk", "WhatsApp/Telegram", "모바일/SMS", "EVTX", "Registry/NTUSER", "USB/Shellbag", "실행 흔적", "MFT/USN", "EDB/검색", "브라우저 기록", "다운로드/캐시", "AI 질문/답변", "기타/미분류", "전체 시간축", "윈도우 이벤트", "파일 변경", "웹/AI 활동", "삭제/변경", "리뷰보드", "보고 후보", "인용/해시", "제출 산출물"):
            self.assertIn(subnav_label, app_js)
        self.assertIn("renderUsableCapabilityMap", app_js)
        self.assertIn("data-testid=\"usable-capability-map\"", app_js)
        self.assertIn("현재 사용 가능한 분석 모듈 현황", app_js)
        self.assertIn("여기 숫자는 발견 항목이 아니라, 해당 분류에 묶인 구현 기능 수입니다.", app_js)
        self.assertIn("구현 기능 ${formatNumber(capabilities.length)}개", app_js)
        self.assertIn("<small>기능</small>", app_js)
        self.assertIn("renderForensicQuestionBar", app_js)
        self.assertIn("data-testid=\"case-question-bar\"", app_js)
        self.assertIn("renderIntelDrawer", app_js)
        self.assertIn("data-testid=\"intel-collapsible-card\"", app_js)
        self.assertIn("forensicQuestionItems", app_js)
        self.assertIn("case-question-drawer", app_js)
        self.assertIn("질문 피벗", app_js)
        self.assertIn("Stage subnavigation", styles)
        self.assertIn(".stage-count-legend", styles)
        self.assertIn(".stage-count-badge small", styles)
        self.assertIn(".stage-subaction-count small", styles)
        self.assertIn(".stage-nav-item.active .stage-nav-subactions", styles)
        self.assertIn(".stage-nav-subactions-drawer:not([open]) > .stage-nav-subactions", styles)
        self.assertIn(".stage-subaction.active", styles)
        self.assertIn(".client-filter-summary", styles)
        self.assertIn(".client-filter-summary.empty", styles)
        self.assertIn(".client-filter-empty .review-list-shell", styles)
        self.assertIn("renderOutputAvailabilityStrip", app_js)
        self.assertIn("data-testid=\"output-availability-strip\"", app_js)
        self.assertIn("renderSecondaryWorkbenchControls", app_js)
        self.assertIn("data-testid=\"secondary-workbench-drawer\"", app_js)
        self.assertIn("상태 · 피벗 · 단축키", app_js)
        self.assertIn("outputAvailabilityItems", app_js)
        self.assertIn("availabilityStatusLabel", app_js)
        self.assertIn("renderRowActionDock", app_js)
        self.assertIn("data-testid=\"row-action-dock\"", app_js)
        self.assertIn("renderViewerEmptyState", app_js)
        self.assertIn("data-testid=\"viewer-empty-state\"", app_js)
        self.assertIn("1-click preview", app_js)
        self.assertIn("renderSearchScopePlanner", app_js)
        self.assertIn("data-testid=\"search-scope-planner\"", app_js)
        self.assertIn("bindSearchScopePlanner", app_js)
        self.assertIn("renderArtifactPivotStrip", app_js)
        self.assertIn("data-testid=\"artifact-pivot-strip\"", app_js)
        self.assertIn("artifactPivotItems", app_js)
        self.assertIn("renderDocumentReviewLanes", app_js)
        self.assertIn("data-testid=\"document-review-lanes\"", app_js)
        self.assertIn("data-doc-lane-filter", app_js)
        self.assertIn("renderTimelineReviewLanes", app_js)
        self.assertIn("data-testid=\"timeline-review-lanes\"", app_js)
        self.assertIn("data-timeline-lane-filter", app_js)
        self.assertIn("tab-assist-drawer document-review-lanes", app_js)
        self.assertIn("tab-assist-drawer timeline-review-lanes", app_js)
        self.assertIn("renderReviewStateDashboard", app_js)
        self.assertIn("data-testid=\"review-state-dashboard\"", app_js)
        self.assertIn("data-review-status-filter", app_js)
        self.assertIn("applyReviewStatusFilter", app_js)
        self.assertIn("renderReportReadinessGate", app_js)
        self.assertIn("data-testid=\"report-readiness-gate\"", app_js)
        self.assertIn("renderValidationReadinessBanner", app_js)
        self.assertIn("data-testid=\"validation-readiness-banner\"", app_js)
        self.assertIn("renderOperatorShortcutStrip", app_js)
        self.assertIn("data-testid=\"operator-shortcut-strip\"", app_js)
        self.assertIn("executeKeyboardStripAction", app_js)
        self.assertIn("previewFirstVisibleRow", app_js)
        for scope in ("전체 케이스", "현재 파일/뷰어", "아티팩트 피벗"):
            self.assertIn(scope, app_js)
        for pivot in ("EVTX", "Registry", "Browser/AI", "USB/외부장치", "MFT/USN", "EDB/검색", "메신저", "Media/OCR"):
            self.assertIn(pivot, app_js)
        for lane in ("문서·메일·대화 검토 레인", "메일/첨부", "OCR/이미지", "보고 후보"):
            self.assertIn(lane, app_js)
        for lane in ("파일 생성/수정", "웹·AI 활동", "윈도우 이벤트", "외부장치/반출", "삭제/위험"):
            self.assertIn(lane, app_js)
        for review_label in ("선별 작업대", "관련 있음", "재검토", "보고 포함"):
            self.assertIn(review_label, app_js)
        for report_gate in ("제출 전 점검", "해시/manifest", "인용 근거", "제한사항", "제출 묶음"):
            self.assertIn(report_gate, app_js)
        for validation_label in ("검증 게이트", "원본 확인 후 판단", "parser limitation", "원본/해시"):
            self.assertIn(validation_label, app_js)
        for shortcut_label in ("빠른 조작", "첫 결과 미리보기", "관련 있음 저장", "Ctrl/Cmd K"):
            self.assertIn(shortcut_label, app_js)
        for availability in ("접수/해시", "아티팩트", "문서/메일", "파일/미디어", "시간축", "전체검색", "선별", "보고서"):
            self.assertIn(availability, app_js)
        for status in ("단서 있음", "선별 전", "부분 경로", "단서 0", "산출물 없음"):
            self.assertIn(status, app_js)
        for question in ("키워드 단서", "USB/반출", "웹·AI 사용", "문서·메일", "시간 재구성", "보고 후보"):
            self.assertIn(question, app_js)
        self.assertIn("renderTabLoadError", app_js)
        self.assertIn("data-testid=\"tab-load-error\"", app_js)
        self.assertIn("필요한 산출물 파일을 찾을 수 없습니다", app_js)
        self.assertIn("rapidtriage-[\\w-]+\\.json", app_js)
        self.assertIn("data-nav-scope=\"workflow\"", app_js)
        self.assertIn("data-nav-scope=\"source\"", app_js)
        self.assertIn("data-nav-scope=\"capability-map\"", app_js)
        self.assertIn("switchTab(targetTab, { syncStage: false })", app_js)
        self.assertIn("switchTab(targetTab, { stageId, stageSubactionId, syncStage: true })", app_js)
        self.assertIn("applyArtifactTreeFilter(filter)", app_js)
        self.assertIn("prioritizeCapabilityGroupsForTab", app_js)
        self.assertIn("summarizeCapabilityStatuses", app_js)
        self.assertIn("capabilityGroupTab", app_js)
        self.assertIn("capabilityGroupFilter", app_js)
        self.assertIn("status-${safeCssToken(status)}", app_js)
        self.assertIn(".capability-map-card", styles)
        self.assertIn(".capability-map-row", styles)
        self.assertIn(".capability-status-pill.status-usable", styles)
        self.assertIn(".case-question-bar", styles)
        self.assertIn(".timeline-review-lanes", styles)
        self.assertIn("button.timeline-lane-card", styles)
        self.assertIn(".review-state-dashboard", styles)
        self.assertIn("button.review-state-chip", styles)
        self.assertIn(".report-readiness-gate", styles)
        self.assertIn("button.report-gate-card", styles)
        self.assertIn(".validation-readiness-banner", styles)
        self.assertIn(".validation-gate-actions", styles)
        self.assertIn(".operator-shortcut-strip", styles)
        self.assertIn("button.operator-shortcut-button", styles)
        self.assertIn("--rf-type-body", styles)
        self.assertIn("--rf-line-readable", styles)
        self.assertIn("Typography and position calibration", styles)
        self.assertIn("Overlap-safe control calibration", styles)
        self.assertIn("Overlap clipping and row rhythm", styles)
        self.assertIn("Center-lane overlap fix", styles)
        self.assertIn("Compact strip containment pass", styles)
        self.assertIn("Primary pane flex-shrink guard", styles)
        self.assertIn("Progressive disclosure for dense operator controls", styles)
        self.assertIn(".secondary-workbench-drawer", styles)
        self.assertIn(".secondary-workbench-drawer:not([open]) .secondary-workbench-grid", styles)
        self.assertIn(".secondary-workbench-grid", styles)
        self.assertIn("Intelligence panel progressive disclosure", styles)
        self.assertIn(".intel-collapsible-card", styles)
        self.assertIn(".intel-collapsible-card:not([open]) .intel-collapsible-body", styles)
        self.assertIn(".intelligence-panel > .intel-collapsible-card[open]", styles)
        self.assertIn("overscroll-behavior: contain", styles)
        self.assertIn("Result-lane progressive disclosure", styles)
        self.assertIn(".tab-assist-drawer:not([open]) .tab-assist-body", styles)
        self.assertIn("Feature placement audit", styles)
        self.assertIn(".redundant-tab-row", styles)
        self.assertIn(".primary-review-pane > .table-control-bar", styles)
        self.assertIn(".primary-review-pane > .case-question-drawer", styles)
        self.assertIn("질문 열기", styles)
        self.assertIn("repeat(auto-fit, minmax(138px, 1fr))", styles)
        self.assertIn("repeat(auto-fit, minmax(162px, 1fr))", styles)
        self.assertIn("grid-auto-rows: minmax(42px, auto)", styles)
        self.assertIn("grid-auto-rows: minmax(40px, auto)", styles)
        self.assertIn("button.case-question-chip", styles)
        self.assertIn(".output-availability-strip", styles)
        self.assertIn("button.output-availability-chip", styles)
        self.assertIn(".output-availability-chip.status-ready", styles)
        self.assertIn(".row-action-dock", styles)
        self.assertIn(".row-action-dock .primary-viewer-action", styles)
        self.assertIn(".operator-viewer-empty", styles)
        self.assertIn(".viewer-empty-checklist", styles)
        self.assertIn(".search-scope-planner", styles)
        self.assertIn("button.search-scope-card", styles)
        self.assertIn(".artifact-pivot-strip", styles)
        self.assertIn("button.artifact-pivot-chip", styles)
        self.assertIn(".document-review-lanes", styles)
        self.assertIn("button.document-lane-card", styles)
        self.assertIn(".tab-error-card", styles)
        self.assertIn("Priority 1 forensic operator layout", styles)

    def test_lazyweb_command_center_is_connected_to_workbench_tabs(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("LAZYWEB_WORKBENCH_MODEL", config_js)
        self.assertIn("lazyweb-command-center-model-v1", config_js)
        self.assertIn("https://www.lazyweb.com/canvas/flows/raycast/manage-models", config_js)
        self.assertIn("Evidence intake", config_js)
        self.assertIn("Unified search", config_js)
        self.assertIn("Source verify", config_js)
        self.assertIn("Review board", config_js)
        self.assertIn("Report bundle", config_js)
        self.assertIn("renderAdvancedDiagnosticsPanel", app_js)
        self.assertIn("data-testid=\"advanced-diagnostics-panel\"", app_js)
        self.assertIn("developer-diagnostics-drawer", app_js)
        self.assertIn("renderLazywebCommandCenter", app_js)
        self.assertIn("data-testid=\"lazyweb-command-center\"", app_js)
        self.assertIn("data-open-tab=\"search\"", app_js)
        self.assertIn("data-artifact-filter=\"${escapeHtml(command.filter || \"\")}\"", app_js)
        self.assertIn(".lazyweb-command-center", styles)
        self.assertIn(".lazyweb-command-grid", styles)
        self.assertIn("body.analysis-active .lazyweb-command-center", styles)

    def test_forensic_feature_catalog_makes_available_functions_discoverable(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("FORENSIC_FEATURE_CATALOG", config_js)
        self.assertIn("증거 입력 / 케이스", config_js)
        self.assertIn("Windows 핵심 아티팩트", config_js)
        self.assertIn("웹 / AI 사용 기록", config_js)
        self.assertIn("메신저 / 이메일", config_js)
        self.assertIn("문서 / DB / 본문 검색", config_js)
        self.assertIn("docs-index sidecar", config_js)
        self.assertIn("sidecar-index", config_js)
        self.assertIn("이미지 / 영상 / OCR", config_js)
        self.assertIn("타임라인 / IOC / DFIR", config_js)
        self.assertIn("모바일 / 클라우드", config_js)
        self.assertIn("리뷰 / 보고서 / 제출", config_js)
        self.assertIn("renderForensicFeatureCatalog", app_js)
        self.assertIn("data-testid=\"forensic-feature-catalog\"", app_js)
        self.assertIn("개발/QC 전용 기능 구현 지도", app_js)
        self.assertIn("일반 검토는 왼쪽 분류와 가운데 리뷰 화면을 사용하세요", app_js)
        self.assertIn("feature-catalog-card", app_js)
        self.assertIn("data-open-tab=\"${escapeHtml(item.tab)}\"", app_js)
        self.assertIn("data-artifact-filter=\"${escapeHtml(filterTerm)}\"", app_js)
        self.assertIn(".forensic-feature-catalog", styles)
        self.assertIn(".feature-catalog-grid", styles)
        self.assertIn("body.analysis-active .forensic-feature-catalog", styles)
        self.assertIn(".advanced-diagnostics-panel", styles)
        self.assertIn(".developer-diagnostics-drawer:not([open]) .forensic-feature-catalog", styles)

    def test_hidden_forensic_capabilities_are_exposed_as_visible_steps(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("VISIBLE_FORENSIC_CAPABILITY_GROUPS", config_js)
        self.assertIn("VISIBLE_CAPABILITY_STATUS_LABELS", config_js)
        self.assertIn("browser-history", config_js)
        self.assertIn("브라우저 방문 기록", config_js)
        self.assertIn("browser-ai-usage", config_js)
        self.assertIn("AI 서비스 방문 기록", config_js)
        self.assertIn("browser-ai-conversation", config_js)
        self.assertIn("AI 질문/답변 후보", config_js)
        self.assertIn("browser-storage-inventory", config_js)
        self.assertIn("docs-index-sidecar-search", config_js)
        self.assertIn("문서 인덱스 sidecar 재검색", config_js)
        self.assertIn("processed-text-inverted-index", config_js)
        self.assertIn("docs-index-citation-review", config_js)
        self.assertIn("docs-index-review-note-citation-v1", config_js)
        self.assertIn("bookmark-source-mapping-required", config_js)
        self.assertIn("current-file-search-resume", config_js)
        self.assertIn("source-search-full-cursor-scan-contract-v1", config_js)
        self.assertIn("source-search-sqlite-resume-v1", config_js)
        self.assertIn("document_extraction_limits", config_js)
        self.assertIn("sqlite-sidecar-wal-preview", config_js)
        self.assertIn("source-sqlite-wal-preview", config_js)
        self.assertIn("sqlite-sidecar-preview", config_js)
        self.assertIn("commercial-readiness-gate", config_js)
        self.assertIn("commercial-readiness-gui-gate-v1", config_js)
        self.assertIn("commercial_claim_allowed", config_js)
        self.assertIn("internal-known-answer", config_js)
        self.assertIn("mapped evidence", config_js)
        self.assertIn("source-viewer-hit-context-validation-required", config_js)
        self.assertIn("eventlog-chunk", config_js)
        self.assertIn("eventlog-record-candidate", config_js)
        self.assertIn("evtx_recovery_report_citation_manifest", config_js)
        self.assertIn("evtx_message_rendering_profile", config_js)
        self.assertIn("registry-user-activity", config_js)
        self.assertIn("registry-key-recovery-candidate", config_js)
        self.assertIn("registry-value-recovery-candidate", config_js)
        self.assertIn("registry_report_citation_manifest", config_js)
        self.assertIn("ads-stream-inventory", config_js)
        self.assertIn("ads-stream-candidate", config_js)
        self.assertIn("archive-encrypted-inventory", config_js)
        self.assertIn("archive-file-inventory", config_js)
        self.assertIn("windows-search-edb-row-candidate", config_js)
        self.assertIn("windows-search-edb-page-candidate", config_js)
        self.assertIn("virtual-disk-workflow", config_js)
        self.assertIn("qemu_img_info_profile", config_js)
        self.assertIn("virtual_disk_chain_profile", config_js)
        self.assertIn("forensic-container-workflow", config_js)
        self.assertIn("verified_export_manifest_profile", config_js)
        self.assertIn("forensic_container_workflow_manifest", config_js)
        self.assertIn("browser_analyst_review_profile", config_js)
        self.assertIn("mobile-message", config_js)
        self.assertIn("kakaotalk-windows-app-database", config_js)
        self.assertIn("kakaotalk-macos-database", config_js)
        self.assertIn("chat_app_forensic_review", config_js)
        self.assertIn("messenger-export-framework-manifest", config_js)
        self.assertIn("cloud-message", config_js)
        self.assertIn("icloud_export_review_profile", config_js)
        self.assertIn("icloud_export_parser_manifest", config_js)
        self.assertIn("m365_export_review_profile", config_js)
        self.assertIn("m365_export_parser_manifest", config_js)
        self.assertIn("teams_message_review_profile", app_js)
        self.assertIn("m365_file_permission_review_profile", app_js)
        self.assertIn("m365_file_state_review_profile", app_js)
        self.assertIn("cloud-export-review-card", app_js)
        self.assertIn("media-audio", config_js)
        self.assertIn("waveform_preview", config_js)
        self.assertIn("transcript_sidecars", config_js)
        self.assertIn("media-cue-proof-manifest", config_js)
        self.assertIn("memory-dump-indicators", config_js)
        self.assertIn("dfir-webshell-log", config_js)
        self.assertIn("webshell-source-candidate", config_js)
        self.assertIn("web-server-log", config_js)
        self.assertIn("webshell_semantic_profile", config_js)
        self.assertIn("webshell_log_correlation", config_js)
        self.assertIn("webshell_report_citation_package", config_js)
        self.assertIn("ai-service-export-conversation", config_js)
        self.assertIn("ai_service_export_parser_manifest", config_js)
        self.assertIn("mapi_container_review_profile", config_js)
        self.assertIn("email_mailbox_parser_manifest", config_js)
        self.assertIn("fde_operator_runbook", config_js)
        self.assertIn("trusted-decryption-workflow-log-required", config_js)
        for capability_id in (
            "evidence-vss-apfs-snapshot",
            "evidence-fde-unlock",
            "evidence-unallocated-carving",
            "ntfs-logfile-transactions",
            "timestamp-stomping-detection",
            "signature-mismatch-detection",
            "etl-trace-parser",
            "eventlog-clearing-alert",
            "usb-external-device-history",
            "autoruns-persistence-view",
            "lnk-jumplist-analysis",
            "windows-timeline-activities",
            "webcachev01-ese-parser",
            "local-llm-ollama-lmstudio-gpt4all",
            "windows-copilot-recall",
            "print-spooler-spl-shd",
            "geo-location-map-viewer",
            "aws-cloudtrail-parser",
            "exif-gps-map",
            "hiberfil-pagefile-carving",
            "remote-control-anydesk-teamviewer-rustdesk",
            "super-timeline-plaso-style",
            "denisting-nsrl-whitelist",
            "yara-ioc-scanner",
        ):
            self.assertIn(capability_id, config_js)
        self.assertIn("renderVisibleCapabilityGroups", app_js)
        self.assertIn("sqlite_resume_token", app_js)
        self.assertIn("file_resume_token", app_js)
        self.assertIn("data-file-search-resume", app_js)
        self.assertIn("data-file-search-resume-kind", app_js)
        self.assertIn("Continue SQLite search", app_js)
        self.assertIn("Continue large file search", app_js)
        self.assertIn("doc cap", app_js)
        self.assertIn("PDF stream cap", app_js)
        self.assertIn("No matches in the searched window yet", app_js)
        self.assertIn("Continue from the cursor before concluding the keyword is absent", app_js)
        self.assertIn("resumeCurrentFileSearch", app_js)
        self.assertIn("visibleCapabilityGroupsForRun", app_js)
        self.assertIn("loadRunCapabilities", app_js)
        self.assertIn("/capabilities", app_js)
        self.assertIn("group.catalogId || group.catalog_id", app_js)
        self.assertIn("capability.artifactTypes || capability.artifact_types", app_js)
        self.assertIn("capability.nextAction || capability.next_action", app_js)
        self.assertIn("data-workflow-stage", app_js)
        self.assertIn("data-viewer", app_js)
        self.assertIn("capabilitySignalLookup", app_js)
        self.assertIn("matched signals", app_js)
        self.assertIn("visible steps", app_js)
        self.assertIn("feature-capability-chip", app_js)
        self.assertIn("data-capability-filter", app_js)
        self.assertIn("data-signal-count", app_js)
        self.assertIn("capability?.dataset.capabilityFilter", app_js)
        self.assertIn("safeCssToken", app_js)
        self.assertIn(".feature-capability-groups", styles)
        self.assertIn(".feature-capability-chip.has-signals", styles)
        self.assertIn(".feature-capability-chip.status-validation-required", styles)
        self.assertIn("body.analysis-active .feature-capability-group", styles)

    def test_visible_forensic_capability_ids_stay_synced_between_api_and_gui(self) -> None:
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")

        python_ids = [
            capability["id"]
            for group in CAPABILITY_GROUPS
            for capability in group["capabilities"]
        ]
        self.assertGreaterEqual(len(python_ids), 80)
        for capability_id in python_ids:
            self.assertIn(capability_id, config_js)

    def test_visible_capability_registry_has_gui_contract_for_every_feature(self) -> None:
        issues = validate_visible_capability_contract()
        payload = build_visible_capability_response()
        capabilities = {
            capability["id"]: capability
            for group in payload["groups"]
            for capability in group["capabilities"]
        }

        self.assertEqual(issues, [])
        self.assertTrue(payload["summary"]["gui_contract_pass"])
        self.assertEqual(payload["gui_contract"]["issue_count"], 0)
        self.assertEqual(capabilities["media-audio"]["status"], "partial")
        self.assertIn("media-audio", capabilities["media-audio"]["artifact_types"])
        self.assertEqual(capabilities["dfir-webshell-log"]["status"], "partial")
        self.assertIn("webshell-source-candidate", capabilities["dfir-webshell-log"]["artifact_types"])
        self.assertIn("web-server-log", capabilities["dfir-webshell-log"]["artifact_types"])
        for capability_id in (
            "windows-search-edb-row-candidate",
            "browser-storage-inventory",
            "kakaotalk-macos-inventory",
            "messenger-whatsapp-telegram-signal-line",
            "cloud-icloud-export",
            "cloud-message",
            "image-vm-disk",
            "image-export-only",
            "browser-ai-export-parser",
            "eventlog-provider-message-rendering",
            "eventlog-corrupt-recovery",
            "registry-deleted-candidate",
            "email-pst-ost-import",
        ):
            self.assertEqual(capabilities[capability_id]["status"], "partial")
        self.assertIn("virtual-disk-workflow", capabilities["image-vm-disk"]["artifact_types"])
        self.assertIn("forensic-container-workflow", capabilities["image-export-only"]["artifact_types"])
        self.assertIn("ai-service-export-conversation", capabilities["browser-ai-export-parser"]["artifact_types"])
        self.assertIn("eventlog-event", capabilities["eventlog-provider-message-rendering"]["artifact_types"])
        self.assertIn("eventlog-record-candidate", capabilities["eventlog-corrupt-recovery"]["artifact_types"])
        self.assertIn("registry-deleted-cell-candidate", capabilities["registry-deleted-candidate"]["artifact_types"])
        self.assertIn("registry-value-recovery-candidate", capabilities["registry-deleted-candidate"]["artifact_types"])
        self.assertIn("email-mailbox", capabilities["email-pst-ost-import"]["artifact_types"])
        self.assertEqual(capabilities["evidence-fde-unlock"]["status"], "external-required")
        self.assertIn("fde_operator_runbook", capabilities["evidence-fde-unlock"]["terms"])
        self.assertIn("decrypted root", capabilities["evidence-fde-unlock"]["next_action"].lower())
        for group in payload["groups"]:
            self.assertIn("tab", group)
            self.assertIn("workflow_stage", group)
            for capability in group["capabilities"]:
                self.assertTrue(capability["id"])
                self.assertTrue(capability["tab"])
                self.assertTrue(capability["viewer"])
                self.assertTrue(capability["artifact_types"])
                self.assertTrue(capability["workflow_stage"])
                self.assertTrue(capability["next_action"])
                self.assertTrue(capability["gui_surfaces"])

    def test_core_six_step_evidence_workflow_is_visually_primary(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        index_html = (REPO_ROOT / "rapidtriage" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("CORE_EVIDENCE_WORKFLOW", config_js)
        for expected in [
            "이미지/E01 선택과 지원 여부 확인",
            "파일과 아티팩트를 해시와 함께 확보",
            "OS·문서·메신저 아티팩트 파싱",
            "전체 검색과 현재 파일 검색",
            "원본 뷰어에서 확인하고 표시",
            "선택 증거를 제출 후보로 묶기",
        ]:
            self.assertIn(expected, config_js)
            self.assertIn(expected, index_html)
        self.assertIn("data-testid=\"core-evidence-workflow\"", index_html)
        self.assertIn("data-testid=\"six-step-mission-strip\"", index_html)
        self.assertIn("renderCoreEvidenceWorkflow", app_js)
        self.assertIn("coreEvidenceWorkflowStatuses", app_js)
        self.assertIn("payload.workflow?.stages", app_js)
        self.assertIn("renderRunWorkflowContract", app_js)
        self.assertIn("renderRunWorkflowOutputLinks", app_js)
        self.assertIn("renderRunWorkflowChecklistSummary", app_js)
        self.assertIn("renderRunWorkflowChecklist", app_js)
        self.assertIn("runWorkflowChecklistStatusLabel", app_js)
        self.assertIn("loadRunOutputPreview", app_js)
        self.assertIn("renderRunOutputViewer", app_js)
        self.assertIn("data-testid=\"run-workflow-contract\"", app_js)
        self.assertIn("data-testid=\"run-workflow-output-links\"", app_js)
        self.assertIn("data-testid=\"run-workflow-checklist-summary\"", app_js)
        self.assertIn("data-testid=\"run-workflow-checklist\"", app_js)
        self.assertIn("data-testid=\"run-output-viewer-header\"", app_js)
        self.assertIn("single-case workflow contract", app_js)
        self.assertIn("handoff_outputs", app_js)
        self.assertIn("analyst_checklist", app_js)
        self.assertIn("analyst_checklist_summary", app_js)
        self.assertIn("분석관 체크리스트", app_js)
        self.assertIn("data-preview-output-name", app_js)
        self.assertIn("/preview", app_js)
        self.assertIn("/outputs/${encodeURIComponent(name)}/file", app_js)
        self.assertIn("data-core-workflow-step", app_js)
        self.assertIn("data-testid=\"core-workflow-step-${escapeHtml(step.id)}\"", app_js)
        self.assertIn("입력 확인", app_js)
        self.assertIn("분석 완료", app_js)
        self.assertIn("추출 완료", app_js)
        self.assertIn("검색 가능", app_js)
        self.assertIn("리뷰 준비", app_js)
        self.assertIn("보고서 가능", app_js)
        self.assertIn("docs_extracted_count", app_js)
        self.assertIn("files_extracted_count", app_js)
        self.assertIn(".core-evidence-workflow", styles)
        self.assertIn(".intake-core-workflow", styles)
        self.assertIn(".core-workflow-step", styles)
        self.assertIn(".run-workflow-contract", styles)
        self.assertIn(".run-workflow-stage", styles)
        self.assertIn(".run-workflow-stage-main", styles)
        self.assertIn(".run-workflow-output-links", styles)
        self.assertIn(".run-workflow-output-card", styles)
        self.assertIn(".run-workflow-output-actions", styles)
        self.assertIn(".run-workflow-checklist-summary", styles)
        self.assertIn(".run-workflow-checklist", styles)
        self.assertIn(".run-workflow-checklist-row", styles)
        self.assertIn(".sr-only", styles)
        self.assertIn("body.analysis-active .completed-core-workflow", styles)

    def test_docs_tab_discloses_skipped_extraction_errors(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("payload.extraction_errors", app_js)
        self.assertIn("document(s) skipped during text extraction", app_js)
        self.assertIn("Search continued; review the skipped list", app_js)

    def test_search_tab_discloses_document_extraction_errors(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("payload.documents?.errors", app_js)
        self.assertIn("renderDocumentErrors", app_js)
        self.assertIn("Document extraction skipped/failed", app_js)
        self.assertIn("Search coverage is partial for these documents", app_js)

    def test_case_db_search_discloses_document_extraction_errors(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("const documentErrors = payload.documents?.errors || [];", app_js)
        self.assertIn("metric(\"Document errors\", payload.summary?.document_error_count)", app_js)
        self.assertIn("renderDocumentErrors(documentErrors)", app_js)

    def test_file_triage_controls_are_exposed_in_gui_and_files_tab(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        index_html = (REPO_ROOT / "rapidtriage" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        workbench_config = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("knownGoodHashFeedInput", index_html)
        self.assertIn("hideKnownGoodInput", index_html)
        self.assertIn("knownGoodMaxHashMbInput", index_html)
        self.assertIn("Known-good suppression and extension spoofing checks", index_html)
        self.assertIn("parseKnownGoodHashFeeds", app_js)
        self.assertIn("knownGoodMaxHashBytes", app_js)
        self.assertIn("known_good_hash_feeds: parseKnownGoodHashFeeds()", app_js)
        self.assertIn("renderFileTriageSummary", app_js)
        self.assertIn("file_signature_profile", app_js)
        self.assertIn("known_good_suppression_profile", app_js)
        self.assertIn("unifiedSearchHideKnownGood", app_js)
        self.assertIn("known_good_search_suppression_profile", app_js)
        self.assertIn("data-testid=\"known-good-search-suppression\"", app_js)
        self.assertIn("signature_mismatch_candidates", app_js)
        self.assertIn("known-good-index", workbench_config)
        self.assertIn("nsrl-rds.zip", workbench_config)
        self.assertIn("data-testid=\"file-triage-summary\"", app_js)
        self.assertIn(".file-triage-summary", styles)
        self.assertIn(".file-triage-badge", styles)
        self.assertIn(".file-triage-table tr.risk-row", styles)

    def test_command_palette_connects_lazyweb_actions_to_forensic_workbench(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("quick_actions", config_js)
        self.assertIn("Filter visible rows", config_js)
        self.assertIn("Search current file", config_js)
        self.assertIn("renderCommandPalette", app_js)
        self.assertIn("data-testid=\"command-palette\"", app_js)
        self.assertIn("data-command-palette-open", app_js)
        self.assertIn("bindCommandPaletteActions", app_js)
        self.assertIn("openCommandPalette", app_js)
        self.assertIn("executeCommandPaletteButton", app_js)
        self.assertIn("COMMAND_PALETTE_RESULT_LIMIT", app_js)
        self.assertIn("data-command-tab", app_js)
        self.assertIn("data-command-filter", app_js)
        self.assertIn("data-command-action", app_js)
        self.assertIn("Open command palette", config_js)
        self.assertIn(".command-palette", styles)
        self.assertIn(".command-palette-command", styles)
        self.assertIn("body.analysis-active .command-palette-shell", styles)

    def test_row_filter_text_is_bounded_for_large_records(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        row_text_body = app_js.split("function rowText(value) {", 1)[1].split("function compactRowFilterText", 1)[0]
        self.assertIn("ROW_FILTER_TEXT_LIMIT", app_js)
        self.assertIn("ROW_FILTER_KEYS", app_js)
        self.assertIn("compactRowFilterText(value)", row_text_body)
        self.assertNotIn("JSON.stringify", row_text_body)
        self.assertIn("slice(0, ROW_FILTER_TEXT_LIMIT)", app_js)
        self.assertIn("filter text bounded to ${ROW_FILTER_TEXT_LIMIT} chars/row", app_js)


if __name__ == "__main__":
    unittest.main()
