from __future__ import annotations

import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


class RapidTriageWebStaticTests(unittest.TestCase):
    def test_web_artifact_workbench_exposes_ntfs_replay_review_cards(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        self.assertIn("ntfsArtifactPreviewText", app_js)
        self.assertIn("renderNtfsReplayPreviewArtifactCard", app_js)
        self.assertIn("usn_replay_inventory_profile", app_js)
        self.assertIn("bounded_mft_replay_preview", app_js)
        self.assertIn("mft_bounded_path_cache_profile", app_js)
        self.assertIn("MFT cache quality", app_js)
        self.assertIn("MFT partial path warnings", app_js)
        self.assertIn("usn_path_reliability_profile", app_js)
        self.assertIn("Path reliability", app_js)
        self.assertIn("Reliability wording", app_js)
        self.assertIn("rename_pair_preview", app_js)
        self.assertIn("delete_lifecycle_preview", app_js)
        self.assertIn("bounded_state_replay_preview", app_js)
        self.assertIn("usn_state_replay_validation_profile", app_js)
        self.assertIn("State replay validation", app_js)
        self.assertIn("State validation wording", app_js)
        self.assertIn("Delete lifecycle", app_js)
        self.assertIn("State transitions", app_js)
        self.assertIn("Bounded state replay", app_js)
        self.assertIn("STATE paired OLD", app_js)
        self.assertIn("USN replay preview", app_js)
        self.assertIn("renderNtfsSourceLocatorLinks", app_js)
        self.assertIn("Source locators", app_js)
        self.assertIn("source-hex-range", app_js)
        self.assertIn("include_hashes=true", app_js)
        self.assertIn("errorMessageFromDetail", app_js)
        self.assertIn("renderSourceResolutionDiagnostics", app_js)
        self.assertIn("source_path_resolution", app_js)
        self.assertIn("Source path resolution diagnostics", app_js)
        self.assertIn("Court-grade rename/delete replay still requires full-journal ordering", app_js)

    def test_web_workbench_exposes_run_validation_diff_inventory_panel(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("data-testid=\"run-validation-diff-panel\"", app_js)
        self.assertIn("loadRunValidationPackageSummary", app_js)
        self.assertIn("renderRunValidationPackageSummary", app_js)
        self.assertIn("diff_inventory", app_js)
        self.assertIn("usn_state_replay_diff_attached", app_js)
        self.assertIn("usn_state_replay_diff_pass_count", app_js)
        self.assertIn("usn_state_replay_status", app_js)
        self.assertIn("Run validation diff inventory", app_js)
        self.assertIn("run-validation-diff-panel", styles)
        self.assertIn("validation-diff-card", styles)
        self.assertIn("validation-diff-list", styles)
        self.assertIn("compact-dl", styles)

    def test_search_results_expose_review_facets_for_fast_triage(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("renderSearchFacets", app_js)
        self.assertIn("review facets", app_js)
        self.assertIn("search-facet-chip[data-filter]", app_js)
        self.assertIn("aria-label=\"Filter results by", app_js)
        self.assertIn("search-facet-panel", styles)
        self.assertIn("search-facet-chip", styles)

    def test_workbench_review_queue_and_schema_visibility_contracts(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        state_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_state.js").read_text(encoding="utf-8")
        index_html = (REPO_ROOT / "rapidtriage" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('/assets/app_workbench_config.js', index_html)
        self.assertIn('/assets/app_state.js', index_html)
        self.assertLess(index_html.index('/assets/app_workbench_config.js'), index_html.index('/assets/app.js'))
        self.assertLess(index_html.index('/assets/app_workbench_config.js'), index_html.index('/assets/app_state.js'))
        self.assertLess(index_html.index('/assets/app_state.js'), index_html.index('/assets/app.js'))
        self.assertIn("function persistWorkbenchSession", state_js)
        self.assertIn("function renderVirtualizationNotice", state_js)
        self.assertIn("function getSearchDraft", state_js)
        self.assertIn("data-testid=\"artifact-tree-lane-find\"", app_js)
        self.assertIn("data-testid=\"artifact-tree-lane-deliver\"", app_js)
        self.assertIn("tab: \"summary\", label: \"Overview\"", config_js)
        self.assertIn("tab: \"indicators\", label: \"Indicators\"", config_js)
        self.assertIn("data-testid=\"forensic-view-mode-bar\"", app_js)
        self.assertIn("aria-current=\"${mode.tab === tab ? \"page\" : \"false\"}\"", app_js)
        self.assertIn("aria-live=\"polite\"", app_js)
        self.assertIn("viewer.setAttribute(\"aria-busy\", \"true\")", app_js)
        self.assertIn("viewer.setAttribute(\"aria-busy\", \"false\")", app_js)
        self.assertIn("data-artifact-filter", app_js)
        self.assertIn("applyArtifactTreeFilter", app_js)
        self.assertIn("data-testid=\"review-bulk-queue\"", app_js)
        self.assertIn("review-bulk-toolbar", app_js)
        self.assertIn("Find related", app_js)
        self.assertIn("Prepare report", app_js)
        self.assertIn("renderSqliteSchemaPanel", app_js)
        self.assertIn("data-testid=\"sqlite-schema-panel\"", app_js)
        self.assertIn("Schema visibility", app_js)
        self.assertIn("artifact-tree-lane", styles)
        self.assertIn("review-bulk-toolbar", styles)
        self.assertIn("sqlite-schema-panel", styles)
        self.assertIn("sqlite-column-chip", styles)

    def test_lazyweb_command_center_is_connected_to_workbench_tabs(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("LAZYWEB_WORKBENCH_MODEL", config_js)
        self.assertIn("lazyweb-command-center-model-v1", config_js)
        self.assertIn("https://www.lazyweb.com/canvas/flows/raycast/manage-models", config_js)
        self.assertIn("Evidence intake", config_js)
        self.assertIn("Unified search", config_js)
        self.assertIn("Source verify", config_js)
        self.assertIn("Review board", config_js)
        self.assertIn("Report bundle", config_js)
        self.assertIn("renderLazywebCommandCenter", app_js)
        self.assertIn("data-testid=\"lazyweb-command-center\"", app_js)
        self.assertIn("data-open-tab=\"search\"", app_js)
        self.assertIn("data-artifact-filter=\"${escapeHtml(command.filter || \"\")}\"", app_js)
        self.assertIn(".lazyweb-command-center", styles)
        self.assertIn(".lazyweb-command-grid", styles)
        self.assertIn("body.analysis-active .lazyweb-command-center", styles)

    def test_forensic_feature_catalog_makes_available_functions_discoverable(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("FORENSIC_FEATURE_CATALOG", config_js)
        self.assertIn("증거 입력 / 케이스", config_js)
        self.assertIn("Windows 핵심 아티팩트", config_js)
        self.assertIn("웹 / AI 사용 기록", config_js)
        self.assertIn("메신저 / 이메일", config_js)
        self.assertIn("문서 / DB / 본문 검색", config_js)
        self.assertIn("이미지 / 영상 / OCR", config_js)
        self.assertIn("타임라인 / IOC / DFIR", config_js)
        self.assertIn("모바일 / 클라우드", config_js)
        self.assertIn("리뷰 / 보고서 / 제출", config_js)
        self.assertIn("renderForensicFeatureCatalog", app_js)
        self.assertIn("data-testid=\"forensic-feature-catalog\"", app_js)
        self.assertIn("지원 기능을 먼저 보고 시작하세요", app_js)
        self.assertIn("feature-catalog-card", app_js)
        self.assertIn("data-open-tab=\"${escapeHtml(item.tab)}\"", app_js)
        self.assertIn("data-artifact-filter=\"${escapeHtml(filterTerm)}\"", app_js)
        self.assertIn(".forensic-feature-catalog", styles)
        self.assertIn(".feature-catalog-grid", styles)
        self.assertIn("body.analysis-active .forensic-feature-catalog", styles)

    def test_core_three_step_evidence_workflow_is_visually_primary(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        index_html = (REPO_ROOT / "rapidtriage" / "web" / "static" / "index.html").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("CORE_EVIDENCE_WORKFLOW", config_js)
        self.assertIn("이미지/E01 안을 읽고 분류", config_js)
        self.assertIn("필요한 파일을 해시와 함께 꺼내기", config_js)
        self.assertIn("키워드로 찾고 원본에서 재확인", config_js)
        self.assertIn("data-testid=\"core-evidence-workflow\"", index_html)
        self.assertIn("renderCoreEvidenceWorkflow", app_js)
        self.assertIn("coreEvidenceWorkflowStatuses", app_js)
        self.assertIn("data-core-workflow-step", app_js)
        self.assertIn("data-testid=\"core-workflow-step-${escapeHtml(step.id)}\"", app_js)
        self.assertIn("분석 완료", app_js)
        self.assertIn("추출 완료", app_js)
        self.assertIn("검색 가능", app_js)
        self.assertIn("docs_extracted_count", app_js)
        self.assertIn("files_extracted_count", app_js)
        self.assertIn(".core-evidence-workflow", styles)
        self.assertIn(".core-workflow-step", styles)
        self.assertIn(".sr-only", styles)
        self.assertIn("body.analysis-active .completed-core-workflow", styles)

    def test_command_palette_connects_lazyweb_actions_to_forensic_workbench(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")
        config_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app_workbench_config.js").read_text(encoding="utf-8")
        styles = (REPO_ROOT / "rapidtriage" / "web" / "static" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("quick_actions", config_js)
        self.assertIn("Filter visible rows", config_js)
        self.assertIn("Search current file", config_js)
        self.assertIn("renderCommandPalette", app_js)
        self.assertIn("data-testid=\"command-palette\"", app_js)
        self.assertIn("data-command-palette-open", app_js)
        self.assertIn("bindCommandPaletteActions", app_js)
        self.assertIn("openCommandPalette", app_js)
        self.assertIn("executeCommandPaletteButton", app_js)
        self.assertIn("COMMAND_PALETTE_RESULT_LIMIT", app_js)
        self.assertIn("data-command-tab", app_js)
        self.assertIn("data-command-filter", app_js)
        self.assertIn("data-command-action", app_js)
        self.assertIn("Open command palette", config_js)
        self.assertIn(".command-palette", styles)
        self.assertIn(".command-palette-command", styles)
        self.assertIn("body.analysis-active .command-palette-shell", styles)

    def test_row_filter_text_is_bounded_for_large_records(self) -> None:
        app_js = (REPO_ROOT / "rapidtriage" / "web" / "static" / "app.js").read_text(encoding="utf-8")

        row_text_body = app_js.split("function rowText(value) {", 1)[1].split("function compactRowFilterText", 1)[0]
        self.assertIn("ROW_FILTER_TEXT_LIMIT", app_js)
        self.assertIn("ROW_FILTER_KEYS", app_js)
        self.assertIn("compactRowFilterText(value)", row_text_body)
        self.assertNotIn("JSON.stringify", row_text_body)
        self.assertIn("slice(0, ROW_FILTER_TEXT_LIMIT)", app_js)
        self.assertIn("filter text bounded to ${ROW_FILTER_TEXT_LIMIT} chars/row", app_js)


if __name__ == "__main__":
    unittest.main()
