// Generates TypeScript types from rapidtriage/schemas/*.json into src/schemas/.
// Run: npm run gen:schemas

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, "..", "..", "rapidtriage", "schemas");
const outDir = join(here, "..", "src", "schemas");

await mkdir(outDir, { recursive: true });

const files = (await readdir(schemaDir)).filter((name) => name.endsWith(".schema.json")).sort();
const generated = [];

for (const file of files) {
  const schemaPath = join(schemaDir, file);
  const base = file.replace(/\.schema\.json$/, "");
  const outName = `${base}.ts`;
  try {
    const schema = JSON.parse(await readFile(schemaPath, "utf-8"));
    const ts = await compile(schema, base.replace(/-/g, "_"), {
      bannerComment: "/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */",
      format: false,
      strictIndexSignatures: true,
    });
    await writeFile(join(outDir, outName), ts, "utf-8");
    generated.push(outName);
    console.log(`generated src/schemas/${outName}`);
  } catch (error) {
    console.error(`skipped ${file}: ${error.message}`);
  }
}

await writeFile(
  join(outDir, "index.ts"),
  `// Generated barrel — do not edit by hand.\n${generated
    .map((name) => `export * from "./${name.replace(/\.ts$/, "")}";`)
    .join("\n")}\n`,
  "utf-8",
);
console.log(`schemas: ${generated.length}/${files.length} generated`);
