/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface ArtifactRecordV1 {
schema: "ArtifactRecordV1"
artifact_id: string
artifact_family: string
artifact_type: string
parser: string
parser_version: string
source: {
case_id: string
source_id: string
source_path: string
offset: (number | null)
length: (number | null)
hashes: {
[k: string]: string | undefined
}
}
confidence: number
validation_required: boolean
commercial_grade_ready: boolean
commercial_grade_blockers: string[]
legal_limitations: string[]
fields: {
[k: string]: unknown | undefined
}
}
