/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Artifacts {
command: "artifacts"
kind: string
generated_at: string
root: string
provider: {
name: string
description: string
target_platform: string
supported: boolean
}
summary: {
artifact_count: number
artifact_type_counts: {
[k: string]: number | undefined
}
parser_error_count?: number
collection_status?: string
matched_rule_count?: number
ioc_hit_count?: number
artifact_record_contract_valid_count?: number
artifact_record_contract_invalid_count?: number
}
artifacts: {
provider: string
artifact_type: string
path: string
supported: boolean
details: {
[k: string]: unknown | undefined
}
artifact_record?: {
[k: string]: unknown | undefined
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}[]
artifact_record_contract?: {
profile_version: "artifact-output-contract-v1"
schema: "ArtifactRecordV1"
adapter_version: string
record_count: number
valid_count: number
invalid_count: number
gui_usable: boolean
errors: {
[k: string]: unknown | undefined
}[]
}
parser_errors?: {
kind: string
collector: string
error_type: string
message: string
}[]
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}
