/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Artifacts {
command: "artifacts"
kind: string
generated_at: string
root: string
provider: {
name: string
description: string
target_platform: string
supported: boolean
}
summary: {
artifact_count: number
artifact_type_counts: {
[k: string]: number | undefined
}
parser_error_count?: number
collection_status?: string
matched_rule_count?: number
ioc_hit_count?: number
artifact_record_contract_valid_count?: number
artifact_record_contract_invalid_count?: number
}
artifacts: {
provider: string
artifact_type: string
path: string
supported: boolean
details: {
[k: string]: unknown | undefined
}
/**
 * ArtifactRecordV1 envelope; run outputs omit fields (fields_source: details) and hoist constant envelope parts into artifact_type_profiles
 */
artifact_record?: {
[k: string]: unknown | undefined
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
/**
 * artifact_type whose artifact_type_profiles entry holds this row's hoisted constant blocks; merge it back with expand_profile
 */
profile_ref?: string
incremental_reuse?: {
[k: string]: unknown | undefined
}
/**
 * true when artifact_type_profiles[profile_ref].contexts[path] holds this row's per-source-file constants
 */
context_ref?: boolean
}[]
artifact_record_contract?: {
profile_version: "artifact-output-contract-v1"
schema: "ArtifactRecordV1"
adapter_version: string
record_count: number
valid_count: number
invalid_count: number
gui_usable: boolean
errors: {
[k: string]: unknown | undefined
}[]
}
parser_errors?: {
kind: string
collector: string
error_type: string
message: string
}[]
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
/**
 * Per artifact_type templates of constant (parts of) details blocks and the ArtifactRecordV1 envelope; rows with profile_ref deep-merge their residue over them
 */
artifact_type_profiles?: {
[k: string]: {
details?: {
[k: string]: unknown | undefined
}
artifact_record?: {
[k: string]: unknown | undefined
}
/**
 * per source file (row path) templates: details/artifact_record
 */
contexts?: {
[k: string]: {
[k: string]: unknown | undefined
} | undefined
}
/**
 * dictionary-encoded details labels: key -> value list; rows hold the index
 */
codes?: {
[k: string]: string[] | undefined
}
} | undefined
}
collector_options?: {
[k: string]: unknown | undefined
}
/**
 * true when artifacts holds only the first rows; the full row stream is records_path
 */
artifacts_preview?: boolean
/**
 * rows in records_path
 */
record_count?: number
/**
 * absolute path of the JSONL row stream (one artifacts row per line)
 */
records_path?: string
/**
 * records_path file name, resolved next to this JSON when the run directory moved
 */
records_file?: string
records_format?: "jsonl"
incremental_delta?: {
[k: string]: unknown | undefined
}
}
