/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Case {
command: "case"
generated_at: string
updated_at: string
case_id: string
title: string
summary: {
bookmark_count: number
tagged_bookmark_count: number
report_item_count: number
review_revision_count: number
tag_counts: {
[k: string]: number | undefined
}
review_status_counts: {
[k: string]: number | undefined
}
source_command_counts: {
[k: string]: number | undefined
}
}
bookmarks: {
bookmark_id: string
created_at: string
updated_at: string
summary: string
tags: string[]
note: string
review: {
status: ("unreviewed" | "relevant" | "needs-review" | "not-relevant" | "excluded")
include_in_report: boolean
reviewed_at: (string | null)
}
review_history?: {
action: ("created" | "updated")
at: string
status: ("unreviewed" | "relevant" | "needs-review" | "not-relevant" | "excluded")
include_in_report: boolean
tags: string[]
note: string
changed_fields: string[]
}[]
reference: {
command: string
file: string
pointer: string
root: (string | null)
stable_key: string
}
snapshot: {
path: (string | null)
hash: (string | null)
timestamp: (string | null)
artifact_key: (string | null)
summary: string
}
}[]
}
