/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Compare {
command: "compare"
generated_at: string
options: {
[k: string]: unknown | undefined
}
inputs: {
left?: Input
right?: Input
baseline?: Input
items?: Input[]
}
summary: {
result_count: number
status_counts: {
[k: string]: number | undefined
}
different_field_count?: number
text_diff_included?: boolean
input_count?: number
text_diff_count?: number
[k: string]: unknown | undefined
}
compare_native_capabilities?: {
[k: string]: boolean | undefined
}
compare_review_profile?: {
[k: string]: unknown | undefined
}
compare_citation_manifest?: {
[k: string]: unknown | undefined
}
compare_report_grade_validation_plan?: {
[k: string]: unknown | undefined
}
compare_report_grade_assessment?: {
[k: string]: unknown | undefined
}
core_accuracy_gates?: {
[k: string]: unknown | undefined
}[]
commercial_uplift_evidence?: {
[k: string]: unknown | undefined
}
results: {
comparison_id: string
status: ("same" | "different" | "only-in-left" | "only-in-right" | "both-missing")
timestamp: string
path: string
left_path: string
right_path: string
summary: string
fields: {
[k: string]: unknown | undefined
}[]
diff: {
[k: string]: unknown | undefined
}
left: Input
right: Input
[k: string]: unknown | undefined
}[]
}
export interface Input {
label: string
path: string
name: string
extension: string
exists: boolean
is_file: boolean
is_dir: boolean
size: (number | null)
modified_at: (string | null)
hashes: {
[k: string]: string | undefined
}
[k: string]: unknown | undefined
}
