/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Docs {
command: "docs"
root: string
scan_scope_root?: string
generated_at: string
summary: {
candidate_count: number
match_count: number
supported_extensions: string[]
matched_rule_count?: number
ioc_hit_count?: number
extraction_error_count?: number
skipped_document_count?: number
}
index?: {
command: "docs-index"
path: string
strategy: string
version: number
document_count: number
term_count: number
}
manifest: {
generated_at: string
root: string
platform: string
keywords: string[]
providers: {
name: string
description: string
target_platform: string
supported: boolean
/**
 * Number of artifact rows the provider produced; the rows themselves are in rapidtriage-manifest.json and artifacts/*.json.
 */
artifact_count?: number
/**
 * Legacy docs.json outputs embedded every artifact row here; current outputs omit it.
 */
artifacts?: {
provider: string
artifact_type: string
path: string
supported: boolean
details: {
[k: string]: unknown | undefined
}
}[]
}[]
}
candidates: {
path: string
kind: string
size: number
modified_at: string
}[]
results: {
path: string
kind: string
matched_keywords: string[]
preview: string
size: number
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}[]
extraction_errors?: {
path: string
kind: string
size: number
reason: string
error_type: string
message: string
recoverable: boolean
effect: string
}[]
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}
