/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Extract {
command: "extract"
source_command: ("docs" | "files")
input_json: string
root: (string | null)
generated_at: string
output_dir: string
filters: {
name_contains: string[]
path_contains: string[]
extensions: string[]
categories: string[]
kinds: string[]
limit: number
}
safety: {
dry_run: boolean
read_only: boolean
max_extract_size_bytes: number
max_file_count: number
overwrite: boolean
}
summary: {
input_count: number
selected_count: number
extracted_count: number
skipped_count: number
}
entries: {
original_path: string
extracted_path: string
relative_path: string
sha256: string
modified_at: string
size: number
categories?: string[]
kind?: string
matched_keywords?: string[]
recovery?: {
[k: string]: unknown | undefined
}
}[]
skipped: {
original_path: string
reason: string
}[]
}
