/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Files {
command: "files"
root: string
scan_scope_root?: string
generated_at: string
filters: {
categories: string[]
name_contains: string[]
path_contains: string[]
extensions: string[]
modified_after: (string | null)
modified_before: (string | null)
limit: number
known_good_hash_feeds?: string[]
hide_known_good?: boolean
known_good_max_hash_bytes?: number
}
summary: {
scanned_file_count: number
candidate_count: number
raw_candidate_count?: number
category_counts: {
[k: string]: number | undefined
}
newest_modified_at: (string | null)
oldest_modified_at: (string | null)
duplicate_group_count?: number
duplicate_file_count?: number
fuzzy_text_duplicate_group_count?: number
fuzzy_text_duplicate_file_count?: number
known_good_feed_count?: number
known_good_hash_count?: number
known_good_match_count?: number
known_good_suppressed_count?: number
known_good_hash_skipped_large_count?: number
known_good_nsrl_rds_feed_count?: number
known_good_nsrl_rds_row_count?: number
candidate_kind_counts?: {
[k: string]: number | undefined
}
signature_checked_count?: number
signature_mismatch_count?: number
signature_unrecognized_known_extension_count?: number
commercial_gap_ids?: string[]
matched_rule_count?: number
ioc_hit_count?: number
}
candidates: {
path: string
name: string
extension: string
size: number
modified_at: string
modified_epoch: number
categories: string[]
reasons: {
[k: string]: string[] | undefined
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
known_good_status?: string
known_good_error?: string
known_good_match?: {
[k: string]: unknown | undefined
}
report_suppression_status?: string
analyst_review_required?: boolean
file_signature?: {
[k: string]: unknown | undefined
}
recovery?: {
schema: string
candidate_kind: ("existing" | "deleted-entry" | "orphan-record" | "carved" | "partial-corrupt")
subtype?: (string | null)
confidence: ("high" | "medium" | "low" | "unknown")
validation_status: ("unverified" | "validated" | "partial" | "rejected")
deletion_state?: (string | null)
source_id?: (string | null)
source_path?: (string | null)
source_record_id?: (string | null)
source_offset?: (number | null)
boundary_method?: (string | null)
signature_type?: (string | null)
limitations: string[]
reportability: string
commercial_claim_allowed: boolean
[k: string]: unknown | undefined
}
}[]
known_good_suppression_profile?: {
[k: string]: unknown | undefined
}
known_good_suppressed_candidates?: {
[k: string]: unknown | undefined
}[]
file_signature_profile?: {
[k: string]: unknown | undefined
}
signature_mismatch_candidates?: {
[k: string]: unknown | undefined
}[]
duplicate_content_groups?: {
sha256: string
file_count: number
size: number
paths: string[]
truncated_paths: boolean
commercial_gap_ids?: string[]
group_id?: string
group_fingerprint?: string
representative_path?: string
representative_name?: string
report_suppression_status?: string
analyst_review_required?: boolean
suppression_policy?: {
[k: string]: unknown | undefined
}
duplicate_resolution_status?: string
}[]
fuzzy_text_duplicate_groups?: {
group_id: string
group_fingerprint: string
file_count: number
representative_path?: string
representative_name?: string
paths: string[]
truncated_paths: boolean
min_similarity?: number
match_type: string
normalized_sha256_values?: string[]
commercial_gap_ids?: string[]
duplicate_resolution_status?: string
report_suppression_status: string
analyst_review_required?: boolean
suppression_policy?: {
[k: string]: unknown | undefined
}
[k: string]: unknown | undefined
}[]
duplicate_content_manifest?: {
[k: string]: unknown | undefined
}
hash_cache_assessment?: {
[k: string]: unknown | undefined
}
hash_cache_manifest?: {
[k: string]: unknown | undefined
}
duplicate_detection_assessment?: {
[k: string]: unknown | undefined
}
core_accuracy_gates?: {
[k: string]: unknown | undefined
}[]
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}
