/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Indicators {
command: "indicators"
generated_at: string
run_summary: string
options: {
max_indicators: number
max_sources_per_indicator: number
rule_set: string
ti_feeds: string[]
}
summary: {
indicator_count: number
type_counts: {
[k: string]: number | undefined
}
source_output_counts: {
[k: string]: number | undefined
}
matched_rule_counts: {
[k: string]: number | undefined
}
matched_indicator_count: number
ioc_scanner_hit_count?: number
ioc_scanner_row_count?: number
ioc_scanner_rule_count?: number
enriched_indicator_count: number
ti_feed_count: number
commercial_gap_ids?: string[]
commercial_grade_ready?: boolean
}
ti_feed_sources?: {
path: string
format: string
name: string
version: string
sha256?: string
size_bytes?: number
indicator_count: number
local_only: boolean
commercial_gap_ids?: string[]
validation_status?: string
ti_feed_manifest?: {
[k: string]: unknown | undefined
}
ti_feed_manifest_hash?: string
}[]
indicator_native_capabilities?: {
[k: string]: boolean | undefined
}
ioc_scanner_hits?: {
rule_id: string
type: string
value: string
count: number
classification: string
risk_flags: string[]
sources: {
[k: string]: string | undefined
}[]
commercial_gap_ids?: string[]
ready_for_court_report?: boolean
report_use_boundary?: string
ioc_scanner_row_hash?: string
source_viewer_locator?: {
[k: string]: unknown | undefined
}
}[]
ioc_scanner_manifest?: {
[k: string]: unknown | undefined
}
ioc_scanner_manifest_hash?: string
ioc_ti_enrichment_manifest?: {
[k: string]: unknown | undefined
}
ioc_ti_enrichment_manifest_hash?: string
ioc_ti_report_grade_validation_plan?: {
[k: string]: unknown | undefined
}
ioc_ti_report_grade_validation_plan_hash?: string
report_grade_ready_slot_count?: number
report_grade_blocking_slot_count?: number
ti_enrichment_assessment?: {
[k: string]: unknown | undefined
}
reportability_decision?: {
[k: string]: unknown | undefined
}
core_accuracy_gates?: {
[k: string]: unknown | undefined
}[]
commercial_uplift_evidence?: {
[k: string]: unknown | undefined
}
indicators: {
type: ("url" | "domain" | "ip" | "md5" | "sha1" | "sha256")
value: string
count: number
classification: string
risk_flags: string[]
sources: {
[k: string]: string | undefined
}[]
commercial_gap_ids?: string[]
ready_for_court_report?: boolean
matched_rules?: string[]
ioc_ti_indicator_manifest?: {
[k: string]: unknown | undefined
}
ioc_ti_indicator_manifest_hash?: string
indicator_row_hash?: string
ti_enrichment?: {
type?: string
value?: string
severity?: string
classification?: string
source?: string
feed_name?: string
feed_version?: string
feed_path?: string
feed_row_hash?: string
matched_on?: string
note?: string
commercial_gap_ids?: string[]
validation_status?: string
}
}[]
}
