/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Manifest {
generated_at: string
root: string
platform: string
keywords: string[]
providers: {
name: string
description: string
target_platform: string
supported: boolean
artifacts: {
provider: string
artifact_type: string
path: string
supported: boolean
details: {
[k: string]: unknown | undefined
}
}[]
}[]
}
