/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface RunSummary {
command: "run"
mode: ("seizure" | "fraud" | "hacking" | "recovery")
generated_at: string
root: string
source?: {
type: string
source_path: string
analysis_root: string
stage_dir?: string
partition_start_sector?: number
recovery_mode?: string
image_paths?: string[]
tool?: string
converted_raw_path?: string
conversion_tool?: string
}
scan_scope_root: string
output_dir: string
audit?: string
carving?: {
enabled: boolean
output: string
summary: {
[k: string]: unknown | undefined
}
limitation: string
}
profile: {
description: string
keywords: string[]
docs_extract_kinds: string[]
file_extract_categories: string[]
file_scan_categories: string[]
file_scan_path_contains: string[]
preferred_locations: string[]
artifacts_kinds: string[]
}
safety: {
dry_run: boolean
read_only: boolean
max_extract_size_bytes: number
max_file_count: number
memory_cap_bytes: number
memory_cap_source: string
overwrite: boolean
resume: boolean
resume_effective?: boolean
resume_disabled_reason?: string
known_good_hash_feeds?: string[]
hide_known_good?: boolean
known_good_max_hash_bytes?: number
reused_outputs: string[]
delta_applied_outputs?: string[]
evidence_delta?: {
[k: string]: unknown | undefined
}
input_fingerprint?: {
[k: string]: unknown | undefined
}
memory_cap_stage_checks?: ({
[k: string]: unknown | undefined
} | {
[k: string]: unknown | undefined
}[])
parser_crash_isolation_ledger?: {
[k: string]: unknown | undefined
}
preview_sandbox_policy?: {
[k: string]: unknown | undefined
}
sqlite_fts_optimization?: {
[k: string]: unknown | undefined
}
artifact_scheduler?: {
strategy: string
max_workers: number
scheduled_count: number
commercial_gap_ids: string[]
manifest?: {
[k: string]: unknown | undefined
}
assessment: {
[k: string]: unknown | undefined
}
}
}
resource_caps?: {
[k: string]: unknown | undefined
}
outputs: {
[k: string]: string | undefined
}
steps: {
name: string
status: string
output: string
[k: string]: unknown | undefined
}[]
workflow: {
profile_version: "run-workflow-contract-v1"
stage_order: ("ingest" | "extract" | "parse" | "index" | "review" | "report")[]
stage_count: number
completed_stage_count: number
warning_stage_count: number
blocked_stage_count: number
pending_stage_count: number
gui_primary_flow: boolean
source_type: string
source_path: string
analysis_root: string
read_only: boolean
resume: boolean
stage_hash: string
stage_lookup: {
[k: string]: "completed" | "warning" | "blocked" | "pending" | undefined
}
analyst_checklist_summary: {
profile_version: "run-workflow-analyst-checklist-summary-v1"
item_count: number
ready_count: number
warning_count: number
blocked_count: number
pending_count: number
severity_counts: {
[k: string]: number | undefined
}
next_actions: {
stage: string
status: ("ready" | "warning" | "blocked" | "pending")
severity: string
action: string
}[]
}
stages: {
id: ("ingest" | "extract" | "parse" | "index" | "review" | "report")
label: string
title: string
status: ("completed" | "warning" | "blocked" | "pending")
ready: boolean
step_names: string[]
output_keys: string[]
handoff_outputs: {
name: string
role: string
recommended_viewer: string
gui_action: string
reportability_note: string
}[]
analyst_checklist: {
id: string
label: string
status: ("ready" | "warning" | "blocked" | "pending")
severity: string
expected_outputs: string[]
matched_outputs: string[]
action: string
}[]
reused: boolean
warning_count: number
warning_messages: string[]
gui: {
primary_tab: string
next_action: string
large_case_note: string
}
}[]
}
processing: {
profile_label: string
dry_run: boolean
read_only: boolean
overwrite: boolean
resume: boolean
reused_output_count: number
reused_outputs: string[]
incremental_indexing: {
[k: string]: unknown | undefined
}
checkpoint_resume: {
[k: string]: unknown | undefined
}
parser_crash_isolation: {
[k: string]: unknown | undefined
}
memory_cap_enforcement: {
[k: string]: unknown | undefined
}
parallel_parser_scheduler: {
[k: string]: unknown | undefined
}
preview_sandboxing?: {
[k: string]: unknown | undefined
}
sqlite_fts_optimization?: {
[k: string]: unknown | undefined
}
functional_large_data_profiles: {
[k: string]: unknown | undefined
}
runtime_defensibility_profiles: {
[k: string]: unknown | undefined
}
streaming_parser_boundary?: {
[k: string]: unknown | undefined
}
caps: {
max_extract_size_bytes: number
max_file_count: number
[k: string]: unknown | undefined
}
step_count: number
warning_count: number
highest_warning_level: string
warnings: {
step: string
level: string
message: string
}[]
}
summary: {
document_candidate_count: number
document_match_count: number
scanned_file_count: number
file_candidate_count: number
provider_artifact_counts: {
[k: string]: number | undefined
}
windows_provider_artifact_counts: {
[k: string]: number | undefined
}
artifact_type_counts: {
[k: string]: number | undefined
}
matched_keyword_counts: {
[k: string]: number | undefined
}
file_category_counts: {
[k: string]: number | undefined
}
artifacts: {
[k: string]: {
artifact_count: number
artifact_type_counts: {
[k: string]: number | undefined
}
output: string
} | undefined
}
docs_extracted_count: number
files_extracted_count: number
preferred_location_candidate_count: number
timeline_event_count: number
silent_failure_risk: boolean
silent_failure_risk_check_count: number
matched_rule_count?: number
ioc_hit_count?: number
counts: {
validation_issues: number
validation_issue_breakdown: {
step_warnings: number
parser_errors: number
}
outputs: number
artifacts: number
docs: number
files: number
timeline_events: number
review_items: number
indicators: number
}
}
silent_failure_detection: {
status: string
silent_failure_risk: boolean
check_count: number
risk_check_count: number
target_inventory: {
[k: string]: unknown | undefined
}
checks: {
[k: string]: unknown | undefined
}[]
[k: string]: unknown | undefined
}
highlights: {
document_hits: {
path: string
kind: string
matched_keywords: string[]
preview: string
}[]
recent_file_candidates: {
path: string
categories: string[]
extension: (string | null)
size: (number | null)
modified_at: (string | null)
}[]
large_file_candidates: {
path: string
categories: string[]
size: (number | null)
modified_at: (string | null)
}[]
preferred_location_candidates: {
path: string
categories: string[]
size: (number | null)
modified_at: (string | null)
}[]
}
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}
