/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface SubmissionManifest {
command: "submission-manifest"
generated_at: string
case_id: string
title: string
hash_algorithms: ("md5" | "sha1" | "sha256")[]
hash_verification: {
scope: string
metadata_cache_bypassed: boolean
hash_source: string
note: string
}
options: {
include_all: boolean
max_items: number
}
summary: {
case_bookmark_count: number
hashed_item_count: number
skipped_count: number
total_size: number
}
items: {
bookmark_id: string
summary: string
tags: string[]
note: string
review: {
[k: string]: unknown | undefined
}
reference: {
[k: string]: unknown | undefined
}
evidence: {
path: string
name: string
size: number
modified_at: string
hash_source: string
hashes: {
md5: string
sha1: string
sha256: string
}
}
}[]
skipped: {
bookmark_id: string
summary: string
path: string
reason: string
}[]
}
