/* Generated by frontend/scripts/gen-schemas.mjs — do not edit by hand. */

export interface Timeline {
command: "timeline"
generated_at: string
root: string
inputs: {
files: string[]
docs: string[]
artifacts: string[]
}
summary: {
input_file_count: number
event_count: number
source_counts: {
[k: string]: number | undefined
}
event_type_counts: {
[k: string]: number | undefined
}
earliest_event_at: (string | null)
latest_event_at: (string | null)
matched_rule_count?: number
ioc_hit_count?: number
}
events: {
timestamp: string
source: ("files" | "docs" | "artifacts")
event_type: string
path: string
input_file: string
summary: string
details: {
[k: string]: unknown | undefined
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}[]
rule_set?: {
path: string
format: string
rule_count: number
}
matched_rules?: string[]
ioc_hits?: {
rule_id: string
type: string
value: string
count?: number
}[]
}
