from __future__ import annotations

import datetime as dt
from typing import Mapping


CORE_FORENSIC_ACCURACY_VERSION = "core-forensics-accuracy-v1"


CORE_FORENSIC_ACCURACY_ITEMS: tuple[dict[str, object], ...] = (
    {
        "number": 1,
        "title": "Native EVTX BinXML full parsing",
        "surface": "native EVTX records, BinXML values, promoted Event/System/EventData/UserData fields",
        "corpus": "EVTX files with Security, System, PowerShell, Sysmon, malformed chunks, duplicate EventData names, and provider-specific TemplateInstance records",
        "oracle": "EvtxECmd/Hayabusa/Windows Event Viewer XML export record-level diff",
        "required_checks": (
            "record-id and file-offset stability",
            "timestamp/EventID/provider/channel/computer equality",
            "duplicate EventData order preservation",
            "BinXML scalar type decoding diff",
            "trusted-tool record-level diff pass",
            "unsupported grammar warning coverage",
        ),
    },
    {
        "number": 2,
        "title": "EVTX event template/message rendering",
        "surface": "rendered message, provider/template metadata, unresolved-template warnings",
        "corpus": "provider manifests/resource-DLL exports plus high-value Windows/Sysmon/Defender events",
        "oracle": "Windows Event Viewer rendered message and trusted EVTX export tools",
        "required_checks": (
            "message text normalization",
            "inserted parameter mapping",
            "provider/template/source provenance",
            "trusted rendered-message diff pass",
            "unresolved template warning",
            "fallback-message limitation disclosure",
        ),
    },
    {
        "number": 3,
        "title": "EVTX deleted/corrupt record recovery validation",
        "surface": "slack/deleted/corrupt record candidates with offsets and confidence",
        "corpus": "known-answer EVTX slack, truncated chunks, corrupt checksums, and carved record headers",
        "oracle": "hand-labeled offsets plus second-parser recovery output",
        "required_checks": (
            "chunk-boundary containment",
            "record-size plausibility",
            "checksum/integrity status",
            "candidate reason and confidence",
            "trusted recovery offset diff pass",
            "non-reportable default for unvalidated recovery",
        ),
    },
    {
        "number": 4,
        "title": "Registry hive full key tree reconstruction",
        "surface": "regf/hbin/nk/vk/sk/lf/lh/ri tree rows and parent/value links",
        "corpus": "NTUSER/SOFTWARE/SYSTEM hives with nested keys, value lists, dirty sequence numbers, and transaction logs",
        "oracle": "regripper/RegRipper, python-registry, exported .reg, and hand-labeled offsets",
        "required_checks": (
            "root-cell reachability",
            "parent-child backlink consistency",
            "value-list ownership",
            "last-write timestamp preservation",
            "transaction-log replay disclosure",
        ),
    },
    {
        "number": 5,
        "title": "Registry deleted key/value recovery",
        "surface": "free-cell nk/vk candidates, allocator state, parent confidence, data previews",
        "corpus": "hives with deleted keys/values, allocator reuse, transaction logs, and false-positive free cells",
        "oracle": "hand-labeled deleted-cell corpus and second-parser comparison",
        "required_checks": (
            "positive-size free-cell validation",
            "parent-key confirmation",
            "data-type and data-length plausibility",
            "allocator-state evidence",
            "reportability blocked until independent confirmation",
        ),
    },
    {
        "number": 6,
        "title": "SAM/SECURITY/SYSTEM account and permission deep parser",
        "surface": "SAM F/V, aliases, SECURITY policy/LSA metadata, ControlSet, privileges",
        "corpus": "Windows version matrix with local/admin/deleted/disabled accounts and group aliases",
        "oracle": "Windows API/Registry exports, RegRipper, and known account lifecycle assertions",
        "required_checks": (
            "RID/name/SID consistency",
            "UAC flag decoding",
            "group alias membership reconstruction",
            "privilege assignment attribution",
            "secret-value redaction and authority gate",
        ),
    },
    {
        "number": 7,
        "title": "Amcache parser",
        "surface": "Amcache.hve execution/install path, hash, publisher, timestamp semantics",
        "corpus": "Windows 7/8/10/11 Amcache schema variants and installer/execution fixtures",
        "oracle": "AmcacheParser/RegRipper export and hand-labeled timestamp semantics",
        "required_checks": (
            "schema-version detection",
            "path/hash/publisher extraction",
            "timestamp source labeling",
            "execution caveat wording",
            "deleted/legacy schema fallback warnings",
        ),
    },
    {
        "number": 8,
        "title": "ShimCache/AppCompatCache parser",
        "surface": "SYSTEM AppCompatCache binary entries by OS version",
        "corpus": "Windows XP through Windows 11 cache layouts with non-executed references",
        "oracle": "AppCompatCacheParser/ShimCacheParser and OS-version known-answer data",
        "required_checks": (
            "OS layout selection",
            "path/timestamp/flag decoding",
            "entry order preservation",
            "not-proof-of-execution warning",
            "malformed binary bounds checks",
        ),
    },
    {
        "number": 9,
        "title": "BAM/DAM execution parser",
        "surface": "SYSTEM BAM/DAM SID/path/FILETIME records",
        "corpus": "Windows 10/11 BAM/DAM hives with multiple SIDs and device paths",
        "oracle": "RegRipper/BAM parser output plus known execution timeline",
        "required_checks": (
            "SID extraction",
            "device path normalization",
            "FILETIME validity",
            "ControlSet attribution",
            "execution-semantics warning",
        ),
    },
    {
        "number": 10,
        "title": "SRUM full ESE table parser",
        "surface": "SRUDB ESE catalog/pages/tables/rows for app/network/resource usage",
        "corpus": "SRUDB.dat fixtures with network bytes, energy, app resources, and damaged pages",
        "oracle": "srum-dump/SrumECmd export and hand-labeled ESE page assertions",
        "required_checks": (
            "ESE page checksum validation",
            "catalog/table mapping",
            "tagged column decoding",
            "counter/timestamp semantics",
            "native-row confidence scoring",
        ),
    },
    {
        "number": 11,
        "title": "Windows.edb full ESE parser",
        "surface": "Windows Search ESE tables, properties, content snippets, deleted/index state",
        "corpus": "Windows.edb fixtures with files, URLs, content, deleted-state markers, and damaged pages",
        "oracle": "esentutl/export utilities, ESE parser exports, and known document/property assertions",
        "required_checks": (
            "catalog/table/page mapping",
            "property ID/name mapping",
            "path/URL/content correlation",
            "deleted/index-state validation",
            "page-level source citation",
        ),
    },
    {
        "number": 12,
        "title": "$MFT full attribute parser",
        "surface": "FILE records, attributes, resident/nonresident data, paths, timestamps, deleted state",
        "corpus": "NTFS volumes with attribute lists, hard links, deleted records, USA repairs, and nonresident runlists",
        "oracle": "MFTECmd/TSK output and byte-level FILE record assertions",
        "required_checks": (
            "USA validation",
            "attribute-list extension resolution",
            "parent path reconstruction",
            "runlist decoding",
            "timestamp/source field provenance",
        ),
    },
    {
        "number": 13,
        "title": "$UsnJrnl large-scale timeline parser",
        "surface": "USN v2/v3/v4 records, FRN/parent replay, rename/delete timeline",
        "corpus": "large USN journals with renames, deletes, truncation, v3 FILE_ID_128, and cursor pagination",
        "oracle": "MFTECmd/USN parser output plus replayed filesystem known-answer timeline",
        "required_checks": (
            "record-size bounds",
            "reason flag decoding",
            "FRN path cache replay",
            "rename/delete ordering",
            "cursor determinism at scale",
        ),
    },
    {
        "number": 14,
        "title": "JumpList DestList deep parser",
        "surface": "Automatic/Custom Destinations OLE streams, DestList entries, embedded LNKs",
        "corpus": "JumpList fixtures across OS versions with deleted streams and known AppIDs",
        "oracle": "JLECmd/LNK parser output and known application mapping",
        "required_checks": (
            "CFB stream inventory",
            "DestList header/entry layout",
            "embedded LNK linkage",
            "AppID mapping provenance",
            "deleted-entry warning",
        ),
    },
    {
        "number": 15,
        "title": "ShellBags native hive parser",
        "surface": "BagMRU/Bags relationships, shell item binary payloads, NTUSER/UsrClass transaction context",
        "corpus": "ShellBag hives with nested folders, network paths, deleted bags, and transaction logs",
        "oracle": "ShellBagsExplorer/SBECmd output and hand-labeled shell item paths",
        "required_checks": (
            "BagMRU/Bags relationship",
            "shell item binary decoding",
            "timestamp source labeling",
            "UsrClass/NTUSER correlation",
            "deleted/slack validation warning",
        ),
    },
    {
        "number": 16,
        "title": "Prefetch full version parser",
        "surface": "PF versions 17/23/26/30/31 sections, run counts, volumes, file metrics",
        "corpus": "compressed and uncompressed Prefetch files across Windows versions",
        "oracle": "PECmd/WinPrefetchView output and known run-count fixtures",
        "required_checks": (
            "SCCA/header validation",
            "version-specific section offsets",
            "run count and last-run timestamps",
            "volume/file metrics",
            "compressed PF handling",
        ),
    },
    {
        "number": 17,
        "title": "LNK full metadata parser",
        "surface": "ShellLinkHeader, LinkInfo, StringData, ExtraData, tracker GUID metadata",
        "corpus": "LNK fixtures for local, removable, network, Unicode, arguments, and tracker metadata",
        "oracle": "LECmd/Windows shell properties and hand-labeled link fields",
        "required_checks": (
            "header flag consistency",
            "target/working-dir/arguments extraction",
            "drive/network metadata",
            "tracker GUID validation",
            "timestamp/source field provenance",
        ),
    },
    {
        "number": 18,
        "title": "WER/Defender/Firewall/Task Scheduler/WMI deep parser",
        "surface": "WER reports/dumps, Defender logs, Firewall logs, Task XML/TaskCache, WMI repository pivots",
        "corpus": "Windows IR fixtures with malware detections, scheduled tasks, WMI persistence, and crash reports",
        "oracle": "Windows native exports, Chainsaw/Hayabusa/Velociraptor, and hand-labeled IR assertions",
        "required_checks": (
            "event semantics and risk rules",
            "Task XML/TaskCache correlation",
            "Defender/Firewall field normalization",
            "WER dump/cab linkage",
            "WMI consumer/filter binding validation",
        ),
    },
    {
        "number": 19,
        "title": "Browser cache/session/extension/sync artifacts",
        "surface": "Chromium/Firefox/Safari cache, sessions, extensions, cookies, sync, credential stores",
        "corpus": "multi-browser profiles with cache entries, session restore, extensions, cookies, and cleared history",
        "oracle": "browser DB queries, BrowserHistoryView/Hindsight exports, and known browsing sessions",
        "required_checks": (
            "profile/source attribution",
            "cache/session schema validation",
            "extension ID/source mapping",
            "secret/cookie opt-in legal gate",
            "deleted/synced content warning",
        ),
    },
    {
        "number": 20,
        "title": "Chrome/Edge/Firefox/Safari unified browser timeline",
        "surface": "cross-browser visit/download/search timeline with transition and profile metadata",
        "corpus": "Windows/macOS profiles with multiple browsers, downloads, typed URLs, and timezone edge cases",
        "oracle": "browser-native SQLite queries and trusted browser forensic exports",
        "required_checks": (
            "timestamp normalization",
            "transition semantics",
            "download target/source URL linkage",
            "multi-profile deduplication",
            "Safari scope limitation disclosure",
        ),
    },
    {
        "number": 21,
        "title": "AI service transcript parser for ChatGPT/Claude/Gemini/Perplexity",
        "surface": "browser storage/export prompt-answer candidates with service labels and pairing confidence",
        "corpus": "service exports and browser storage fixtures for ChatGPT, Claude, Gemini, Perplexity, and schema changes",
        "oracle": "service export JSON/HTML and hand-labeled Q/A pairs",
        "required_checks": (
            "service/schema version detection",
            "question/answer pairing confidence",
            "orphan prompt/answer tracking",
            "source offset/storage provenance",
            "privacy and completeness warnings",
        ),
    },
    {
        "number": 22,
        "title": "E01/Ex01 fully integrated workflow",
        "surface": "libewf/Sleuth Kit mount/extract, partition selection, progress, hashes, resume",
        "corpus": "E01/Ex01 images with partitions, corrupt segments, encryption warnings, and known file hashes",
        "oracle": "ewfverify, mmls/fls/tsk_recover output, and known-answer image manifest",
        "required_checks": (
            "source hash and segment integrity",
            "tool version/command capture",
            "partition offset correctness",
            "read-only extraction provenance",
            "corrupt/encrypted limitation reporting",
        ),
    },
    {
        "number": 23,
        "title": "RAW/split image robust partition/filesystem handling",
        "surface": "DD/RAW/IMG/001 split detection, partition/filesystem extraction, gap warnings",
        "corpus": "raw and split images with missing segments, multiple filesystems, deleted files, and encrypted volumes",
        "oracle": "TSK output plus known-answer recovered file/hash manifest",
        "required_checks": (
            "split-set order and gap validation",
            "partition table parsing",
            "filesystem extraction audit",
            "deleted-file recovery expectations",
            "encrypted volume limitation warning",
        ),
    },
    {
        "number": 24,
        "title": "VHD/VHDX/VMDK/VDI/QCOW direct handling polish",
        "surface": "virtual disk conversion/extraction with snapshot and provenance handling",
        "corpus": "VM disks with differencing chains, snapshots, compression, corruption, and known recovered hashes",
        "oracle": "qemu-img info/convert, TSK extraction, and hypervisor metadata manifest",
        "required_checks": (
            "qemu-img version/command capture",
            "snapshot/differencing-chain detection",
            "converted raw hash/provenance",
            "nested partition extraction",
            "unsupported/encrypted VM warning",
        ),
    },
    {
        "number": 25,
        "title": "AD1/L01/Lx01/AFF/AFF4/XVA support",
        "surface": "forensic container detection, export-first workflow, source integrity, and native parser gates",
        "corpus": "AD1/L01/Lx01/AFF/AFF4/XVA samples or vendor exports with known file manifests",
        "oracle": "vendor export logs, afflib where available, and known-answer file/hash manifest",
        "required_checks": (
            "container type detection",
            "source integrity capture",
            "native-vs-export workflow disclosure",
            "metadata/deleted-entry validation",
            "encrypted/compressed limitation warning",
        ),
    },
    {
        "number": 26,
        "title": "Cellebrite/XRY/GrayKey/AXIOM export deep import",
        "surface": "vendor export messages, contacts, calls, files, apps, accounts, browser/media rows",
        "corpus": "versioned vendor exports with deleted-record and duplicate-message edge cases",
        "oracle": "source vendor tool report, acquisition hash manifest, and hand-labeled row counts",
        "required_checks": (
            "source tool/version/profile detection",
            "row count and source ID preservation",
            "duplicate/deleted semantics",
            "source hash and acquisition linkage",
            "schema version compatibility warning",
        ),
    },
    {
        "number": 27,
        "title": "iOS backup parser",
        "surface": "Manifest.db, domains, Info/Status plist, app DB/media/message inventory",
        "corpus": "encrypted and unencrypted iOS backups with messages, media, app domains, and deleted records",
        "oracle": "iTunes/idevicebackup metadata, iLEAPP exports, and known backup manifest assertions",
        "required_checks": (
            "Manifest.db domain/fileID mapping",
            "Info/Status plist consistency",
            "encrypted backup authority gate",
            "app database schema detection",
            "deleted-record limitation warning",
        ),
    },
    {
        "number": 28,
        "title": "iOS keychain/artifact parser",
        "surface": "keychain inventory, protected-data metadata, redacted secret handling",
        "corpus": "authorized keychain exports with generic/password/certificate records and protected data states",
        "oracle": "iLEAPP/keychain-dumper style inventory and legal authority manifest",
        "required_checks": (
            "secret values redacted by default",
            "protected-data class labeling",
            "authority gate before reveal/decrypt",
            "record count/table inventory",
            "audit log for any controlled reveal",
        ),
    },
    {
        "number": 29,
        "title": "Android backup/artifact parser",
        "surface": "Android backup/export SMS, calls, contacts, browser, media, app DB/file artifacts",
        "corpus": "Android logical/backup exports with schema variants, media links, and encrypted stores",
        "oracle": "ALEAPP/vendor export plus known app/table assertions",
        "required_checks": (
            "package/path attribution",
            "SMS/call/contact row validation",
            "browser/media source linkage",
            "encrypted-store limitation",
            "app-specific schema version tracking",
        ),
    },
    {
        "number": 30,
        "title": "Android app package/data parser",
        "surface": "APK manifest/permissions/components/DEX strings/native libraries plus app data inventory",
        "corpus": "benign and malicious APKs with binary manifests, signatures, native code, and app databases",
        "oracle": "apkanalyzer/aapt/jadx/MobSF exports and known malware triage labels",
        "required_checks": (
            "binary manifest decode or limitation",
            "permission/component normalization",
            "signature chain validation",
            "DEX/native string pivot bounds",
            "app-data schema and secret-handling warnings",
        ),
    },
    {
        "number": 31,
        "title": "KakaoTalk parser",
        "surface": "authorized KakaoTalk exports, PC inventory/decrypt workflows, chat/message/media pivots",
        "corpus": "pre/post-2025-08 KakaoTalk exports and Windows PC stores with known chat/message/media counts",
        "oracle": "authorized KakaoTalk export, validated decrypted SQLite, vendor tool output, and hand-labeled message assertions",
        "required_checks": (
            "KakaoTalk service/profile detection",
            "chat/message participant/media normalization",
            "schema/app version and BigBang compatibility tracking",
            "encrypted/deleted limitation warning",
            "source hash and legal provenance",
        ),
    },
    {
        "number": 32,
        "title": "WhatsApp parser",
        "surface": "authorized WhatsApp exports, msgstore/contact/media/call database inventory",
        "corpus": "WhatsApp exports and msgstore/contact fixtures across schema and crypt variants",
        "oracle": "WhatsApp export text, validated msgstore.db decode, vendor tool output, and hand-labeled media/message counts",
        "required_checks": (
            "WhatsApp service/profile detection",
            "chat/contact/media normalization",
            "crypt backup authority workflow warning",
            "deleted-row limitation warning",
            "source hash and app-version provenance",
        ),
    },
    {
        "number": 33,
        "title": "Telegram parser",
        "surface": "Telegram desktop/mobile export rows, cache/media/account attribution, database inventory",
        "corpus": "Telegram JSON/HTML exports and desktop/mobile cache/database fixtures",
        "oracle": "Telegram native export, vendor tool output, and hand-labeled chat/media/account assertions",
        "required_checks": (
            "Telegram service/profile detection",
            "chat/user/media attribution",
            "account/cache provenance",
            "encrypted local store warning",
            "deleted/cache recovery limitation",
        ),
    },
    {
        "number": 34,
        "title": "Signal parser",
        "surface": "authorized Signal exports/backups, SQLCipher-safe inventory, thread/message/recipient pivots",
        "corpus": "Signal exports/backups with thread, recipient, attachment, deleted, and encrypted-store variants",
        "oracle": "authorized Signal export, validated SQLCipher decode where legally supplied, and hand-labeled assertions",
        "required_checks": (
            "Signal service/profile detection",
            "thread/recipient/message inventory",
            "SQLCipher/key authority gate",
            "attachment/deleted limitation warning",
            "secret-safe legal provenance",
        ),
    },
    {
        "number": 35,
        "title": "Extended messenger parser",
        "surface": "WeChat/LINE/Discord/Instagram and extended messenger authorized exports/databases",
        "corpus": "service-specific exports covering media, reactions, read-state, edits, deletes, and ephemeral modes",
        "oracle": "native service export, vendor tool output, and hand-labeled message/media/reaction assertions",
        "required_checks": (
            "extended service/profile detection",
            "message/media/reaction normalization",
            "schema/app version registry",
            "encrypted/ephemeral limitation warning",
            "source hash and legal provenance",
        ),
    },
    {
        "number": 36,
        "title": "Email PST/OST full mailbox parser",
        "surface": "EML/MBOX/Maildir parsing and PST/OST/MSG mailbox inventory with attachment/thread pivots",
        "corpus": "mailboxes with folder trees, duplicate threads, attachments, deleted items, PST/OST/MSG variants",
        "oracle": "libpff/readpst/Outlook exports, MBOX/EML ground truth, and hand-labeled folder/message assertions",
        "required_checks": (
            "mailbox/message source profile detection",
            "message header/body/attachment inventory",
            "PST/OST native limitation warning",
            "threading/dedup validation warning",
            "legal privilege boundary",
        ),
    },
    {
        "number": 37,
        "title": "Gmail/Google Takeout deep parser",
        "surface": "Gmail, Drive, Photos, Activity, Location, and account Takeout exports",
        "corpus": "Google Takeout exports with selected products, split archives, sidecars, Gmail threads, and location/activity variants",
        "oracle": "Google Takeout index/native views, provider API spot-checks, and hand-labeled product assertions",
        "required_checks": (
            "Google service/profile detection",
            "Gmail/Drive/Activity/Location normalization",
            "source hash and export-scope warning",
            "sidecar/media/linkage limitation",
            "provider schema/timezone warning",
        ),
    },
    {
        "number": 38,
        "title": "Apple iCloud export parser",
        "surface": "iCloud/Apple privacy export account, file, photos, mail, and shared metadata rows",
        "corpus": "Apple privacy exports and iCloud copies with photos, shared albums, files, accounts, and ADP limitations",
        "oracle": "Apple export index/iCloud web view, EXIF/sidecar assertions, and hand-labeled account/file metadata",
        "required_checks": (
            "Apple/iCloud service profile detection",
            "account/file/photo metadata normalization",
            "source hash and export-scope warning",
            "ADP/shared-album limitation warning",
            "provider retention/schema warning",
        ),
    },
    {
        "number": 39,
        "title": "Microsoft 365/OneDrive/Teams export parser",
        "surface": "Microsoft 365, OneDrive, SharePoint, Teams, Exchange, and audit exports",
        "corpus": "Purview/eDiscovery/Graph exports with Teams messages, reactions, OneDrive files, audit and permission states",
        "oracle": "Purview/eDiscovery export, Graph API spot-checks, and hand-labeled Teams/OneDrive/Audit assertions",
        "required_checks": (
            "Microsoft 365 service profile detection",
            "mail/file/message/audit normalization",
            "source hash and eDiscovery/export warning",
            "permissions/retention/deleted limitation",
            "provider schema/timestamp warning",
        ),
    },
    {
        "number": 40,
        "title": "Cloud API acquisition workflow",
        "surface": "manifest-driven cloud API collection, credential redaction, response hashing, and import workflow",
        "corpus": "authorized provider API fixtures covering pagination, retries, scope, OAuth, delta, and error handling",
        "oracle": "provider API/native export diff, request/response hash manifest, and reviewer-signed authorization metadata",
        "required_checks": (
            "manifest request validation",
            "credential redaction",
            "response hash/provenance",
            "pagination/backoff limitation warning",
            "provider OAuth/scope/legal warning",
        ),
    },
    {
        "number": 41,
        "title": "Cloud token/credential secure handling",
        "surface": "cloud API tokens, request headers, storage boundary, scope/consent metadata, and audit warnings",
        "corpus": "authorized cloud collection manifests with bearer/API-key headers, scope metadata, redaction checks, and rotation/revocation evidence",
        "oracle": "provider OAuth consent records, native audit logs, redacted request manifests, and reviewer-signed authorization metadata",
        "required_checks": (
            "token value redaction",
            "environment or vault storage boundary",
            "scope and consent capture warning",
            "rotation and revocation audit warning",
            "legal authority warning",
        ),
    },
    {
        "number": 42,
        "title": "Browser password/cookie/session artifact handling with strict legal warning",
        "surface": "browser credential stores, cookies, session tokens, keychain/DPAPI boundaries, and redacted inventory",
        "corpus": "Chrome/Edge/Firefox/Safari profiles with password, cookie, and session stores across OS keychain states",
        "oracle": "browser-native store inventory, OS keychain/DPAPI validation fixtures, and legal authority/audit records",
        "required_checks": (
            "sensitive artifact inventory",
            "secret values redacted by default",
            "strict legal warning",
            "opt-in reveal workflow warning",
            "audit and scope review requirement",
        ),
    },
    {
        "number": 43,
        "title": "Mobile app media/message timeline correlation",
        "surface": "mobile messages, media attachments, calls, contacts, app rows, source export scope, and timeline-ready links",
        "corpus": "vendor mobile exports with known chat/media/contact/call relationships and schema/timezone variants",
        "oracle": "vendor tool timeline, native app export, hand-labeled message-media links, and acquisition hash manifest",
        "required_checks": (
            "message-media linkage built",
            "message/contact/call/media counts preserved",
            "service attribution",
            "timeline correlation readiness",
            "known-answer limitation warning",
        ),
    },
    {
        "number": 44,
        "title": "Contact/call/SMS unified mobile view",
        "surface": "contacts, calls, SMS/messages, participants, actor pivots, and grouped mobile review rows",
        "corpus": "mobile exports with overlapping contacts, calls, SMS, chat participants, duplicate identities, and deleted rows",
        "oracle": "vendor mobile report, native phone export, and hand-labeled actor/contact/call/SMS assertions",
        "required_checks": (
            "contact/call/SMS actor merge",
            "source row links preserved",
            "participant attribution",
            "dedupe/entity limitation warning",
            "export-scope limitation warning",
        ),
    },
    {
        "number": 45,
        "title": "App-specific known schema version management",
        "surface": "app names, package IDs, app/export/schema versions, table inventories, and compatibility matrices",
        "corpus": "versioned app exports/databases across messenger, mobile OS, and vendor-export schema changes",
        "oracle": "native app schema documentation, vendor export version metadata, and migration fixture expected outputs",
        "required_checks": (
            "app/service schema version registry",
            "source app/version attribution",
            "schema compatibility warning",
            "migration fixture warning",
            "release-gate limitation disclosure",
        ),
    },
    {
        "number": 46,
        "title": "Large-result clustering",
        "surface": "search result clusters by source, artifact kind, extension, folder, keyword, and representative hits",
        "corpus": "large search-result fixtures with repeated documents, OCR hits, web/log rows, and noise clusters",
        "oracle": "hand-labeled cluster membership, reviewer triage outcomes, and performance/cursor validation logs",
        "required_checks": (
            "bounded cluster generation",
            "representative match links",
            "source and keyword grouping",
            "truncation disclosure",
            "review-state limitation warning",
        ),
    },
    {
        "number": 47,
        "title": "Entity view for people/accounts/email/phone/IP/domain",
        "surface": "normalized entity pivots, source counts, match references, risk flags, and merge/split limitations",
        "corpus": "search fixtures with emails, URLs/domains, public IPs, hashes, phone numbers, people, and account hints",
        "oracle": "hand-labeled entity set, false-positive list, and analyst-reviewed merge/split decisions",
        "required_checks": (
            "entity extraction across supported types",
            "source and path references",
            "match reference links",
            "risk flag assignment",
            "merge/split limitation warning",
        ),
    },
    {
        "number": 48,
        "title": "Graph view for account-file-URL-time relationships",
        "surface": "bounded graph nodes/edges connecting matches, paths, keywords, entities, URLs, and source citations",
        "corpus": "search fixtures with known account-file-URL relationships, graph truncation boundaries, and source citations",
        "oracle": "hand-labeled relationship graph and source-row citation review",
        "required_checks": (
            "match/path/keyword/entity nodes",
            "relationship edges built",
            "source citation references",
            "graph paging/truncation disclosure",
            "causal-proof limitation warning",
        ),
    },
    {
        "number": 49,
        "title": "Unified timeline correlation",
        "surface": "timestamp extraction, UTC normalization, date buckets, timeline events, and source match anchors",
        "corpus": "multi-source search fixtures with filesystem, browser, event log, mobile, cloud, and timezone edge cases",
        "oracle": "hand-labeled chronological order, source timestamp semantics, and timezone/skew validation notes",
        "required_checks": (
            "timestamp extraction",
            "UTC normalization",
            "source match anchors",
            "date bucket generation",
            "timezone/skew limitation warning",
        ),
    },
    {
        "number": 50,
        "title": "Incident hypothesis/workbook feature",
        "surface": "draft hypotheses, evidence cluster links, review tasks, questions, next actions, and report-readiness flags",
        "corpus": "case-search fixtures with credential, web/AI, execution, and network/cloud investigation scenarios",
        "oracle": "analyst workbook rubric, hand-labeled hypothesis/evidence attachments, and report section review",
        "required_checks": (
            "draft hypotheses generated",
            "evidence cluster links",
            "review tasks and questions",
            "report-readiness flag",
            "persistence/versioning limitation warning",
        ),
    },
    {
        "number": 51,
        "title": "Reviewer assignment/status workflow",
        "surface": "review marks, reviewer/assignee, priority, due dates, verification status, report inclusion, and history",
        "corpus": "case database fixtures with assigned/reassigned review decisions, batch updates, saved searches, and report exports",
        "oracle": "analyst review log, case database audit history, and reviewer sign-off workflow checklist",
        "required_checks": (
            "review status fields persisted",
            "assignment and priority captured",
            "verification status captured",
            "report inclusion state captured",
            "history/audit limitation warning",
        ),
    },
    {
        "number": 52,
        "title": "A/B/C multi-evidence compare",
        "surface": "two-way and baseline multi-file compare, hashes, text diff, labels, status counts, and report pivots",
        "corpus": "file comparison fixtures with same/different text, binary files, labels, and report review selections",
        "oracle": "known file hashes, expected unified diff output, and analyst-selected comparison notes",
        "required_checks": (
            "A/B/C baseline compare",
            "hash comparison",
            "bounded text diff",
            "status counts",
            "specialized diff limitation warning",
        ),
    },
    {
        "number": 53,
        "title": "Raw/source hex viewer",
        "surface": "bounded hex rows, offsets, ASCII, preview hash, byte search citations, and safe copy/export warnings",
        "corpus": "binary source fixtures with known byte offsets, repeated terms, truncation boundaries, and hash assertions",
        "oracle": "known byte-offset manifest, source hash output, and manual hex editor comparison",
        "required_checks": (
            "bounded hex rows",
            "byte offsets and hex offsets",
            "preview hash",
            "byte-search citation support",
            "full-source validation warning",
        ),
    },
    {
        "number": 54,
        "title": "SQLite/table specialized viewer",
        "surface": "read-only SQLite table preview, schema SQL, column details, indexes, row samples, and text search hooks",
        "corpus": "SQLite fixtures with tables, views, indexes, primary keys, text/blob columns, and large row counts",
        "oracle": "sqlite3 CLI queries, expected schema/table row assertions, and source database hashes",
        "required_checks": (
            "read-only SQLite open",
            "table and schema inventory",
            "column/index metadata",
            "bounded row preview",
            "deleted/WAL limitation warning",
        ),
    },
    {
        "number": 55,
        "title": "Email conversation viewer",
        "surface": "threaded email previews, headers, participants, message order, attachments, and conversation limitations",
        "corpus": "EML/MBOX fixtures with Message-ID, References/In-Reply-To, attachments, and duplicate subjects",
        "oracle": "mail client/thread export, message header assertions, and attachment inventory manifest",
        "required_checks": (
            "thread grouping",
            "message order",
            "participant/header preservation",
            "attachment inventory",
            "mailbox threading limitation warning",
        ),
    },
    {
        "number": 56,
        "title": "Image gallery review mode",
        "surface": "image dimensions, source hashes, thumbnails, perceptual hash, similarity bucket, tags, and report selection hints",
        "corpus": "image fixtures with dimensions, thumbnails, visually similar groups, OCR sidecars, and broken images",
        "oracle": "image metadata/hash manifest, visual review labels, and perceptual-hash expected buckets",
        "required_checks": (
            "image metadata and source hashes",
            "thumbnail or preview metadata",
            "perceptual similarity bucket",
            "tag/report selection hints",
            "visual-classifier limitation warning",
        ),
    },
    {
        "number": 57,
        "title": "Video/audio preview and transcript",
        "surface": "media metadata, source hashes, transcript sidecars, cue timestamps, and playback/transcript limitations",
        "corpus": "audio/video fixtures with WAV metadata, SRT/VTT/TXT transcript sidecars, cue ranges, and hash assertions",
        "oracle": "media metadata tools, transcript cue manifest, and manual playback verification notes",
        "required_checks": (
            "media metadata extracted",
            "source hashes captured",
            "transcript sidecars imported",
            "cue timestamps preserved",
            "playback/transcript verification warning",
        ),
    },
    {
        "number": 58,
        "title": "OCR queue manager",
        "surface": "OCR candidate queue, sidecar import, retry state, source/sidecar hashes, metadata, and status counts",
        "corpus": "image fixtures with OCR sidecars, metadata sidecars, failed previous queues, and retry scenarios",
        "oracle": "expected queue manifest, OCR sidecar hash manifest, and external OCR engine run logs",
        "required_checks": (
            "queue item generation",
            "sidecar import and hashes",
            "retry state handling",
            "engine/metadata preservation",
            "native OCR limitation warning",
        ),
    },
    {
        "number": 59,
        "title": "Korean OCR/translation workflow hardening",
        "surface": "Korean language hints, OCR quality metrics, translation sidecars, confidence metadata, and review warnings",
        "corpus": "Korean/English image OCR fixtures with Hangul sidecars, translations, confidence, and engine metadata",
        "oracle": "human-reviewed OCR/translation expected text, sidecar hashes, and language-pack validation logs",
        "required_checks": (
            "Korean language hinting",
            "OCR quality metrics",
            "translation sidecar import",
            "confidence/engine metadata",
            "human translation validation warning",
        ),
    },
    {
        "number": 60,
        "title": "Search hit deduplication",
        "surface": "duplicate groups by hash or normalized preview, representative hits, source/path links, and suppression warnings",
        "corpus": "search-result fixtures with exact hash duplicates, repeated previews, OCR duplicates, and near-duplicate noise",
        "oracle": "hand-labeled duplicate groups, hash manifests, and reviewer suppression decisions",
        "required_checks": (
            "duplicate fingerprint generation",
            "duplicate group counts",
            "representative hit links",
            "source/path references",
            "near-duplicate limitation warning",
        ),
    },
    {
        "number": 61,
        "title": "Fuzzy search/stemming/regex proximity search",
        "surface": "search mode/options, exact/fuzzy/regex/stem matching, proximity summaries, hit pointers, and verification warnings",
        "corpus": "search fixtures with typos, suffix variants, regex patterns, proximity windows, and false-positive terms",
        "oracle": "hand-labeled query-hit manifest, regex engine expectations, and source-row verification checklist",
        "required_checks": (
            "query mode and options recorded",
            "fuzzy/stemming/regex matching available",
            "proximity metadata preserved",
            "matched hit source pointers",
            "source verification limitation warning",
        ),
    },
    {
        "number": 62,
        "title": "Saved keyword pack library",
        "surface": "built-in packs, custom JSON packs, keyword counts, pack provenance, and validation blockers",
        "corpus": "keyword-pack fixtures with built-in names, custom JSON lists, duplicate terms, and case search replay",
        "oracle": "expected keyword expansion manifest and saved-search/replay review notes",
        "required_checks": (
            "built-in pack inventory",
            "custom JSON pack support",
            "deduplicated keyword expansion",
            "pack provenance recorded",
            "case-specific validation warning",
        ),
    },
    {
        "number": 63,
        "title": "IOC/TI enrichment plugin",
        "surface": "URL/domain/IP/hash pivots, local rules, offline TI feeds, feed provenance, and local-only warnings",
        "corpus": "indicator fixtures with URLs, domains, IPs, hashes, local rule hits, and JSON/CSV/TXT TI feeds",
        "oracle": "hand-labeled IOC set, local rule expected matches, and feed provenance manifest",
        "required_checks": (
            "indicator extraction and source links",
            "local rule match preservation",
            "offline feed provenance",
            "match mode recorded",
            "local-only/no-external-call warning",
        ),
    },
    {
        "number": 64,
        "title": "Report citation manager",
        "surface": "citation IDs, review/source citation pairs, source references, report-use hints, and export counts",
        "corpus": "Case DB report fixtures with reviewed files, artifacts, searches, source references, and missing-source edge cases",
        "oracle": "expected citation index manifest and reviewer report citation checklist",
        "required_checks": (
            "review citation IDs",
            "source-record citation IDs",
            "source reference preserved",
            "citation count summary",
            "report-use verification warning",
        ),
    },
    {
        "number": 65,
        "title": "Evidence selection/version history",
        "surface": "review history rows, changed fields, actors, timestamps, previous/current states, and report inclusion",
        "corpus": "Case DB fixtures with status changes, include-in-report changes, batch review, and export replay",
        "oracle": "expected review history manifest, audit trail, and analyst sign-off checklist",
        "required_checks": (
            "versioned review history rows",
            "changed fields captured",
            "previous/current state captured",
            "report inclusion history",
            "multi-user/signing limitation warning",
        ),
    },
    {
        "number": 66,
        "title": "100k/1M/10M record benchmark",
        "surface": "benchmark metrics, p50/p95 search latency, records/sec, memory, scale matrix, and hardware blockers",
        "corpus": "synthetic and real benchmark runs at 100k, 1M, and 10M records with preserved run summaries",
        "oracle": "benchmark JSON/Markdown, hardware profile, dependency versions, and threshold comparison sheet",
        "required_checks": (
            "scale matrix emitted",
            "ingest/search metrics captured",
            "memory/output size captured",
            "run summary linked",
            "hardware-scale limitation warning",
        ),
    },
    {
        "number": 67,
        "title": "1TB-10TB evidence stress test",
        "surface": "stress scenarios, wall-clock estimates, resource caps, failure thresholds, runbook, and evidence requirements",
        "corpus": "large-evidence stress runs or runbooks for 1TB, 5TB, and 10TB cases",
        "oracle": "hardware run logs, resource telemetry, checkpoint output, crash logs, and independent reproduction notes",
        "required_checks": (
            "TB-scale scenarios emitted",
            "resource caps specified",
            "failure thresholds specified",
            "required evidence bundle listed",
            "real-hardware validation warning",
        ),
    },
    {
        "number": 68,
        "title": "Incremental indexing",
        "surface": "input fingerprints, changed-source detection, resume safety, bounded file scan metadata, and reuse warnings",
        "corpus": "run fixtures with unchanged inputs, changed mtimes/sizes, truncated fingerprints, and resume attempts",
        "oracle": "expected fingerprint/reuse manifest and repeated-run output comparison",
        "required_checks": (
            "input fingerprint emitted",
            "path/size/mtime metadata captured",
            "changed-source reuse disabled",
            "truncation disclosure",
            "per-file reindex limitation warning",
        ),
    },
    {
        "number": 69,
        "title": "Background job queue",
        "surface": "queued/running/completed/failed/canceled statuses, persisted state, steps, cancellation flags, and retry support",
        "corpus": "job-store fixtures with queued, failed, canceled, retried, imported, and completed runs",
        "oracle": "expected job state JSON, step transition log, and web/API workflow assertions",
        "required_checks": (
            "job status persisted",
            "step progress recorded",
            "state-file persistence",
            "cancel/retry state recorded",
            "local-threadpool limitation warning",
        ),
    },
    {
        "number": 70,
        "title": "Stage checkpoint/resume hardening",
        "surface": "stage checkpoints, output paths/sizes, reused flags, resume effective state, and failed-stage limitations",
        "corpus": "run fixtures with fresh runs, resume runs, changed fingerprints, and partial/missing stage outputs",
        "oracle": "expected checkpoint manifest and resumed-run output comparison",
        "required_checks": (
            "stage checkpoints emitted",
            "output path and size captured",
            "reused flag captured",
            "resume status summarized",
            "partial-stage limitation warning",
        ),
    },
    {
        "number": 71,
        "title": "Parser crash isolation",
        "surface": "isolated parser failures, parser error rows, continued run summaries, and crash corpus warnings",
        "corpus": "parser-stage fixtures with synthetic exceptions, corrupt inputs, partial artifacts, and successful sibling parsers",
        "oracle": "expected parser_errors payload, run continuation summary, failed-parser JSON output, and crash-corpus checklist",
        "required_checks": (
            "per-parser exception capture",
            "failed parser JSON output",
            "run continuation after parser error",
            "summary warning surfaced",
            "native sandbox/fuzzing limitation warning",
        ),
    },
    {
        "number": 72,
        "title": "Memory cap enforcement",
        "surface": "configured memory cap, RSS readings, stage-boundary checks, fail-fast behavior, and platform caveats",
        "corpus": "run fixtures with unset cap, configured cap, exceeded cap, and platform RSS reporting differences",
        "oracle": "expected resource cap JSON, failure message, RSS evidence, and platform caveat matrix",
        "required_checks": (
            "memory cap configuration recorded",
            "RSS reading captured",
            "stage-boundary enforcement",
            "fail-fast corruption prevention warning",
            "hard OS limit limitation warning",
        ),
    },
    {
        "number": 73,
        "title": "Preview sandboxing",
        "surface": "read-only previews, active-content blocking, network denial, bounded text/hex caps, and sandbox warnings",
        "corpus": "viewer fixtures with HTML/SVG/script, binary files, large text, SQLite, media, and structured documents",
        "oracle": "expected viewer_sandbox metadata, active-content flags, cap metadata, and no-execution assertion",
        "required_checks": (
            "read-only bounded preview",
            "active content execution blocked",
            "external network access disabled",
            "preview caps recorded",
            "OS sandbox limitation warning",
        ),
    },
    {
        "number": 74,
        "title": "Large SQLite/FTS optimization",
        "surface": "SQLite WAL/cache pragmas, table profiles, text column counts, FTS readiness, and optimization caveats",
        "corpus": "Case DB and source-viewer SQLite fixtures with text columns, indexes, row previews, WAL mode, and large-table caps",
        "oracle": "expected pragma metadata, table profile summary, FTS/read-only preview output, and large-DB limitation sheet",
        "required_checks": (
            "SQLite performance pragmas applied",
            "table profile emitted",
            "searchable text columns counted",
            "bounded row preview preserved",
            "large corpus optimization limitation warning",
        ),
    },
    {
        "number": 75,
        "title": "Parallel parser scheduler",
        "surface": "bounded worker count, deterministic artifact outputs, per-parser capture, resume-aware scheduling, and queue limits",
        "corpus": "artifact-stage fixtures with multiple parser kinds, resume reuse, synthetic parser failure, and deterministic output checks",
        "oracle": "expected scheduler metadata, output path ordering, parser result capture, and local-threadpool caveat",
        "required_checks": (
            "bounded worker count",
            "deterministic output paths",
            "per-parser result capture",
            "resume-aware scheduling",
            "distributed scheduler limitation warning",
        ),
    },
    {
        "number": 76,
        "title": "File hash cache",
        "surface": "MD5/SHA1/SHA256 cache metadata, path-size-mtime keys, hit/miss counts, and persistence caveats",
        "corpus": "file metadata fixtures with repeated hash requests, changed mtimes/sizes, and large-file hash caps",
        "oracle": "expected hash values, cache hit/miss counters, invalidation behavior, and persistence limitation notes",
        "required_checks": (
            "MD5/SHA1/SHA256 captured",
            "path-size-mtime cache key recorded",
            "hit/miss counters emitted",
            "hash cache assessment attached",
            "persistent cache limitation warning",
        ),
    },
    {
        "number": 77,
        "title": "Duplicate file/content detection",
        "surface": "same-size buckets, bounded SHA256 confirmation, duplicate groups, representative paths, and suppression warnings",
        "corpus": "file scan fixtures with exact duplicates, same-size non-duplicates, large skipped candidates, and path truncation",
        "oracle": "expected duplicate group manifest, SHA256 equality proof, skipped-boundary records, and analyst suppression checklist",
        "required_checks": (
            "same-size candidate bucketing",
            "bounded SHA256 confirmation",
            "duplicate group counts",
            "representative paths listed",
            "suppression verification warning",
        ),
    },
    {
        "number": 78,
        "title": "Artifact pagination/cursor API",
        "surface": "cursor tokens, offsets, limits, totals, next/previous cursors, and snapshot-isolation warnings",
        "corpus": "API fixtures covering files, documents, timeline, indicators, artifact groups, invalid cursor, and empty collections",
        "oracle": "expected pagination metadata, cursor decode behavior, bounded rows, and API compatibility checklist",
        "required_checks": (
            "cursor token emitted",
            "offset/limit/total recorded",
            "next/previous cursor support",
            "bounded row return",
            "snapshot isolation limitation warning",
        ),
    },
    {
        "number": 79,
        "title": "UI virtualization for massive result tables",
        "surface": "bounded DOM row windows, visible-row notices, keyboard/filter flow, persisted viewport hints, and paging links",
        "corpus": "web UI fixtures with search rows, Case DB rows, API-paged tabs, keyboard navigation, and large-table notices",
        "oracle": "expected DOM window metadata, rendered-row cap, visible-row warning, and browser responsiveness checklist",
        "required_checks": (
            "bounded DOM row window",
            "visible row count disclosed",
            "keyboard/filter workflow preserved",
            "API pagination link preserved",
            "true virtual scroller limitation warning",
        ),
    },
    {
        "number": 80,
        "title": "Long-running job cancellation/retry",
        "surface": "queued/running cancellation flags, failed/canceled retry, state-file persistence, step metadata, and cleanup caveats",
        "corpus": "job-store fixtures with queued cancel, running cancel request, failed retry, canceled retry, and persisted state reload",
        "oracle": "expected job transition log, cancellation flag, retry support matrix, and partial-output cleanup checklist",
        "required_checks": (
            "queued job cancellation",
            "running cancel request recorded",
            "failed/canceled retry support",
            "state-file cancel flag persisted",
            "partial output cleanup limitation warning",
        ),
    },
    {
        "number": 81,
        "title": "NIST CFReDS/CFTT based known-answer tests",
        "surface": "known-answer manifest ingestion, dataset status counts, evidence-path checks, public corpus guidance, and release gates",
        "corpus": "NIST-style known-answer manifests with pass/open/fail datasets, expected assertions, observed outputs, and evidence paths",
        "oracle": "known-answer manifest, public corpus reference, observed RapidTriage output, and reviewer sign-off",
        "required_checks": (
            "known-answer manifest ingested",
            "dataset status counts recorded",
            "evidence path existence checked",
            "public corpus guidance emitted",
            "report-grade release gate recorded",
        ),
    },
    {
        "number": 82,
        "title": "Parser-specific fixture corpus",
        "surface": "parser fixture areas, fixture/test counts, expected edge cases, coverage status, and release gates",
        "corpus": "repo fixture/test inventory for Windows, browser, mobile, cloud, email, memory, media, and OCR parser families",
        "oracle": "fixture inventory, test-file coverage matrix, expected edge-case list, and release gate checklist",
        "required_checks": (
            "parser areas inventoried",
            "fixture/test counts recorded",
            "expected edge cases listed",
            "coverage status summarized",
            "release gate for parser changes recorded",
        ),
    },
    {
        "number": 83,
        "title": "Parser false positive/false negative documentation",
        "surface": "parser-family FP/FN risk notes, validation-required wording, and limitation disclosure",
        "corpus": "parser-family limitation notes covering native Windows, browser/AI, mobile/cloud/email/media, and memory evidence",
        "oracle": "reviewed FP/FN risk register and parser-family validation checklist",
        "required_checks": (
            "false positive risks documented",
            "false negative risks documented",
            "validation-required guidance recorded",
            "parser family scope recorded",
            "quantification limitation warning",
        ),
    },
    {
        "number": 84,
        "title": "Independent validation report",
        "surface": "external report path, hash, size, required signoffs, minimum sections, and not-attached blocker",
        "corpus": "independent reviewer report attachments with scope, datasets, tool version, known-answer table, FP/FN notes, and legal review",
        "oracle": "signed independent validation report, hash manifest, and release-owner signoff",
        "required_checks": (
            "independent report status recorded",
            "report hash captured when attached",
            "required signoffs listed",
            "minimum report sections listed",
            "not-attached blocker recorded",
        ),
    },
    {
        "number": 85,
        "title": "Tool validation package automation",
        "surface": "validation JSON/Markdown/artifact manifest, output hashes, known-answer sections, fixture corpus, and limitations",
        "corpus": "release validation package outputs with JSON, Markdown, hash manifest, known-answer manifest, fixture corpus, FP/FN notes, and tool versions",
        "oracle": "validation package hash manifest, generated report, command log, and release checklist",
        "required_checks": (
            "validation JSON output generated",
            "validation Markdown output generated",
            "artifact hash manifest generated",
            "known-answer/fixture sections included",
            "package generation limitation warning",
        ),
    },
    {
        "number": 86,
        "title": "Chain-of-custody full workflow",
        "surface": "evidence sources, custody events, citation IDs, status, source hashes, and acquisition limitations",
        "corpus": "Case DB fixtures with evidence sources, audit events, review exports, and report-linked custody records",
        "oracle": "custody event manifest, evidence-source hash manifest, and examiner handoff checklist",
        "required_checks": (
            "evidence source inventory",
            "custody event inventory",
            "citation IDs preserved",
            "source status/hash fields preserved",
            "acquisition metadata limitation warning",
        ),
    },
    {
        "number": 87,
        "title": "Evidence acquisition hash workflow",
        "surface": "evidence-source hashes, hash records, algorithms, calculation times, and missing-hash warnings",
        "corpus": "Case DB fixtures with evidence-source MD5/SHA1/SHA256 values, hash_record rows, and report exports",
        "oracle": "hash manifest, source file hash comparison, and acquisition metadata checklist",
        "required_checks": (
            "evidence-source hashes exported",
            "hash records exported",
            "hash algorithms preserved",
            "calculation timestamps preserved",
            "missing hash limitation warning",
        ),
    },
    {
        "number": 88,
        "title": "Analyst action immutable audit log",
        "surface": "audit events, previous/event hash chain, actor/action/target/time fields, and notarization caveat",
        "corpus": "Case DB audit fixtures with review, import, export, and hash actions plus deterministic export replay",
        "oracle": "audit hash-chain manifest, append-only policy review, and external signing/notarization evidence",
        "required_checks": (
            "audit events exported",
            "previous/event hash chain generated",
            "actor/action/target/time fields preserved",
            "head hash recorded",
            "external notarization limitation warning",
        ),
    },
    {
        "number": 89,
        "title": "Report reproducibility",
        "surface": "stable payload hash, deterministic sorting, item/citation counts, volatile field disclosure, and replay caveats",
        "corpus": "Case DB report export fixtures replayed with identical source rows and deterministic citation ordering",
        "oracle": "same-input same-output hash comparison, deterministic sort checklist, and cross-platform replay notes",
        "required_checks": (
            "stable payload hash generated",
            "deterministic sorting documented",
            "item/citation counts recorded",
            "volatile fields disclosed",
            "cross-platform replay limitation warning",
        ),
    },
    {
        "number": 90,
        "title": "Report item source provenance completeness",
        "surface": "source path, hashes, parser/version/confidence, offsets/source index, review status, reportability, and evidence strength",
        "corpus": "Case DB report fixtures with reviewed files, documents, artifacts, search hits, and source_reference metadata",
        "oracle": "report provenance checklist, source hash manifest, parser version inventory, and reviewer signoff",
        "required_checks": (
            "source path preserved",
            "source or record hashes preserved",
            "parser/version/confidence preserved",
            "offset or source index preserved when available",
            "review/reportability fields preserved",
        ),
    },
    {
        "number": 91,
        "title": "Parser confidence scoring",
        "surface": "parser confidence, coverage status, reportability, validation warnings, and evidence strength per report item",
        "corpus": "Case DB report fixtures with mixed reportable, validation-required, and low-confidence parser outputs",
        "oracle": "parser-confidence calibration table, reportability checklist, and reviewer signoff",
        "required_checks": (
            "parser confidence preserved",
            "reportability state recorded",
            "coverage status recorded",
            "validation warnings derived",
            "evidence strength surfaced",
        ),
    },
    {
        "number": 92,
        "title": "Validation-required warning UX",
        "surface": "warning counts, item warning reasons, report badges/metadata, and reviewer guidance",
        "corpus": "Report fixtures with missing hashes, unsupported parser states, validation-required flags, and partial coverage",
        "oracle": "reviewer warning checklist, UI/report badge inventory, and expected warning reason manifest",
        "required_checks": (
            "validation warning reasons emitted",
            "summary warning counts emitted",
            "report guidance emitted",
            "validation-required state preserved",
            "warning UX limitation disclosed",
        ),
    },
    {
        "number": 93,
        "title": "Legal limitation statement per artifact",
        "surface": "artifact limitations, parser caveats, jurisdiction caveat, and analyst-review blockers",
        "corpus": "Report fixtures covering files, documents, artifacts, indicators, timeline rows, and parser-provided limitations",
        "oracle": "legal wording checklist, parser limitation inventory, and forensic-lead review",
        "required_checks": (
            "artifact limitation text emitted",
            "parser-provided limitations preserved",
            "jurisdiction caveat emitted",
            "analyst review blocker emitted",
            "limitation count summarized",
        ),
    },
    {
        "number": 94,
        "title": "Court exhibit export package",
        "surface": "selected exhibit index, exhibit IDs, output hashes, source references, review status, and verification steps",
        "corpus": "Reviewer bundle fixtures with selected evidence, report exports, hashes, skipped items, and sanitized report previews",
        "oracle": "court exhibit checklist, bundle manifest hash comparison, and selected-evidence manifest",
        "required_checks": (
            "exhibit IDs assigned",
            "selected evidence hashes preserved",
            "generated output hashes captured",
            "source references preserved",
            "verification steps emitted",
        ),
    },
    {
        "number": 95,
        "title": "External tool version capture",
        "surface": "external tool availability, path, command, return code, version output, and capture errors",
        "corpus": "Release validation package fixtures across Python, libewf/Sleuth Kit, qemu-img, OCR, and Node runtimes",
        "oracle": "release environment inventory, command transcript, and operator-preserved tool logs",
        "required_checks": (
            "tool inventory emitted",
            "tool path captured when available",
            "version command captured",
            "capture error recorded",
            "per-run limitation warning",
        ),
    },
    {
        "number": 96,
        "title": "Write-blocker/acquisition metadata recording",
        "surface": "operator, acquisition timestamps, source identifier, write-blocker, acquisition tool/version, whole-source hash, and missing-field checks",
        "corpus": "Case DB acquisition fixtures with complete and incomplete metadata records linked to evidence sources",
        "oracle": "acquisition form checklist, write-blocker log, source hash manifest, and examiner handoff record",
        "required_checks": (
            "operator/source metadata recorded",
            "write-blocker field recorded",
            "whole-source hash field recorded",
            "missing required fields listed",
            "submission readiness flag emitted",
        ),
    },
    {
        "number": 97,
        "title": "Timezone normalization validation",
        "surface": "original timestamps, source timezone, UTC assumption, timestamp kind, parser/source samples, and missing timezone counts",
        "corpus": "Case DB event fixtures with UTC, local, missing, and source-specific timezone values",
        "oracle": "timeline timezone checklist, source parser assumptions, and known timestamp fixture manifest",
        "required_checks": (
            "event timezone inventory emitted",
            "missing timezone count emitted",
            "timestamp samples preserved",
            "UTC assumption disclosed",
            "review-required flag emitted",
        ),
    },
    {
        "number": 98,
        "title": "Clock skew analysis",
        "surface": "parsed timestamp ranges, impossible/future timestamp warnings, baseline requirement, and heuristic caveat",
        "corpus": "Case DB event fixtures with normal, pre-1980, future, and baseline-comparison timestamps",
        "oracle": "clock-skew known-answer manifest, acquisition notes, trusted external timestamp comparison",
        "required_checks": (
            "parsed timestamp range emitted",
            "skew warning records emitted",
            "warning count summarized",
            "baseline requirement disclosed",
            "heuristic limitation emitted",
        ),
    },
    {
        "number": 99,
        "title": "Evidence contamination warning",
        "surface": "evidence roots, staged output location, zero-byte sources, stat failures, write-blocker integration status, and review warnings",
        "corpus": "Case DB evidence-source fixtures with output-under-evidence, staged-under-root, zero-byte source, and stat-failure cases",
        "oracle": "contamination checklist, acquisition metadata, filesystem stat evidence, and write-blocker policy",
        "required_checks": (
            "contamination warning records emitted",
            "warning count summarized",
            "output-under-evidence checks emitted",
            "write-blocker integration limitation emitted",
            "review-required flag emitted",
        ),
    },
    {
        "number": 100,
        "title": "Tamper-evident audit bundle",
        "surface": "generated output hashes, previous-entry hash chain, entry hashes, head hash, verification steps, and signing limitation",
        "corpus": "Reviewer bundle fixtures with report exports, exhibit index, selected evidence, bundle audit, and deterministic output hashing",
        "oracle": "tamper-evident bundle recomputation, archive hash manifest, and external signing/notarization evidence",
        "required_checks": (
            "generated output hashes captured",
            "previous-entry hash chain generated",
            "entry hashes emitted",
            "head hash recorded",
            "external signing limitation emitted",
        ),
    },
    {
        "number": 101,
        "title": "Windows signed installer",
        "surface": "Windows installer plan, Authenticode requirements, timestamp authority evidence, SHA256, and fresh Windows smoke logs",
        "corpus": "Release artifact fixtures with portable ZIP, packaging plan, Windows smoke script, and signing evidence placeholders",
        "oracle": "Get-AuthenticodeSignature output, timestamp authority proof, release manifest, and Windows smoke summary",
        "required_checks": (
            "windows installer target declared",
            "authenticode evidence requirement recorded",
            "timestamp authority requirement recorded",
            "windows smoke test requirement recorded",
            "external signing blocker disclosed",
        ),
    },
    {
        "number": 102,
        "title": "macOS notarized package",
        "surface": "macOS pkg/dmg plan, codesign verification, notarization ticket, Gatekeeper assessment, and smoke logs",
        "corpus": "Release artifact fixtures with packaging plan, macOS/Linux smoke script, and notarization evidence placeholders",
        "oracle": "codesign --verify output, notarytool status, spctl Gatekeeper assessment, release manifest, and smoke summary",
        "required_checks": (
            "macos package target declared",
            "codesign evidence requirement recorded",
            "notarization requirement recorded",
            "gatekeeper smoke requirement recorded",
            "external notarization blocker disclosed",
        ),
    },
    {
        "number": 103,
        "title": "Linux package/deb/rpm/AppImage",
        "surface": "portable ZIP, wheel/sdist, deb/rpm/AppImage packaging plan, dependency inventory, and Linux smoke requirements",
        "corpus": "Release artifact fixtures with dependency inventory, packaging plan, checksum manifest, and Linux smoke placeholders",
        "oracle": "package manager install logs, dependency resolution logs, SHA256SUMS, release manifest, and Linux smoke summary",
        "required_checks": (
            "linux package targets declared",
            "portable zip or python distribution generated",
            "dependency inventory generated",
            "linux smoke requirement recorded",
            "package wrapper blocker disclosed",
        ),
    },
    {
        "number": 104,
        "title": "Auto-update channel",
        "surface": "update manifest, artifact hashes, manual channel policy, enterprise disable flag, rollback guidance, and signature policy",
        "corpus": "Release artifact fixtures with update-manifest.json and packaging-plan update-channel rows",
        "oracle": "signed update manifest checklist, rollback test evidence, hosted-channel policy, and enterprise-disable review",
        "required_checks": (
            "update manifest generated",
            "artifact hashes recorded",
            "enterprise disable recorded",
            "rollback guidance recorded",
            "public hosting/signing blocker disclosed",
        ),
    },
    {
        "number": 105,
        "title": "Crash reporting",
        "surface": "local crash reports, redacted context, runtime metadata, local-only policy, and operator export workflow",
        "corpus": "Crash report fixtures with sensitive context keys, local output paths, and API exception handling",
        "oracle": "redaction checklist, local filesystem crash report, and no-upload enterprise policy review",
        "required_checks": (
            "local crash report written",
            "sensitive context redacted",
            "runtime metadata captured",
            "no-upload policy recorded",
            "operator export limitation disclosed",
        ),
    },
    {
        "number": 106,
        "title": "Telemetry-free/local-only enterprise mode",
        "surface": "telemetry disabled state, crash/evidence upload policy, localhost bind default, and remote auth-token guard",
        "corpus": "Enterprise policy fixtures with default local-only mode and remote-auth environment variations",
        "oracle": "network policy checklist, enterprise deployment guide, and API bind/auth configuration evidence",
        "required_checks": (
            "telemetry disabled recorded",
            "evidence/crash upload disabled recorded",
            "localhost default recorded",
            "remote auth token requirement recorded",
            "local-only limitation disclosed",
        ),
    },
    {
        "number": 107,
        "title": "License/activation system",
        "surface": "offline license file record, hash/size, network activation disabled, evidence-touch denial, and optional paid-flow blocker",
        "corpus": "Enterprise policy fixtures with absent, present, missing, and unreadable license-file states",
        "oracle": "license handling checklist, no-evidence-touch review, and offline activation policy",
        "required_checks": (
            "license requirement state recorded",
            "offline license hash captured when present",
            "network activation disabled recorded",
            "evidence-touch false recorded",
            "paid activation blocker disclosed",
        ),
    },
    {
        "number": 108,
        "title": "Role-based access control",
        "surface": "roles, active role, permission matrix, export controls, admin-only backup policy, and enforcement-scope caveat",
        "corpus": "Enterprise policy fixtures for local-analyst, viewer, admin, and unsupported role settings",
        "oracle": "RBAC matrix review, API auth tests, export-control checklist, and multi-user enforcement plan",
        "required_checks": (
            "role matrix emitted",
            "active role evaluated",
            "active permissions emitted",
            "export controls recorded",
            "per-action enforcement blocker disclosed",
        ),
    },
    {
        "number": 109,
        "title": "Multi-user case server",
        "surface": "multi-user disabled guard, required enablement checklist, network guardrails, conflict/locking blockers, and security-review gate",
        "corpus": "Enterprise policy fixtures documenting not-enabled multi-user server state and required controls",
        "oracle": "multi-user architecture checklist, auth/locking/concurrency tests, and independent security review",
        "required_checks": (
            "multi-user disabled state recorded",
            "network guardrails emitted",
            "identity provider requirement recorded",
            "locking/conflict requirement recorded",
            "security review blocker disclosed",
        ),
    },
    {
        "number": 110,
        "title": "Collaboration audit trail",
        "surface": "collaboration audit scope, recorded fields, tamper-evidence linkage, identity model, and multi-user conflict caveat",
        "corpus": "Enterprise policy and Case DB audit fixtures with review/export audit rows and hash-chain outputs",
        "oracle": "audit trail checklist, append-only policy, reviewer identity matrix, and export hash-chain verification",
        "required_checks": (
            "audit trail scope recorded",
            "recorded fields listed",
            "tamper evidence linkage recorded",
            "identity model caveat recorded",
            "multi-user conflict blocker disclosed",
        ),
    },
    {
        "number": 111,
        "title": "Backup/restore/migration",
        "surface": "case database backup manifest, WAL/SHM copy, hashes, schema inventory, restore verification, and migration readiness",
        "corpus": "Case DB backup/restore fixtures with schema_info, table inventory, backup manifest, and restored database hash checks",
        "oracle": "backup manifest, restore rehearsal log, SHA256 comparison, migration corpus, and schema compatibility checklist",
        "required_checks": (
            "backup manifest generated",
            "database hashes captured",
            "schema inventory captured",
            "restore hash verified",
            "migration rehearsal requirement recorded",
        ),
    },
    {
        "number": 112,
        "title": "Release notes/changelog discipline",
        "surface": "release notes template, changelog sections, known limits, migration notes, validation state, and checksum references",
        "corpus": "Release package fixtures with release notes template, release checklist, validation package, and release manifest",
        "oracle": "release note CI gate, changelog review, checksum manifest, and known-limits disclosure",
        "required_checks": (
            "release notes template packaged",
            "known limits section required",
            "validation state section required",
            "migration notes section required",
            "CI changelog blocker disclosed",
        ),
    },
    {
        "number": 113,
        "title": "LTS branch/hotfix policy",
        "surface": "LTS support window, hotfix branch policy, emergency patch criteria, backport validation, and release gating",
        "corpus": "Documentation fixtures with rapidtriage-lts-hotfix-policy.md and release validation package references",
        "oracle": "branch policy review, hotfix checklist, backport validation log, and release-owner signoff",
        "required_checks": (
            "LTS policy document packaged",
            "hotfix criteria documented",
            "backport validation documented",
            "emergency patch gate documented",
            "operator maintenance blocker disclosed",
        ),
    },
    {
        "number": 114,
        "title": "Support SLA documentation",
        "surface": "severity levels, response targets, escalation, secure evidence intake, patch targets, and staffed support blocker",
        "corpus": "Support SLA template fixtures in validation package and release ZIP",
        "oracle": "contractual SLA review, support desk staffing evidence, secure intake process, and patch delivery records",
        "required_checks": (
            "support SLA document packaged",
            "severity levels emitted",
            "response targets emitted",
            "secure intake requirement emitted",
            "staffed support blocker disclosed",
        ),
    },
    {
        "number": 115,
        "title": "Training curriculum",
        "surface": "analyst/admin curriculum, labs, validation exercises, scoring rubric, and release package inclusion",
        "corpus": "Training curriculum documentation fixtures and release ZIP packaging evidence",
        "oracle": "training syllabus review, lab execution logs, trainee scoring rubric, and instructor signoff",
        "required_checks": (
            "training curriculum packaged",
            "analyst curriculum documented",
            "admin curriculum documented",
            "validation exercise documented",
            "training delivery blocker disclosed",
        ),
    },
    {
        "number": 116,
        "title": "Analyst quickstart lab",
        "surface": "sample case, ingest/search/review/report workflow, reviewer bundle verification, and quickstart instructions",
        "corpus": "Sample workflow fixtures, smoke tests, training guide, and quickstart documentation",
        "oracle": "quickstart lab run log, sample case expected outputs, reviewer bundle hash verification, and analyst checklist",
        "required_checks": (
            "quickstart lab documented",
            "sample workflow command recorded",
            "ingest/search/review/report steps documented",
            "bundle verification documented",
            "real training run blocker disclosed",
        ),
    },
    {
        "number": 117,
        "title": "Admin deployment guide",
        "surface": "install/update/auth/backup/logging/security deployment guide, release verification, and smoke testing",
        "corpus": "Admin deployment documentation fixtures and release package inclusion evidence",
        "oracle": "admin deployment checklist, fresh-machine smoke logs, backup drill, and security hardening review",
        "required_checks": (
            "admin guide packaged",
            "install/update guidance documented",
            "auth/network guidance documented",
            "backup/restore guidance documented",
            "deployment proof blocker disclosed",
        ),
    },
    {
        "number": 118,
        "title": "Security hardening review",
        "surface": "auth, path handling, export rendering, crash redaction, dependency monitoring, parser safety, and independent AppSec blocker",
        "corpus": "Enterprise policy, admin guide, security policy, preview sandbox metadata, and release evidence fixtures",
        "oracle": "independent AppSec report, threat model, dependency scan, path traversal tests, and export-rendering security tests",
        "required_checks": (
            "security baseline emitted",
            "auth/network hardening documented",
            "export rendering safety documented",
            "crash redaction documented",
            "independent AppSec blocker disclosed",
        ),
    },
    {
        "number": 119,
        "title": "Malicious evidence sandboxing",
        "surface": "bounded/read-only previews, active-content blocking, parser crash isolation, hostile evidence guidance, and OS sandbox blocker",
        "corpus": "Preview sandbox fixtures, parser-crash tests, reviewer export CSP evidence, and admin guide hostile-evidence notes",
        "oracle": "malicious file corpus, process sandbox policy, active-content renderer tests, and AppSec review",
        "required_checks": (
            "preview sandboxing documented",
            "active content blocking documented",
            "parser crash isolation documented",
            "hostile evidence guidance documented",
            "OS sandbox blocker disclosed",
        ),
    },
    {
        "number": 120,
        "title": "Dependency vulnerability monitoring",
        "surface": "dependency inventory, optional pip-audit output, advisory policy, release-blocking severity rule, and CI scheduling blocker",
        "corpus": "Dependency monitoring script output, release dependency inventory, validation package, and release evidence checks",
        "oracle": "SBOM/advisory scan output, pip-audit or equivalent, CI scheduled job, and release-owner exception approval",
        "required_checks": (
            "dependency inventory emitted",
            "vulnerability scan attempted",
            "release blocking policy recorded",
            "dependency monitoring script packaged",
            "CI scheduled scan blocker disclosed",
        ),
    },
)


def build_core_forensics_accuracy_profiles() -> dict[str, object]:
    profiles = [build_accuracy_profile(item) for item in CORE_FORENSIC_ACCURACY_ITEMS]
    return {
        "version": CORE_FORENSIC_ACCURACY_VERSION,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "scope": "#1-#120 validation and accuracy reinforcement",
        "profile_count": len(profiles),
        "commercial_gap_ids": [f"#{item['number']}" for item in profiles],
        "status": "accuracy-profiles-ready",
        "release_gate": "Each #1-#120 parser/legal/operations claim must attach pass/fail evidence against its profile before report-grade wording.",
        "profiles": profiles,
    }


def build_core_forensics_known_answer_template() -> dict[str, object]:
    profiles = [build_accuracy_profile(item) for item in CORE_FORENSIC_ACCURACY_ITEMS]
    return {
        "version": CORE_FORENSIC_ACCURACY_VERSION,
        "status": "template-not-run",
        "item_count": len(profiles),
        "instructions": [
            "Replace source/evidence_paths with real corpora before using this as validation evidence.",
            "Keep status as not-run/open/fail until every required check has observed evidence.",
            "Only status=pass datasets with present evidence paths can satisfy commercial-readiness validation gates.",
        ],
        "datasets": [known_answer_dataset_for_profile(profile) for profile in profiles],
    }


def build_accuracy_profile(item: Mapping[str, object]) -> dict[str, object]:
    number = int(item["number"])
    required_checks = list(item["required_checks"])
    return {
        "number": number,
        "gap_id": f"#{number}",
        "title": str(item["title"]),
        "surface": str(item["surface"]),
        "known_answer_corpus_requirement": str(item["corpus"]),
        "oracle": str(item["oracle"]),
        "required_checks": required_checks,
        "minimum_evidence": [
            "source file or export hash",
            "tool/parser version and command",
            "expected-answer manifest",
            "observed RapidTriage output",
            "record-level or row-level diff",
            "reviewer sign-off and limitation note",
        ],
        "accuracy_controls": {
            "source_provenance_required": True,
            "offset_or_record_id_required": number <= 25,
            "hash_required": True,
            "timezone_or_timestamp_semantics_required": number in {
                1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 20, 22, 23, 24, 26, 27, 29, 31, 32,
                33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 45, 49, 51, 55, 57, 58, 59, 64, 65, 66, 67,
                86, 88, 89, 90, 91, 96, 97, 98, 101, 102, 103, 104, 105, 110, 111, 112, 113, 114,
            },
            "secret_redaction_required": number in {19, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 40, 41, 42, 63, 105, 107},
            "legal_or_authority_gate_required": number in {19, 22, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 63, 64, 65, 81, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 96, 97, 98, 99, 100, 101, 102, 104, 105, 107, 108, 109, 110, 111, 114, 118, 119, 120},
            "cross_tool_diff_required": True,
            "known_answer_required": True,
        },
        "pass_fail_rules": [
            "pass only when every required_check has explicit observed evidence",
            "fail when parser output loses record order, source path/hash, record ID, offset/source index, or timestamp semantics required by the profile",
            "fail when a recovered/deleted/native-candidate artifact is reportable without secondary validation",
            "open when fixture evidence exists but broad corpus or cross-tool validation is not attached",
        ],
        "default_reportability": "validation-required",
        "commercial_grade_ready": False,
    }


def known_answer_dataset_for_profile(profile: Mapping[str, object]) -> dict[str, object]:
    number = int(profile["number"])
    return {
        "id": f"core-forensics-{number:02d}",
        "name": f"#{number} {profile['title']} known-answer validation",
        "source": str(profile["known_answer_corpus_requirement"]),
        "corpus_family": "core-forensics",
        "status": "not-run",
        "backlog_items": [str(number)],
        "evidence_paths": [],
        "expected": {
            "oracle": profile["oracle"],
            "required_checks": list(profile["required_checks"]),
            "minimum_evidence": list(profile["minimum_evidence"]),
            "pass_fail_rules": list(profile["pass_fail_rules"]),
        },
        "notes": "Attach source hashes, RapidTriage output, oracle output, diff, and reviewer sign-off.",
    }


def build_accuracy_gate(
    number: int,
    *,
    satisfied_checks: list[str] | tuple[str, ...] | None = None,
    evidence_refs: list[str] | tuple[str, ...] | None = None,
    status: str = "validation-required",
) -> dict[str, object]:
    profile = accuracy_profile_for_item(number)
    satisfied = [str(item) for item in (satisfied_checks or []) if str(item)]
    required = [str(item) for item in profile["required_checks"]]
    missing = [item for item in required if item not in satisfied]
    return {
        "profile_version": CORE_FORENSIC_ACCURACY_VERSION,
        "gap_id": profile["gap_id"],
        "title": profile["title"],
        "status": status,
        "required_checks": required,
        "satisfied_checks": satisfied,
        "missing_required_checks": missing,
        "minimum_evidence": list(profile["minimum_evidence"]),
        "accuracy_controls": dict(profile["accuracy_controls"]),
        "evidence_refs": [str(item) for item in (evidence_refs or []) if str(item)],
        "default_reportability": profile["default_reportability"],
        "commercial_grade_ready": False,
        "next_validation_step": (
            "Attach known-answer corpus output, cross-tool diff, and reviewer sign-off before report-grade claims."
        ),
    }


def accuracy_profile_for_item(number: int) -> dict[str, object]:
    for item in CORE_FORENSIC_ACCURACY_ITEMS:
        if int(item["number"]) == number:
            return build_accuracy_profile(item)
    raise KeyError(f"unknown #1-#120 forensic accuracy item: {number}")
