#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify RapidTriage release evidence folders")
    parser.add_argument("--release-dir", default="release", help="Directory containing release artifacts")
    parser.add_argument("--validation-dir", default="release-validation", help="Directory containing validation package")
    parser.add_argument("--benchmark-dir", default="release-benchmark", help="Directory containing benchmark output")
    parser.add_argument(
        "--columnar-benchmark-dir",
        help="Directory containing optional columnar-benchmark output for high-volume ArtifactRecord evidence",
    )
    parser.add_argument("--smoke-dir", action="append", default=[], help="Smoke output directory; repeat per platform")
    parser.add_argument("--minimum-smoke-count", type=int, default=1, help="Minimum required passing smoke summaries")
    parser.add_argument(
        "--require-smoke-platform",
        action="append",
        default=[],
        help="Required passing smoke platform label; repeat for windows, macos-linux, or custom labels",
    )
    parser.add_argument(
        "--crash-smoke-json",
        help="Optional crash-export-smoke.json generated on the release host",
    )
    parser.add_argument(
        "--crash-redaction-review-json",
        help="Optional crash-redaction-review.json generated from the crash export bundle",
    )
    parser.add_argument(
        "--parser-sandbox-smoke-json",
        help="Optional parser-sandbox-smoke.json generated on the release host",
    )
    parser.add_argument(
        "--dependency-monitoring-json",
        help="Optional dependency-monitoring JSON generated by scripts/check-dependencies.py",
    )
    parser.add_argument(
        "--security-hardening-review-json",
        help="Optional security-hardening-review JSON generated by scripts/security-hardening-review.py",
    )
    parser.add_argument(
        "--external-release-evidence-json",
        help="Optional external commercial evidence JSON covering items 1-8 from the external evidence plan",
    )
    parser.add_argument(
        "--hostile-evidence-containment-json",
        help="Optional hostile evidence containment JSON covering items 9-13 from the external evidence plan",
    )
    parser.add_argument(
        "--independent-operations-evidence-json",
        help="Optional independent validation and operations evidence JSON covering items 14-18 from the external evidence plan",
    )
    parser.add_argument("--output-dir", default="release-evidence", help="Directory for evidence verification report")
    args = parser.parse_args(argv)

    release_dir = Path(args.release_dir).expanduser().resolve()
    validation_dir = Path(args.validation_dir).expanduser().resolve()
    benchmark_dir = Path(args.benchmark_dir).expanduser().resolve()
    columnar_benchmark_dir = (
        Path(args.columnar_benchmark_dir).expanduser().resolve() if args.columnar_benchmark_dir else None
    )
    smoke_dirs = [Path(value).expanduser().resolve() for value in args.smoke_dir]
    crash_smoke_json = Path(args.crash_smoke_json).expanduser().resolve() if args.crash_smoke_json else None
    crash_redaction_review_json = (
        Path(args.crash_redaction_review_json).expanduser().resolve() if args.crash_redaction_review_json else None
    )
    parser_sandbox_smoke_json = (
        Path(args.parser_sandbox_smoke_json).expanduser().resolve() if args.parser_sandbox_smoke_json else None
    )
    dependency_monitoring_json = (
        Path(args.dependency_monitoring_json).expanduser().resolve() if args.dependency_monitoring_json else None
    )
    security_hardening_review_json = (
        Path(args.security_hardening_review_json).expanduser().resolve()
        if args.security_hardening_review_json
        else None
    )
    external_release_evidence_json = (
        Path(args.external_release_evidence_json).expanduser().resolve()
        if args.external_release_evidence_json
        else None
    )
    hostile_evidence_containment_json = (
        Path(args.hostile_evidence_containment_json).expanduser().resolve()
        if args.hostile_evidence_containment_json
        else None
    )
    independent_operations_evidence_json = (
        Path(args.independent_operations_evidence_json).expanduser().resolve()
        if args.independent_operations_evidence_json
        else None
    )
    required_smoke_platforms = [normalize_platform_label(value) for value in args.require_smoke_platform if value.strip()]
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    checks: list[dict[str, Any]] = []
    checks.extend(check_release_artifacts(release_dir))
    checks.extend(check_validation_package(validation_dir))
    checks.extend(check_benchmark_output(benchmark_dir))
    if columnar_benchmark_dir is not None:
        checks.extend(check_columnar_benchmark_output(columnar_benchmark_dir))
    else:
        checks.append(
            make_skip_check(
                "columnar-benchmark-not-provided",
                "optional columnar benchmark evidence not requested; pass --columnar-benchmark-dir to verify it",
            )
        )
    checks.extend(
        check_smoke_outputs(
            smoke_dirs,
            minimum_smoke_count=args.minimum_smoke_count,
            required_platforms=required_smoke_platforms,
        )
    )
    checks.extend(
        check_security_operations_evidence(
            crash_smoke_json=crash_smoke_json,
            crash_redaction_review_json=crash_redaction_review_json,
            parser_sandbox_smoke_json=parser_sandbox_smoke_json,
            dependency_monitoring_json=dependency_monitoring_json,
            security_hardening_review_json=security_hardening_review_json,
        )
    )
    checks.extend(check_external_release_evidence(external_release_evidence_json))
    checks.extend(check_hostile_evidence_containment(hostile_evidence_containment_json))
    checks.extend(check_independent_operations_evidence(independent_operations_evidence_json))
    passed = all(item["status"] in {"pass", "skip"} for item in checks if item.get("required", True))

    payload = {
        "command": "verify-release-evidence",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "passed": passed,
        "release_gate": "pass" if passed else "fail",
        "inputs": {
            "release_dir": str(release_dir),
            "validation_dir": str(validation_dir),
            "benchmark_dir": str(benchmark_dir),
            "columnar_benchmark_dir": str(columnar_benchmark_dir) if columnar_benchmark_dir is not None else "",
            "smoke_dirs": [str(path) for path in smoke_dirs],
            "crash_smoke_json": str(crash_smoke_json) if crash_smoke_json is not None else "",
            "crash_redaction_review_json": str(crash_redaction_review_json)
            if crash_redaction_review_json is not None
            else "",
            "parser_sandbox_smoke_json": str(parser_sandbox_smoke_json)
            if parser_sandbox_smoke_json is not None
            else "",
            "dependency_monitoring_json": str(dependency_monitoring_json)
            if dependency_monitoring_json is not None
            else "",
            "security_hardening_review_json": str(security_hardening_review_json)
            if security_hardening_review_json is not None
            else "",
            "external_release_evidence_json": str(external_release_evidence_json)
            if external_release_evidence_json is not None
            else "",
            "hostile_evidence_containment_json": str(hostile_evidence_containment_json)
            if hostile_evidence_containment_json is not None
            else "",
            "independent_operations_evidence_json": str(independent_operations_evidence_json)
            if independent_operations_evidence_json is not None
            else "",
            "minimum_smoke_count": args.minimum_smoke_count,
            "required_smoke_platforms": required_smoke_platforms,
        },
        "checks": checks,
        "summary": build_summary(checks),
        "next_actions": build_next_actions(checks),
    }

    json_path = output_dir / "release-evidence-report.json"
    markdown_path = output_dir / "release-evidence-report.md"
    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(payload), encoding="utf-8")

    print(f"Wrote release evidence JSON: {json_path}")
    print(f"Wrote release evidence Markdown: {markdown_path}")
    print(f"Release evidence result: {'PASS' if payload['passed'] else 'FAIL'}")
    return 0 if payload["passed"] else 1


def check_release_artifacts(release_dir: Path) -> list[dict[str, Any]]:
    checks = [
        check_path("release-dir", release_dir, is_dir=True),
        check_path("release-portable-zip", release_dir / "rapidtriage-portable.zip"),
        check_path("release-sha256s", release_dir / "SHA256SUMS"),
        check_path("release-manifest", release_dir / "release-manifest.json"),
        check_path("release-dependency-inventory", release_dir / "dependency-inventory.txt"),
        check_path("release-commercial-readiness-json", release_dir / "rapidtriage-commercial-readiness.json"),
        check_path("release-commercial-readiness-markdown", release_dir / "rapidtriage-commercial-readiness.md"),
    ]
    checks.append(check_sha256s(release_dir))
    checks.append(check_release_manifest(release_dir))
    checks.append(check_commercial_readiness_disclosure(release_dir))
    return checks


def check_validation_package(validation_dir: Path) -> list[dict[str, Any]]:
    json_path = validation_dir / "rapidtriage-validation-package.json"
    markdown_path = validation_dir / "rapidtriage-validation-report.md"
    checks = [
        check_path("validation-dir", validation_dir, is_dir=True),
        check_path("validation-json", json_path),
        check_path("validation-markdown", markdown_path),
    ]
    payload = read_json(json_path)
    status = payload.get("status") if isinstance(payload, dict) else None
    checks.append(
        make_check(
            "validation-status",
            status == "release-validation-package-ready",
            f"status={status or 'missing'}",
            path=json_path,
        )
    )
    return checks


def check_benchmark_output(benchmark_dir: Path) -> list[dict[str, Any]]:
    json_path = benchmark_dir / "rapidtriage-benchmark.json"
    markdown_path = benchmark_dir / "rapidtriage-benchmark.md"
    checks = [
        check_path("benchmark-dir", benchmark_dir, is_dir=True),
        check_path("benchmark-json", json_path),
        check_path("benchmark-markdown", markdown_path),
    ]
    payload = read_json(json_path)
    metrics = payload.get("metrics") if isinstance(payload, dict) else None
    ingest_seconds = metrics.get("ingest_seconds") if isinstance(metrics, dict) else None
    search_p50 = metrics.get("search_p50_seconds") if isinstance(metrics, dict) else None
    checks.append(
        make_check(
            "benchmark-metrics",
            isinstance(ingest_seconds, (int, float)) and ingest_seconds >= 0
            and isinstance(search_p50, (int, float))
            and search_p50 >= 0,
            f"ingest_seconds={ingest_seconds}, search_p50_seconds={search_p50}",
            path=json_path,
        )
    )
    return checks


def check_columnar_benchmark_output(columnar_dir: Path) -> list[dict[str, Any]]:
    json_path = columnar_dir / "columnar-benchmark.json"
    markdown_path = columnar_dir / "columnar-benchmark.md"
    jsonl_path = columnar_dir / "artifact-records.jsonl"
    checks = [
        check_path("columnar-benchmark-dir", columnar_dir, is_dir=True),
        check_path("columnar-benchmark-json", json_path),
        check_path("columnar-benchmark-markdown", markdown_path),
        check_path("columnar-benchmark-jsonl", jsonl_path),
    ]
    payload = read_json(json_path)
    if not isinstance(payload, dict):
        checks.append(make_check("columnar-benchmark-payload", False, "payload missing or invalid", path=json_path))
        return checks

    record_count = payload.get("record_count")
    jsonl = payload.get("jsonl_baseline") if isinstance(payload.get("jsonl_baseline"), dict) else {}
    parquet = payload.get("parquet") if isinstance(payload.get("parquet"), dict) else {}
    duckdb_query = payload.get("duckdb_parquet_query") if isinstance(payload.get("duckdb_parquet_query"), dict) else {}
    environment = payload.get("environment") if isinstance(payload.get("environment"), dict) else {}
    readiness = payload.get("commercial_readiness") if isinstance(payload.get("commercial_readiness"), dict) else {}

    checks.append(
        make_check(
            "columnar-benchmark-payload",
            payload.get("command") == "columnar-benchmark" and isinstance(record_count, int) and record_count > 0,
            f"command={payload.get('command')}, record_count={record_count}",
            path=json_path,
        )
    )
    checks.append(
        make_check(
            "columnar-benchmark-jsonl-metrics",
            jsonl.get("status") == "written"
            and jsonl.get("record_count") == record_count
            and jsonl.get("rejected_count") == 0
            and isinstance(jsonl.get("query_seconds_p50"), (int, float))
            and isinstance(jsonl.get("query_seconds_p95"), (int, float))
            and isinstance(jsonl.get("query_match_count"), int),
            (
                f"status={jsonl.get('status')}, record_count={jsonl.get('record_count')}, "
                f"rejected={jsonl.get('rejected_count')}, p50={jsonl.get('query_seconds_p50')}, "
                f"p95={jsonl.get('query_seconds_p95')}"
            ),
            path=json_path,
        )
    )
    checks.append(
        make_check(
            "columnar-benchmark-environment",
            isinstance(environment.get("python_version"), str)
            and isinstance(environment.get("platform"), str)
            and isinstance(environment.get("dependency_versions"), dict),
            (
                f"platform={environment.get('platform')}, python={environment.get('python_version')}, "
                f"dependencies={sorted(environment.get('dependency_versions', {}).keys()) if isinstance(environment.get('dependency_versions'), dict) else []}"
            ),
            path=json_path,
        )
    )
    checks.extend(check_columnar_parquet_and_query(columnar_dir, parquet, duckdb_query, record_count, json_path))
    checks.append(
        make_check(
            "columnar-benchmark-commercial-disclosure",
            readiness.get("ready_for_1m_10m_claim") is False
            and isinstance(readiness.get("blockers"), list)
            and "#66" in readiness.get("commercial_gap_ids", []),
            (
                f"ready_for_1m_10m_claim={readiness.get('ready_for_1m_10m_claim')}, "
                f"blockers={len(readiness.get('blockers', [])) if isinstance(readiness.get('blockers'), list) else 'missing'}"
            ),
            path=json_path,
        )
    )
    return checks


def check_columnar_parquet_and_query(
    columnar_dir: Path,
    parquet: dict[str, Any],
    duckdb_query: dict[str, Any],
    record_count: Any,
    json_path: Path,
) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    parquet_status = parquet.get("status")
    if parquet_status == "written":
        manifest = parquet.get("manifest") if isinstance(parquet.get("manifest"), dict) else {}
        parquet_path = Path(str(parquet.get("path") or columnar_dir / "artifact-records.parquet"))
        checks.append(check_path("columnar-benchmark-parquet-file", parquet_path))
        checks.append(
            make_check(
                "columnar-benchmark-parquet-manifest",
                parquet.get("record_count") == record_count
                and parquet.get("rejected_count") == 0
                and manifest.get("streaming_safe") is True
                and isinstance(manifest.get("row_group_count"), int),
                (
                    f"record_count={parquet.get('record_count')}, rejected={parquet.get('rejected_count')}, "
                    f"streaming_safe={manifest.get('streaming_safe')}, row_groups={manifest.get('row_group_count')}"
                ),
                path=json_path,
            )
        )
    elif parquet_status == "skipped":
        checks.append(
            make_skip_check(
                "columnar-benchmark-parquet-file",
                f"Parquet output skipped: {parquet.get('reason')}; {parquet.get('install_hint', '')}",
                path=json_path,
            )
        )
        checks.append(
            make_skip_check(
                "columnar-benchmark-parquet-manifest",
                "Parquet manifest unavailable because Parquet output was skipped",
                path=json_path,
            )
        )
    else:
        checks.append(
            make_check(
                "columnar-benchmark-parquet-file",
                False,
                f"unexpected parquet status={parquet_status}",
                path=json_path,
            )
        )
        checks.append(
            make_check(
                "columnar-benchmark-parquet-manifest",
                False,
                f"unexpected parquet status={parquet_status}",
                path=json_path,
            )
        )

    duckdb_status = duckdb_query.get("status")
    if duckdb_status == "queried":
        checks.append(
            make_check(
                "columnar-benchmark-duckdb-query",
                duckdb_query.get("query_match_count") is not None
                and isinstance(duckdb_query.get("query_seconds_p50"), (int, float))
                and isinstance(duckdb_query.get("query_seconds_p95"), (int, float)),
                (
                    f"match_count={duckdb_query.get('query_match_count')}, "
                    f"p50={duckdb_query.get('query_seconds_p50')}, p95={duckdb_query.get('query_seconds_p95')}"
                ),
                path=json_path,
            )
        )
    elif duckdb_status == "skipped":
        checks.append(
            make_skip_check(
                "columnar-benchmark-duckdb-query",
                f"DuckDB query skipped: {duckdb_query.get('reason')}; {duckdb_query.get('install_hint', '')}",
                path=json_path,
            )
        )
    else:
        checks.append(
            make_check(
                "columnar-benchmark-duckdb-query",
                False,
                f"unexpected DuckDB query status={duckdb_status}",
                path=json_path,
            )
        )
    return checks


def check_smoke_outputs(
    smoke_dirs: list[Path],
    *,
    minimum_smoke_count: int,
    required_platforms: list[str],
) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    passing = 0
    passing_platforms: set[str] = set()
    for index, smoke_dir in enumerate(smoke_dirs, start=1):
        label = smoke_dir.name or f"smoke-{index}"
        json_path = smoke_dir / "smoke-summary.json"
        markdown_path = smoke_dir / "smoke-summary.md"
        checks.append(check_path(f"smoke-{label}-dir", smoke_dir, is_dir=True))
        checks.append(check_path(f"smoke-{label}-json", json_path))
        checks.append(check_path(f"smoke-{label}-markdown", markdown_path))
        payload = read_json(json_path)
        passed = bool(payload.get("passed")) if isinstance(payload, dict) else False
        platform_label = infer_smoke_platform(smoke_dir, payload)
        if passed:
            passing += 1
            passing_platforms.add(platform_label)
        checks.append(
            make_check(
                f"smoke-{label}-status",
                passed,
                f"passed={passed}, platform={platform_label}",
                path=json_path,
            )
        )

    checks.append(
        make_check(
            "smoke-minimum-count",
            passing >= minimum_smoke_count,
            f"passing={passing}, required={minimum_smoke_count}",
        )
    )
    for platform_label in required_platforms:
        checks.append(
            make_check(
                f"smoke-platform-{platform_label}",
                platform_label in passing_platforms,
                f"passing_platforms={sorted(passing_platforms)}, required={platform_label}",
            )
        )
    return checks


def check_security_operations_evidence(
    *,
    crash_smoke_json: Path | None,
    crash_redaction_review_json: Path | None,
    parser_sandbox_smoke_json: Path | None,
    dependency_monitoring_json: Path | None,
    security_hardening_review_json: Path | None,
) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    checks.extend(check_crash_export_smoke(crash_smoke_json))
    checks.extend(check_crash_redaction_review(crash_redaction_review_json))
    checks.extend(check_parser_sandbox_smoke(parser_sandbox_smoke_json))
    checks.extend(check_dependency_monitoring_evidence(dependency_monitoring_json))
    checks.extend(check_security_hardening_review(security_hardening_review_json))
    return checks


def check_crash_export_smoke(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "crash-export-smoke-not-provided",
                "optional #105 crash export smoke evidence not requested; pass --crash-smoke-json to verify it",
            )
        ]
    checks = [check_path("crash-export-smoke-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("crash-export-smoke-payload", False, "payload missing or invalid", path=path))
        return checks

    failed_ids = payload.get("failed_check_ids")
    checks.append(
        make_check(
            "crash-export-smoke-payload",
            payload.get("command") == "crash-export-smoke"
            and payload.get("profile_version") == "crash-export-release-smoke-v1",
            f"command={payload.get('command')}, profile={payload.get('profile_version')}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "crash-export-smoke-checks",
            isinstance(failed_ids, list)
            and not failed_ids
            and payload.get("commercial_claim_allowed") is False
            and payload.get("checks", {}).get("no_automatic_upload") is True,
            f"failed_check_ids={failed_ids}, commercial_claim_allowed={payload.get('commercial_claim_allowed')}",
            path=path,
        )
    )
    bundle_path = Path(str(payload.get("export_bundle_path") or "")).expanduser()
    expected_bundle_hash = payload.get("export_bundle_sha256")
    bundle_exists = bundle_path.is_file()
    bundle_hash_matches = (
        isinstance(expected_bundle_hash, str)
        and len(expected_bundle_hash) == 64
        and bundle_exists
        and hashlib.sha256(bundle_path.read_bytes()).hexdigest() == expected_bundle_hash
    )
    checks.append(
        make_check(
            "crash-export-smoke-bundle-hash",
            bundle_hash_matches,
            f"bundle_exists={bundle_exists}, bundle_sha256={expected_bundle_hash}",
            path=bundle_path,
        )
    )
    checks.append(
        make_check(
            "crash-export-smoke-manifest-hash",
            isinstance(payload.get("export_manifest_hash"), str)
            and len(str(payload.get("export_manifest_hash"))) == 64
            and isinstance(payload.get("smoke_hash"), str)
            and len(str(payload.get("smoke_hash"))) == 64,
            f"manifest_hash={payload.get('export_manifest_hash')}, smoke_hash={payload.get('smoke_hash')}",
            path=path,
        )
    )
    return checks


def check_crash_redaction_review(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "crash-redaction-review-not-provided",
                "optional #105 crash redaction/export review not requested; pass --crash-redaction-review-json to verify it",
            )
        ]
    checks = [check_path("crash-redaction-review-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("crash-redaction-review-payload", False, "payload missing or invalid", path=path))
        return checks

    trusted_diff = payload.get("trusted_crash_report_diff") if isinstance(payload.get("trusted_crash_report_diff"), dict) else {}
    failed_ids = payload.get("failed_check_ids")
    checks.append(
        make_check(
            "crash-redaction-review-payload",
            payload.get("command") == "crash-redaction-review"
            and payload.get("profile_version") == "crash-redaction-export-review-v1",
            f"command={payload.get('command')}, profile={payload.get('profile_version')}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "crash-redaction-review-checks",
            isinstance(failed_ids, list)
            and not failed_ids
            and trusted_diff.get("status") == "pass"
            and payload.get("commercial_claim_allowed") is False,
            (
                f"failed_check_ids={failed_ids}, trusted_diff_status={trusted_diff.get('status')}, "
                f"commercial_claim_allowed={payload.get('commercial_claim_allowed')}"
            ),
            path=path,
        )
    )
    bundle_path = Path(str(payload.get("export_bundle_path") or "")).expanduser()
    expected_bundle_hash = payload.get("export_bundle_sha256")
    bundle_exists = bundle_path.is_file()
    bundle_hash_matches = (
        isinstance(expected_bundle_hash, str)
        and len(expected_bundle_hash) == 64
        and bundle_exists
        and hashlib.sha256(bundle_path.read_bytes()).hexdigest() == expected_bundle_hash
    )
    checks.append(
        make_check(
            "crash-redaction-review-bundle-hash",
            bundle_hash_matches,
            f"bundle_exists={bundle_exists}, bundle_sha256={expected_bundle_hash}",
            path=bundle_path,
        )
    )
    checks.append(
        make_check(
            "crash-redaction-review-hash",
            isinstance(payload.get("review_hash"), str) and len(str(payload.get("review_hash"))) == 64,
            f"review_hash={payload.get('review_hash')}",
            path=path,
        )
    )
    return checks


def check_parser_sandbox_smoke(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "parser-sandbox-smoke-not-provided",
                "optional #119 parser isolation smoke evidence not requested; pass --parser-sandbox-smoke-json to verify it",
            )
        ]
    checks = [check_path("parser-sandbox-smoke-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("parser-sandbox-smoke-payload", False, "payload missing or invalid", path=path))
        return checks

    failed_ids = payload.get("failed_check_ids")
    boundary = payload.get("sandbox_boundary") if isinstance(payload.get("sandbox_boundary"), dict) else {}
    checks.append(
        make_check(
            "parser-sandbox-smoke-payload",
            payload.get("command") == "parser-sandbox-smoke"
            and payload.get("profile_version") == "parser-subprocess-isolation-smoke-v1",
            f"command={payload.get('command')}, profile={payload.get('profile_version')}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "parser-sandbox-smoke-checks",
            isinstance(failed_ids, list)
            and not failed_ids
            and payload.get("commercial_claim_allowed") is False
            and boundary.get("active_content_execution_allowed") is False
            and boundary.get("network_probe_performed") is False,
            f"failed_check_ids={failed_ids}, boundary={boundary}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "parser-sandbox-smoke-limitation-preserved",
            boundary.get("os_level_sandbox_enabled") is False
            and "os_level_sandbox_claim_blocked" in payload.get("checks", {}),
            f"os_level_sandbox_enabled={boundary.get('os_level_sandbox_enabled')}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "parser-sandbox-smoke-hash",
            isinstance(payload.get("smoke_hash"), str) and len(str(payload.get("smoke_hash"))) == 64,
            f"smoke_hash={payload.get('smoke_hash')}",
            path=path,
        )
    )
    return checks


def check_dependency_monitoring_evidence(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "dependency-monitoring-not-provided",
                "optional #120 dependency monitoring evidence not requested; pass --dependency-monitoring-json to verify it",
            )
        ]
    checks = [check_path("dependency-monitoring-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("dependency-monitoring-payload", False, "payload missing or invalid", path=path))
        return checks

    commercial_ids = payload.get("commercial_gap_ids") if isinstance(payload.get("commercial_gap_ids"), list) else []
    checks.append(
        make_check(
            "dependency-monitoring-payload",
            payload.get("command") == "dependency-monitoring" and "#120" in commercial_ids,
            f"command={payload.get('command')}, commercial_gap_ids={commercial_ids}",
            path=path,
        )
    )
    ci_evidence = (
        payload.get("dependency_ci_workflow_evidence")
        if isinstance(payload.get("dependency_ci_workflow_evidence"), dict)
        else {}
    )
    passed_ci_checks = ci_evidence.get("passed_checks") if isinstance(ci_evidence.get("passed_checks"), list) else []
    checks.append(
        make_check(
            "dependency-monitoring-ci-workflow",
            ci_evidence.get("configured") is True
            and "scheduled_trigger" in passed_ci_checks
            and "artifact_upload_configured" in passed_ci_checks
            and "sbom_archived_in_dependency_artifact" in passed_ci_checks,
            f"configured={ci_evidence.get('configured')}, passed_checks={passed_ci_checks}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "dependency-monitoring-sbom-hash",
            isinstance(payload.get("dependency_sbom_manifest_hash"), str)
            and len(str(payload.get("dependency_sbom_manifest_hash"))) == 64
            and isinstance(payload.get("dependency_monitoring_evidence_manifest_hash"), str)
            and len(str(payload.get("dependency_monitoring_evidence_manifest_hash"))) == 64,
            (
                f"sbom_hash={payload.get('dependency_sbom_manifest_hash')}, "
                f"manifest_hash={payload.get('dependency_monitoring_evidence_manifest_hash')}"
            ),
            path=path,
        )
    )
    vulnerability_scan = payload.get("vulnerability_scan") if isinstance(payload.get("vulnerability_scan"), dict) else {}
    checks.append(
        make_check(
            "dependency-monitoring-release-policy",
            "Block release" in str(vulnerability_scan.get("release_policy") or ""),
            f"release_policy={vulnerability_scan.get('release_policy')}",
            path=path,
        )
    )
    trusted_diff = (
        payload.get("trusted_dependency_monitoring_diff")
        if isinstance(payload.get("trusted_dependency_monitoring_diff"), dict)
        else {}
    )
    checks.append(
        make_check(
            "dependency-monitoring-limitation-preserved",
            trusted_diff.get("status") == "missing"
            and "trusted-dependency-advisory-sbom-diff-missing" in payload.get("blockers", []),
            f"trusted_diff_status={trusted_diff.get('status')}, blockers={payload.get('blockers')}",
            path=path,
        )
    )
    return checks


def check_security_hardening_review(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "security-hardening-review-not-provided",
                "optional #118 security hardening self-review not requested; pass --security-hardening-review-json to verify it",
            )
        ]
    checks = [check_path("security-hardening-review-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("security-hardening-review-payload", False, "payload missing or invalid", path=path))
        return checks

    failed_ids = payload.get("failed_check_ids")
    commercial_ids = payload.get("commercial_gap_ids") if isinstance(payload.get("commercial_gap_ids"), list) else []
    checks.append(
        make_check(
            "security-hardening-review-payload",
            payload.get("command") == "security-hardening-review"
            and payload.get("profile_version") == "security-hardening-release-review-v1"
            and "#118" in commercial_ids,
            f"command={payload.get('command')}, profile={payload.get('profile_version')}, gaps={commercial_ids}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "security-hardening-review-checks",
            isinstance(failed_ids, list)
            and not failed_ids
            and payload.get("commercial_claim_allowed") is False,
            f"failed_check_ids={failed_ids}, commercial_claim_allowed={payload.get('commercial_claim_allowed')}",
            path=path,
        )
    )
    checks.append(
        make_check(
            "security-hardening-review-hashes",
            isinstance(payload.get("review_hash"), str)
            and len(str(payload.get("review_hash"))) == 64
            and isinstance(payload.get("baseline_manifest_hash"), str)
            and len(str(payload.get("baseline_manifest_hash"))) == 64
            and isinstance(payload.get("control_evidence_matrix_hash"), str)
            and len(str(payload.get("control_evidence_matrix_hash"))) == 64,
            (
                f"review_hash={payload.get('review_hash')}, "
                f"baseline_hash={payload.get('baseline_manifest_hash')}, "
                f"control_matrix_hash={payload.get('control_evidence_matrix_hash')}"
            ),
            path=path,
        )
    )
    checks_payload = payload.get("checks") if isinstance(payload.get("checks"), dict) else {}
    checks.append(
        make_check(
            "security-hardening-review-boundaries",
            checks_payload.get("telemetry_uploads_disabled") is True
            and checks_payload.get("remote_bind_requires_auth") is True
            and checks_payload.get("appsec_blocker_preserved") is True
            and checks_payload.get("os_sandbox_limitation_preserved") is True,
            f"checks={checks_payload}",
            path=path,
        )
    )
    return checks


def check_external_release_evidence(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "external-release-evidence-not-provided",
                "optional 1-8 external commercial evidence not requested; pass --external-release-evidence-json to verify it",
            )
        ]
    checks = [check_path("external-release-evidence-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("external-release-evidence-payload", False, "payload missing or invalid", path=path))
        return checks

    checks.append(
        make_check(
            "external-release-evidence-payload",
            payload.get("profile_version") == "external-commercial-evidence-v1"
            and payload.get("scope") == "release-artifact-evidence-1-8",
            f"profile={payload.get('profile_version')}, scope={payload.get('scope')}",
            path=path,
        )
    )
    items = payload.get("items") if isinstance(payload.get("items"), list) else []
    by_number = {item.get("number"): item for item in items if isinstance(item, dict)}
    missing = [number for number in range(1, 9) if number not in by_number]
    checks.append(
        make_check(
            "external-release-evidence-item-coverage",
            not missing,
            f"items={sorted(by_number)}, missing={missing}",
            path=path,
        )
    )
    for number in range(1, 9):
        item = by_number.get(number)
        if isinstance(item, dict):
            checks.append(check_external_release_evidence_item(number, item, path))
    checks.append(
        make_check(
            "external-release-evidence-package-hash",
            isinstance(payload.get("evidence_package_hash"), str)
            and len(str(payload.get("evidence_package_hash"))) == 64,
            f"evidence_package_hash={payload.get('evidence_package_hash')}",
            path=path,
        )
    )
    return checks


def check_external_release_evidence_item(number: int, item: dict[str, Any], path: Path) -> dict[str, Any]:
    status = item.get("status")
    required_files = item.get("required_files") if isinstance(item.get("required_files"), list) else []
    file_rows_ok = all(check_external_file_row(row) for row in required_files if isinstance(row, dict))
    has_required_files = bool(required_files)
    checks = item.get("checks") if isinstance(item.get("checks"), dict) else {}
    predicates = {
        1: bool(item.get("ci_run_url")) and checks.get("ci_artifact_attached") is True,
        2: bool(item.get("sbom_path") or item.get("sbom_url")) and checks.get("sbom_hash_matches_release") is True,
        3: checks.get("authenticode_valid") is True and bool(item.get("certificate_subject")),
        4: checks.get("windows_11_smoke_passed") is True and "windows" in str(item.get("platform", "")).lower(),
        5: checks.get("codesign_verified") is True
        and checks.get("notarization_accepted") is True
        and checks.get("gatekeeper_accepted") is True,
        6: checks.get("gatekeeper_smoke_passed") is True and "mac" in str(item.get("platform", "")).lower(),
        7: checks.get("install_smoke_passed") is True and checks.get("uninstall_smoke_passed") is True,
        8: checks.get("verifier_schema_updated") is True
        and checks.get("missing_evidence_fails") is True
        and checks.get("attached_hashes_checked") is True,
    }
    passed = status == "pass" and has_required_files and file_rows_ok and predicates.get(number, False)
    return make_check(
        f"external-release-evidence-item-{number:02d}",
        passed,
        (
            f"status={status}, required_files={len(required_files)}, file_rows_ok={file_rows_ok}, "
            f"predicate={predicates.get(number, False)}"
        ),
        path=path,
    )


def check_external_file_row(row: dict[str, Any]) -> bool:
    expected = row.get("sha256")
    file_path = row.get("path")
    if not isinstance(expected, str) or len(expected) != 64 or not isinstance(file_path, str) or not file_path:
        return False
    candidate = Path(file_path).expanduser()
    return candidate.is_file() and hashlib.sha256(candidate.read_bytes()).hexdigest().lower() == expected.lower()


def check_hostile_evidence_containment(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "hostile-evidence-containment-not-provided",
                "optional 9-13 hostile evidence containment package not requested; pass --hostile-evidence-containment-json to verify it",
            )
        ]
    checks = [check_path("hostile-evidence-containment-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("hostile-evidence-containment-payload", False, "payload missing or invalid", path=path))
        return checks

    checks.append(
        make_check(
            "hostile-evidence-containment-payload",
            payload.get("profile_version") == "hostile-evidence-containment-v1"
            and payload.get("scope") == "hostile-evidence-containment-9-13",
            f"profile={payload.get('profile_version')}, scope={payload.get('scope')}",
            path=path,
        )
    )
    items = payload.get("items") if isinstance(payload.get("items"), list) else []
    by_number = {item.get("number"): item for item in items if isinstance(item, dict)}
    missing = [number for number in range(9, 14) if number not in by_number]
    checks.append(
        make_check(
            "hostile-evidence-containment-item-coverage",
            not missing,
            f"items={sorted(by_number)}, missing={missing}",
            path=path,
        )
    )
    for number in range(9, 14):
        item = by_number.get(number)
        if isinstance(item, dict):
            checks.append(check_hostile_evidence_containment_item(number, item, path))
    checks.append(
        make_check(
            "hostile-evidence-containment-package-hash",
            isinstance(payload.get("evidence_package_hash"), str)
            and len(str(payload.get("evidence_package_hash"))) == 64,
            f"evidence_package_hash={payload.get('evidence_package_hash')}",
            path=path,
        )
    )
    return checks


def check_hostile_evidence_containment_item(number: int, item: dict[str, Any], path: Path) -> dict[str, Any]:
    status = item.get("status")
    required_files = item.get("required_files") if isinstance(item.get("required_files"), list) else []
    file_rows_ok = all(check_external_file_row(row) for row in required_files if isinstance(row, dict))
    has_required_files = bool(required_files)
    checks = item.get("checks") if isinstance(item.get("checks"), dict) else {}
    predicates = {
        9: checks.get("threat_model_attached") is True
        and checks.get("allowed_paths_defined") is True
        and checks.get("network_policy_defined") is True
        and checks.get("resource_limits_defined") is True
        and checks.get("os_matrix_defined") is True,
        10: checks.get("os_level_sandbox_enabled") is True
        and checks.get("write_escape_blocked") is True
        and checks.get("network_blocked") is True
        and checks.get("kill_timeout_supported") is True,
        11: checks.get("path_escape_test_passed") is True
        and checks.get("network_probe_blocked") is True
        and checks.get("timeout_test_passed") is True
        and checks.get("memory_pressure_test_passed") is True
        and checks.get("active_content_test_passed") is True,
        12: checks.get("corpus_manifest_attached") is True
        and checks.get("license_notes_attached") is True
        and checks.get("expected_behavior_recorded") is True
        and checks.get("quarantine_expectations_recorded") is True
        and checks.get("artifact_families_covered") is True,
        13: checks.get("fuzz_command_recorded") is True
        and checks.get("seed_corpus_hash_recorded") is True
        and checks.get("crash_quarantine_recorded") is True
        and checks.get("timeout_count_recorded") is True
        and checks.get("no_silent_corruption") is True,
    }
    passed = status == "pass" and has_required_files and file_rows_ok and predicates.get(number, False)
    return make_check(
        f"hostile-evidence-containment-item-{number:02d}",
        passed,
        (
            f"status={status}, required_files={len(required_files)}, file_rows_ok={file_rows_ok}, "
            f"predicate={predicates.get(number, False)}"
        ),
        path=path,
    )


def check_independent_operations_evidence(path: Path | None) -> list[dict[str, Any]]:
    if path is None:
        return [
            make_skip_check(
                "independent-operations-evidence-not-provided",
                "optional 14-18 independent validation and operations package not requested; pass --independent-operations-evidence-json to verify it",
            )
        ]
    checks = [check_path("independent-operations-evidence-json", path)]
    payload = read_json(path)
    if not isinstance(payload, dict):
        checks.append(make_check("independent-operations-evidence-payload", False, "payload missing or invalid", path=path))
        return checks

    checks.append(
        make_check(
            "independent-operations-evidence-payload",
            payload.get("profile_version") == "independent-operations-evidence-v1"
            and payload.get("scope") == "independent-validation-operations-14-18",
            f"profile={payload.get('profile_version')}, scope={payload.get('scope')}",
            path=path,
        )
    )
    items = payload.get("items") if isinstance(payload.get("items"), list) else []
    by_number = {item.get("number"): item for item in items if isinstance(item, dict)}
    missing = [number for number in range(14, 19) if number not in by_number]
    checks.append(
        make_check(
            "independent-operations-evidence-item-coverage",
            not missing,
            f"items={sorted(by_number)}, missing={missing}",
            path=path,
        )
    )
    for number in range(14, 19):
        item = by_number.get(number)
        if isinstance(item, dict):
            checks.append(check_independent_operations_evidence_item(number, item, path))
    checks.append(
        make_check(
            "independent-operations-evidence-package-hash",
            isinstance(payload.get("evidence_package_hash"), str)
            and len(str(payload.get("evidence_package_hash"))) == 64,
            f"evidence_package_hash={payload.get('evidence_package_hash')}",
            path=path,
        )
    )
    return checks


def check_independent_operations_evidence_item(number: int, item: dict[str, Any], path: Path) -> dict[str, Any]:
    status = item.get("status")
    required_files = item.get("required_files") if isinstance(item.get("required_files"), list) else []
    file_rows_ok = all(check_external_file_row(row) for row in required_files if isinstance(row, dict))
    has_required_files = bool(required_files)
    checks = item.get("checks") if isinstance(item.get("checks"), dict) else {}
    predicates = {
        14: checks.get("architecture_overview_attached") is True
        and checks.get("threat_model_attached") is True
        and checks.get("auth_network_boundary_attached") is True
        and checks.get("export_rendering_policy_attached") is True
        and checks.get("sandbox_design_attached") is True
        and checks.get("dependency_report_attached") is True,
        15: bool(item.get("reviewer_identity"))
        and checks.get("signed_report_attached") is True
        and checks.get("scope_recorded") is True
        and checks.get("findings_recorded") is True
        and checks.get("exceptions_recorded") is True
        and checks.get("residual_risk_recorded") is True,
        16: bool(item.get("support_contact"))
        and checks.get("support_contact_defined") is True
        and checks.get("severity_matrix_defined") is True
        and checks.get("staffed_schedule_defined") is True
        and checks.get("escalation_owner_defined") is True
        and checks.get("secure_intake_defined") is True,
        17: checks.get("simulated_issue_recorded") is True
        and checks.get("patch_branch_recorded") is True
        and checks.get("validation_run_attached") is True
        and checks.get("signed_build_attached") is True
        and checks.get("rollback_note_attached") is True,
        18: checks.get("release_package_attached") is True
        and checks.get("platform_smoke_outputs_attached") is True
        and checks.get("signing_notarization_logs_attached") is True
        and checks.get("dependency_sbom_attached") is True
        and checks.get("sandbox_corpus_results_attached") is True
        and checks.get("appsec_signoff_attached") is True
        and checks.get("support_evidence_attached") is True
        and checks.get("remaining_blockers_owner_assigned") is True,
    }
    passed = status == "pass" and has_required_files and file_rows_ok and predicates.get(number, False)
    return make_check(
        f"independent-operations-evidence-item-{number:02d}",
        passed,
        (
            f"status={status}, required_files={len(required_files)}, file_rows_ok={file_rows_ok}, "
            f"predicate={predicates.get(number, False)}"
        ),
        path=path,
    )


def check_sha256s(release_dir: Path) -> dict[str, Any]:
    checksum_path = release_dir / "SHA256SUMS"
    if not checksum_path.is_file():
        return make_check("release-sha256-verification", False, "SHA256SUMS missing", path=checksum_path)

    failures: list[str] = []
    checked = 0
    for raw_line in checksum_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        try:
            expected, name = line.split(None, 1)
        except ValueError:
            failures.append(f"malformed row: {raw_line}")
            continue
        artifact_path = release_dir / name.strip()
        if not artifact_path.is_file():
            failures.append(f"missing artifact: {name.strip()}")
            continue
        actual = hashlib.sha256(artifact_path.read_bytes()).hexdigest()
        checked += 1
        if actual.lower() != expected.lower():
            failures.append(f"checksum mismatch: {name.strip()}")

    return make_check(
        "release-sha256-verification",
        not failures and checked > 0,
        f"checked={checked}" if not failures else "; ".join(failures),
        path=checksum_path,
    )


def check_release_manifest(release_dir: Path) -> dict[str, Any]:
    manifest_path = release_dir / "release-manifest.json"
    payload = read_json(manifest_path)
    artifacts = payload.get("artifacts") if isinstance(payload, dict) else None
    names = {str(item.get("name")) for item in artifacts if isinstance(item, dict)} if isinstance(artifacts, list) else set()
    required_names = {"rapidtriage-portable.zip", "dependency-inventory.txt"}
    missing = sorted(required_names - names)
    return make_check(
        "release-manifest-artifacts",
        isinstance(artifacts, list) and not missing,
        f"artifacts={len(artifacts) if isinstance(artifacts, list) else 0}, missing={missing}",
        path=manifest_path,
    )


def check_commercial_readiness_disclosure(release_dir: Path) -> dict[str, Any]:
    readiness_path = release_dir / "rapidtriage-commercial-readiness.json"
    payload = read_json(readiness_path)
    if not isinstance(payload, dict):
        return make_check(
            "release-commercial-readiness-disclosure",
            False,
            "commercial readiness report missing or invalid",
            path=readiness_path,
        )
    has_disclosure = (
        "commercial_claim_allowed" in payload
        and "non_commercial_count" in payload
        and "release_claim" in payload
        and isinstance(payload.get("non_commercial_items"), list)
    )
    detail = (
        f"claim_allowed={payload.get('commercial_claim_allowed')}, "
        f"non_commercial_count={payload.get('non_commercial_count')}, "
        f"status={payload.get('status')}"
    )
    return make_check("release-commercial-readiness-disclosure", has_disclosure, detail, path=readiness_path)


def check_path(check_id: str, path: Path, *, is_dir: bool = False) -> dict[str, Any]:
    exists = path.is_dir() if is_dir else path.is_file()
    kind = "directory" if is_dir else "file"
    return make_check(check_id, exists, f"{kind} {'present' if exists else 'missing'}", path=path)


def make_check(check_id: str, passed: bool, detail: str, *, path: Path | None = None) -> dict[str, Any]:
    return {
        "id": check_id,
        "status": "pass" if passed else "fail",
        "detail": detail,
        "path": str(path) if path is not None else "",
        "required": True,
        "remediation": "" if passed else remediation_for(check_id),
    }


def make_skip_check(check_id: str, detail: str, *, path: Path | None = None) -> dict[str, Any]:
    return {
        "id": check_id,
        "status": "skip",
        "detail": detail,
        "path": str(path) if path is not None else "",
        "required": False,
        "remediation": "",
    }


def build_summary(checks: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"pass": 0, "fail": 0, "skip": 0}
    for item in checks:
        status = str(item.get("status", "fail"))
        counts[status] = counts.get(status, 0) + 1
    return counts


def build_next_actions(checks: list[dict[str, Any]]) -> list[str]:
    actions: list[str] = []
    seen: set[str] = set()
    for item in checks:
        if item.get("status") != "fail":
            continue
        remediation = str(item.get("remediation") or "").strip()
        if remediation and remediation not in seen:
            actions.append(remediation)
            seen.add(remediation)
    return actions


def remediation_for(check_id: str) -> str:
    if check_id.startswith("release-"):
        return "Rebuild release artifacts, then run build-release.py --verify before attaching SHA256SUMS."
    if check_id.startswith("validation-"):
        return "Run rapidtriage validation --output-dir release-validation --overwrite and attach JSON/Markdown output."
    if check_id.startswith("benchmark-"):
        return "Run rapidtriage benchmark --output-dir release-benchmark --overwrite and attach JSON/Markdown output."
    if check_id.startswith("columnar-benchmark-"):
        return "Run rapidtriage columnar-benchmark --output-dir release-columnar-benchmark --record-count 100000 --json and attach JSON/Markdown/JSONL output; install .[columnar] for Parquet/DuckDB evidence."
    if check_id.startswith("smoke-platform-"):
        platform_label = check_id.removeprefix("smoke-platform-")
        return f"Run and summarize a passing smoke test for platform '{platform_label}', then pass it with --smoke-dir."
    if check_id.startswith("smoke-"):
        return "Run scripts/smoke-test-rapidtriage.sh or scripts/windows/smoke-test-rapidtriage.ps1 and attach smoke-summary.json/md."
    if check_id.startswith("crash-export-smoke-"):
        return "Run python scripts/crash-export-smoke.py --output-dir logs/crash-export-smoke --json and pass --crash-smoke-json."
    if check_id.startswith("crash-redaction-review-"):
        return "Run python scripts/crash-redaction-review.py logs/crash-export-smoke/crash-export-smoke.json --json and pass --crash-redaction-review-json."
    if check_id.startswith("parser-sandbox-smoke-"):
        return "Run python scripts/parser-sandbox-smoke.py --output logs/parser-sandbox-smoke.json --json and pass --parser-sandbox-smoke-json."
    if check_id.startswith("dependency-monitoring-"):
        return "Run python scripts/check-dependencies.py --output logs/dependency-monitoring.json and pass --dependency-monitoring-json."
    if check_id.startswith("security-hardening-review-"):
        return "Run python scripts/security-hardening-review.py --output logs/security-hardening-review.json --json and pass --security-hardening-review-json."
    if check_id.startswith("external-release-evidence-"):
        return "Attach docs/rapidtriage-external-commercial-evidence-plan.md items 1-8 as external-commercial-evidence-v1 JSON and pass --external-release-evidence-json."
    if check_id.startswith("hostile-evidence-containment-"):
        return "Attach docs/rapidtriage-external-commercial-evidence-plan.md items 9-13 as hostile-evidence-containment-v1 JSON and pass --hostile-evidence-containment-json."
    if check_id.startswith("independent-operations-evidence-"):
        return "Attach docs/rapidtriage-external-commercial-evidence-plan.md items 14-18 as independent-operations-evidence-v1 JSON and pass --independent-operations-evidence-json."
    return "Review the failed release evidence check and attach the missing or corrected artifact."


def infer_smoke_platform(smoke_dir: Path, payload: Any) -> str:
    if isinstance(payload, dict):
        value = payload.get("platform")
        if isinstance(value, str) and value.strip():
            return normalize_platform_label(value)
    return normalize_platform_label(smoke_dir.name)


def normalize_platform_label(value: str) -> str:
    cleaned = value.strip().lower().replace("_", "-")
    if cleaned in {"win", "windows", "windows-latest"} or "windows" in cleaned:
        return "windows"
    if cleaned in {"mac", "macos", "macos-latest", "darwin"} or "macos" in cleaned or "darwin" in cleaned:
        return "macos-linux"
    if cleaned in {"linux", "ubuntu", "ubuntu-latest"} or "linux" in cleaned or "ubuntu" in cleaned:
        return "macos-linux"
    return cleaned or "unknown"


def read_json(path: Path) -> Any:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def render_markdown(payload: dict[str, Any]) -> str:
    checks = payload.get("checks") if isinstance(payload.get("checks"), list) else []
    lines = [
        "# RapidTriage Release Evidence Report",
        "",
        f"- Result: {'PASS' if payload.get('passed') else 'FAIL'}",
        f"- Generated: `{payload.get('generated_at', '')}`",
        f"- Release dir: `{payload.get('inputs', {}).get('release_dir', '')}`",
        f"- Validation dir: `{payload.get('inputs', {}).get('validation_dir', '')}`",
        f"- Benchmark dir: `{payload.get('inputs', {}).get('benchmark_dir', '')}`",
        f"- Columnar benchmark dir: `{payload.get('inputs', {}).get('columnar_benchmark_dir', '')}`",
        f"- Smoke dirs: `{', '.join(payload.get('inputs', {}).get('smoke_dirs', []))}`",
        f"- Crash smoke JSON: `{payload.get('inputs', {}).get('crash_smoke_json', '')}`",
        f"- Crash redaction review JSON: `{payload.get('inputs', {}).get('crash_redaction_review_json', '')}`",
        f"- Parser sandbox smoke JSON: `{payload.get('inputs', {}).get('parser_sandbox_smoke_json', '')}`",
        f"- Dependency monitoring JSON: `{payload.get('inputs', {}).get('dependency_monitoring_json', '')}`",
        f"- Security hardening review JSON: `{payload.get('inputs', {}).get('security_hardening_review_json', '')}`",
        f"- External release evidence JSON: `{payload.get('inputs', {}).get('external_release_evidence_json', '')}`",
        f"- Hostile evidence containment JSON: `{payload.get('inputs', {}).get('hostile_evidence_containment_json', '')}`",
        f"- Independent operations evidence JSON: `{payload.get('inputs', {}).get('independent_operations_evidence_json', '')}`",
        f"- Required smoke platforms: `{', '.join(payload.get('inputs', {}).get('required_smoke_platforms', []))}`",
        f"- Release gate: `{payload.get('release_gate', '')}`",
        "",
        "| Check | Status | Detail | Path |",
        "| --- | --- | --- | --- |",
    ]
    for item in checks:
        if not isinstance(item, dict):
            continue
        lines.append(
            f"| {item.get('id', '')} | {item.get('status', '')} | {item.get('detail', '')} | `{item.get('path', '')}` |"
        )
    next_actions = payload.get("next_actions") if isinstance(payload.get("next_actions"), list) else []
    if next_actions:
        lines.extend(["", "## Next Actions", ""])
        for action in next_actions:
            lines.append(f"- {action}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
